// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// HtTrendline wraps ferro_ta_core cycle::ht_trendline.
//
// Hilbert Transform Instantaneous Trendline (Ehlers). Smooths price over the dominant cycle period.
func HtTrendline(close []float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("HtTrendline", C.ft_ht_trendline(inPtr(close), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// HtDcperiod wraps ferro_ta_core cycle::ht_dcperiod.
//
// Hilbert Transform Dominant Cycle Period in bars.
func HtDcperiod(close []float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("HtDcperiod", C.ft_ht_dcperiod(inPtr(close), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// HtDcphase wraps ferro_ta_core cycle::ht_dcphase.
//
// Hilbert Transform Dominant Cycle Phase in degrees.
func HtDcphase(close []float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("HtDcphase", C.ft_ht_dcphase(inPtr(close), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// HtPhasor wraps ferro_ta_core cycle::ht_phasor.
//
// Hilbert Transform Phasor components. Returns `(inphase, quadrature)`.
func HtPhasor(close []float64) (inphase []float64, quadrature []float64, err error) {
	n := len(close)
	inphaseBuf := make([]float64, n)
	quadratureBuf := make([]float64, n)
	if err := statusError("HtPhasor", C.ft_ht_phasor(inPtr(close), C.size_t(n), (*C.double)(outPtr(inphaseBuf)), (*C.double)(outPtr(quadratureBuf)))); err != nil {
		return nil, nil, err
	}
	return inphaseBuf, quadratureBuf, nil
}

// HtSine wraps ferro_ta_core cycle::ht_sine.
//
// Hilbert Transform SineWave. Returns `(sine, leadsine)` where leadsine leads sine by 45 degrees.
func HtSine(close []float64) (sine []float64, leadsine []float64, err error) {
	n := len(close)
	sineBuf := make([]float64, n)
	leadsineBuf := make([]float64, n)
	if err := statusError("HtSine", C.ft_ht_sine(inPtr(close), C.size_t(n), (*C.double)(outPtr(sineBuf)), (*C.double)(outPtr(leadsineBuf)))); err != nil {
		return nil, nil, err
	}
	return sineBuf, leadsineBuf, nil
}

// HtTrendmode wraps ferro_ta_core cycle::ht_trendmode.
//
// Hilbert Transform Trend vs Cycle Mode: 1 = trending, 0 = cycling.
func HtTrendmode(close []float64) ([]int32, error) {
	n := len(close)
	outBuf := make([]int32, n)
	if err := statusError("HtTrendmode", C.ft_ht_trendmode(inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
