// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

// OptionKind mirrors the C FT_OPTION_* constants.
type OptionKind int32

// OptionKind values.
const (
	OptionCall OptionKind = 0
	OptionPut  OptionKind = 1
)

// DigitalKind mirrors the C FT_DIGITAL_* constants.
type DigitalKind int32

// DigitalKind values.
const (
	DigitalCashOrNothing  DigitalKind = 0
	DigitalAssetOrNothing DigitalKind = 1
)

// PricingModel mirrors the C FT_MODEL_* constants.
type PricingModel int32

// PricingModel values.
const (
	ModelBlackScholes PricingModel = 0
	ModelBlack76      PricingModel = 1
)
