// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// Supertrend wraps ferro_ta_core extended::supertrend.
//
// ATR-based Supertrend indicator.
func Supertrend(high []float64, low []float64, close []float64, timeperiod int, multiplier float64) (line []float64, direction []int8, err error) {
	n := len(high)
	if err := checkLengths("Supertrend", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	lineBuf := make([]float64, n)
	directionBuf := make([]int8, n)
	if err := statusError("Supertrend", C.ft_supertrend(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(multiplier), (*C.double)(outPtr(lineBuf)), (*C.int8_t)(outPtr(directionBuf)))); err != nil {
		return nil, nil, err
	}
	return lineBuf, directionBuf, nil
}

// Donchian wraps ferro_ta_core extended::donchian.
//
// Donchian Channels — rolling highest high / lowest low.
func Donchian(high []float64, low []float64, timeperiod int) (upper []float64, middle []float64, lower []float64, err error) {
	n := len(high)
	if err := checkLengths("Donchian", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, nil, nil, err
	}
	upperBuf := make([]float64, n)
	middleBuf := make([]float64, n)
	lowerBuf := make([]float64, n)
	if err := statusError("Donchian", C.ft_donchian(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(upperBuf)), (*C.double)(outPtr(middleBuf)), (*C.double)(outPtr(lowerBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return upperBuf, middleBuf, lowerBuf, nil
}

// KeltnerChannels wraps ferro_ta_core extended::keltner_channels.
//
// Keltner Channels — EMA +/- (multiplier x ATR).
func KeltnerChannels(high []float64, low []float64, close []float64, timeperiod int, atrPeriod int, multiplier float64) (upper []float64, middle []float64, lower []float64, err error) {
	n := len(high)
	if err := checkLengths("KeltnerChannels", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, nil, err
	}
	upperBuf := make([]float64, n)
	middleBuf := make([]float64, n)
	lowerBuf := make([]float64, n)
	if err := statusError("KeltnerChannels", C.ft_keltner_channels(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.int64_t(atrPeriod), C.double(multiplier), (*C.double)(outPtr(upperBuf)), (*C.double)(outPtr(middleBuf)), (*C.double)(outPtr(lowerBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return upperBuf, middleBuf, lowerBuf, nil
}

// ChandelierExit wraps ferro_ta_core extended::chandelier_exit.
//
// Chandelier Exit — ATR-based trailing stop levels.
func ChandelierExit(high []float64, low []float64, close []float64, timeperiod int, multiplier float64) (longExit []float64, shortExit []float64, err error) {
	n := len(high)
	if err := checkLengths("ChandelierExit", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	longExitBuf := make([]float64, n)
	shortExitBuf := make([]float64, n)
	if err := statusError("ChandelierExit", C.ft_chandelier_exit(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(multiplier), (*C.double)(outPtr(longExitBuf)), (*C.double)(outPtr(shortExitBuf)))); err != nil {
		return nil, nil, err
	}
	return longExitBuf, shortExitBuf, nil
}

// ChoppinessIndex wraps ferro_ta_core extended::choppiness_index.
//
// Choppiness Index — measures market choppiness vs trending.
func ChoppinessIndex(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("ChoppinessIndex", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("ChoppinessIndex", C.ft_choppiness_index(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// HullMa wraps ferro_ta_core extended::hull_ma.
//
// Hull Moving Average (HMA).
func HullMa(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("HullMa", C.ft_hull_ma(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Dmi wraps ferro_ta_core extended::dmi.
//
// Directional Movement Index as `(PLUS_DI, MINUS_DI, ADX)`.
func Dmi(high []float64, low []float64, close []float64, timeperiod int) (plusDi []float64, minusDi []float64, adx []float64, err error) {
	n := len(high)
	if err := checkLengths("Dmi", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, nil, err
	}
	plusDiBuf := make([]float64, n)
	minusDiBuf := make([]float64, n)
	adxBuf := make([]float64, n)
	if err := statusError("Dmi", C.ft_dmi(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(plusDiBuf)), (*C.double)(outPtr(minusDiBuf)), (*C.double)(outPtr(adxBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return plusDiBuf, minusDiBuf, adxBuf, nil
}

// WilliamsFractals wraps ferro_ta_core extended::williams_fractals.
//
// Williams Fractals: local swing high / swing low with `timeperiod` bars on each side of the pivot.
func WilliamsFractals(high []float64, low []float64, timeperiod int) (up []float64, down []float64, err error) {
	n := len(high)
	if err := checkLengths("WilliamsFractals", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, nil, err
	}
	upBuf := make([]float64, n)
	downBuf := make([]float64, n)
	if err := statusError("WilliamsFractals", C.ft_williams_fractals(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(upBuf)), (*C.double)(outPtr(downBuf)))); err != nil {
		return nil, nil, err
	}
	return upBuf, downBuf, nil
}

// Rwi wraps ferro_ta_core extended::rwi.
//
// Random Walk Index (Poulos): max over lookbacks `2..=timeperiod` of
func Rwi(high []float64, low []float64, close []float64, timeperiod int) (rwiHigh []float64, rwiLow []float64, err error) {
	n := len(high)
	if err := checkLengths("Rwi", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	rwiHighBuf := make([]float64, n)
	rwiLowBuf := make([]float64, n)
	if err := statusError("Rwi", C.ft_rwi(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(rwiHighBuf)), (*C.double)(outPtr(rwiLowBuf)))); err != nil {
		return nil, nil, err
	}
	return rwiHighBuf, rwiLowBuf, nil
}

// Ichimoku wraps ferro_ta_core extended::ichimoku.
//
// # Returns `(tenkan, kijun, senkou_a, senkou_b, chikou)` arrays. Mismatched input lengths yield all `NaN`.
func Ichimoku(high []float64, low []float64, close []float64, tenkanPeriod int, kijunPeriod int, senkouBPeriod int, displacement int) (tenkan []float64, kijun []float64, senkouA []float64, senkouB []float64, chikou []float64, err error) {
	n := len(high)
	if err := checkLengths("Ichimoku", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, nil, nil, nil, err
	}
	tenkanBuf := make([]float64, n)
	kijunBuf := make([]float64, n)
	senkouABuf := make([]float64, n)
	senkouBBuf := make([]float64, n)
	chikouBuf := make([]float64, n)
	if err := statusError("Ichimoku", C.ft_ichimoku(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(tenkanPeriod), C.int64_t(kijunPeriod), C.int64_t(senkouBPeriod), C.int64_t(displacement), (*C.double)(outPtr(tenkanBuf)), (*C.double)(outPtr(kijunBuf)), (*C.double)(outPtr(senkouABuf)), (*C.double)(outPtr(senkouBBuf)), (*C.double)(outPtr(chikouBuf)))); err != nil {
		return nil, nil, nil, nil, nil, err
	}
	return tenkanBuf, kijunBuf, senkouABuf, senkouBBuf, chikouBuf, nil
}

// ElderRay wraps ferro_ta_core extended::elder_ray.
//
// Elder Ray Index: bull power and bear power versus an EMA of close.
func ElderRay(high []float64, low []float64, close []float64, timeperiod int) (bull []float64, bear []float64, err error) {
	n := len(high)
	if err := checkLengths("ElderRay", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	bullBuf := make([]float64, n)
	bearBuf := make([]float64, n)
	if err := statusError("ElderRay", C.ft_elder_ray(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(bullBuf)), (*C.double)(outPtr(bearBuf)))); err != nil {
		return nil, nil, err
	}
	return bullBuf, bearBuf, nil
}

// Fisher wraps ferro_ta_core extended::fisher.
//
// Ehlers Fisher Transform of median price, plus a 1-bar trigger.
func Fisher(high []float64, low []float64, timeperiod int) (fisher []float64, signal []float64, err error) {
	n := len(high)
	if err := checkLengths("Fisher", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, nil, err
	}
	fisherBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	if err := statusError("Fisher", C.ft_fisher(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(fisherBuf)), (*C.double)(outPtr(signalBuf)))); err != nil {
		return nil, nil, err
	}
	return fisherBuf, signalBuf, nil
}

// Crsi wraps ferro_ta_core extended::crsi.
//
// Connors RSI: average of price RSI, streak RSI, and percent rank of ROC.
func Crsi(close []float64, timeperiod int, streakperiod int, rankperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Crsi", C.ft_crsi(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.int64_t(streakperiod), C.int64_t(rankperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Ao wraps ferro_ta_core extended::ao.
//
// Awesome Oscillator: `SMA(median, fast) − SMA(median, slow)`.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Ao(high []float64, low []float64, fastperiod int, slowperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Ao", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Ao", C.ft_ao(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Ac wraps ferro_ta_core extended::ac.
//
// Accelerator Oscillator: `AO − SMA(AO, timeperiod)`.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Ac(high []float64, low []float64, fastperiod int, slowperiod int, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Ac", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Ac", C.ft_ac(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Po wraps ferro_ta_core extended::po.
//
// Price Oscillator (SMA): `SMA(close, fast) − SMA(close, slow)`.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Po(close []float64, fastperiod int, slowperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Po", C.ft_po(inPtr(close), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Dpo wraps ferro_ta_core extended::dpo.
//
// Detrended Price Oscillator: `close[i − shift] − SMA(close, timeperiod)`, where `shift = timeperiod / 2 + 1`.
func Dpo(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Dpo", C.ft_dpo(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Rvi wraps ferro_ta_core extended::rvi.
//
// Relative Vigor Index and its 4-bar weighted signal.
func Rvi(open []float64, high []float64, low []float64, close []float64, timeperiod int) (rvi []float64, signal []float64, err error) {
	n := len(open)
	if err := checkLengths("Rvi", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	rviBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	if err := statusError("Rvi", C.ft_rvi(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(rviBuf)), (*C.double)(outPtr(signalBuf)))); err != nil {
		return nil, nil, err
	}
	return rviBuf, signalBuf, nil
}

// Cho wraps ferro_ta_core extended::cho.
//
// Chaikin Oscillator — same math as [`volume::adosc`].
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Cho(high []float64, low []float64, close []float64, volume []float64, fastperiod int, slowperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Cho", []string{"high", "low", "close", "volume"}, []int{len(high), len(low), len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Cho", C.ft_cho(inPtr(high), inPtr(low), inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Kst wraps ferro_ta_core extended::kst.
//
// Know Sure Thing: weighted sum of four ROC SMAs, plus a signal SMA.
func Kst(close []float64, roc1 int, roc2 int, roc3 int, roc4 int, sma1 int, sma2 int, sma3 int, sma4 int, signalperiod int) (kst []float64, signal []float64, err error) {
	n := len(close)
	kstBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	if err := statusError("Kst", C.ft_kst(inPtr(close), C.size_t(n), C.int64_t(roc1), C.int64_t(roc2), C.int64_t(roc3), C.int64_t(roc4), C.int64_t(sma1), C.int64_t(sma2), C.int64_t(sma3), C.int64_t(sma4), C.int64_t(signalperiod), (*C.double)(outPtr(kstBuf)), (*C.double)(outPtr(signalBuf)))); err != nil {
		return nil, nil, err
	}
	return kstBuf, signalBuf, nil
}

// Tsi wraps ferro_ta_core extended::tsi.
//
// True Strength Index and an EMA signal of that series.
func Tsi(close []float64, longperiod int, shortperiod int, signalperiod int) (tsi []float64, signal []float64, err error) {
	n := len(close)
	tsiBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	if err := statusError("Tsi", C.ft_tsi(inPtr(close), C.size_t(n), C.int64_t(longperiod), C.int64_t(shortperiod), C.int64_t(signalperiod), (*C.double)(outPtr(tsiBuf)), (*C.double)(outPtr(signalBuf)))); err != nil {
		return nil, nil, err
	}
	return tsiBuf, signalBuf, nil
}

// Vortex wraps ferro_ta_core extended::vortex.
//
// Vortex Indicator: `+VI` and `−VI` over `timeperiod`.
func Vortex(high []float64, low []float64, close []float64, timeperiod int) (plusVi []float64, minusVi []float64, err error) {
	n := len(high)
	if err := checkLengths("Vortex", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	plusViBuf := make([]float64, n)
	minusViBuf := make([]float64, n)
	if err := statusError("Vortex", C.ft_vortex(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(plusViBuf)), (*C.double)(outPtr(minusViBuf)))); err != nil {
		return nil, nil, err
	}
	return plusViBuf, minusViBuf, nil
}

// Stc wraps ferro_ta_core extended::stc.
//
// Schaff Trend Cycle: stochastic of MACD, double-smoothed (`d1`, `d2`).
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Stc(close []float64, fastperiod int, slowperiod int, cycleperiod int, d1 int, d2 int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Stc", C.ft_stc(inPtr(close), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), C.int64_t(cycleperiod), C.int64_t(d1), C.int64_t(d2), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Gator wraps ferro_ta_core extended::gator.
//
// Gator Oscillator from the Alligator jaw / teeth / lips.
func Gator(high []float64, low []float64, jawPeriod int, jawShift int, teethPeriod int, teethShift int, lipsPeriod int, lipsShift int) (upper []float64, lower []float64, err error) {
	n := len(high)
	if err := checkLengths("Gator", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, nil, err
	}
	upperBuf := make([]float64, n)
	lowerBuf := make([]float64, n)
	if err := statusError("Gator", C.ft_gator(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(jawPeriod), C.int64_t(jawShift), C.int64_t(teethPeriod), C.int64_t(teethShift), C.int64_t(lipsPeriod), C.int64_t(lipsShift), (*C.double)(outPtr(upperBuf)), (*C.double)(outPtr(lowerBuf)))); err != nil {
		return nil, nil, err
	}
	return upperBuf, lowerBuf, nil
}

// Coppock wraps ferro_ta_core extended::coppock.
//
// Coppock Curve: `WMA(ROC(roc1) + ROC(roc2), wma_period)`.
func Coppock(close []float64, wmaPeriod int, roc1 int, roc2 int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Coppock", C.ft_coppock(inPtr(close), C.size_t(n), C.int64_t(wmaPeriod), C.int64_t(roc1), C.int64_t(roc2), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Median wraps ferro_ta_core extended::median.
//
// Rolling median of `real` over `timeperiod`.
func Median(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("Median", C.ft_median(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// MedianBands wraps ferro_ta_core extended::median_bands.
//
// Median bands: rolling median of `(high + low) / 2`, ATR envelopes, and an EMA of the median.
func MedianBands(high []float64, low []float64, close []float64, timeperiod int, atrPeriod int, multiplier float64) (median []float64, upper []float64, lower []float64, medianEma []float64, err error) {
	n := len(high)
	if err := checkLengths("MedianBands", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, nil, nil, err
	}
	medianBuf := make([]float64, n)
	upperBuf := make([]float64, n)
	lowerBuf := make([]float64, n)
	medianEmaBuf := make([]float64, n)
	if err := statusError("MedianBands", C.ft_median_bands(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.int64_t(atrPeriod), C.double(multiplier), (*C.double)(outPtr(medianBuf)), (*C.double)(outPtr(upperBuf)), (*C.double)(outPtr(lowerBuf)), (*C.double)(outPtr(medianEmaBuf)))); err != nil {
		return nil, nil, nil, nil, err
	}
	return medianBuf, upperBuf, lowerBuf, medianEmaBuf, nil
}

// Mode wraps ferro_ta_core extended::mode.
//
// Rolling mode via equal-width discretization of each window.
func Mode(real []float64, timeperiod int, bins int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("Mode", C.ft_mode(inPtr(real), C.size_t(n), C.int64_t(timeperiod), C.int64_t(bins), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Alma wraps ferro_ta_core extended::alma.
//
// Arnaud Legoux Moving Average.
// Requires: sigma > 0.0 (else ErrInvalidParam).
func Alma(close []float64, timeperiod int, offset float64, sigma float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Alma", C.ft_alma(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(offset), C.double(sigma), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Zlema wraps ferro_ta_core extended::zlema.
//
// Zero-lag exponential moving average.
func Zlema(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Zlema", C.ft_zlema(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Frama wraps ferro_ta_core extended::frama.
//
// Fractal Adaptive Moving Average (Ehlers).
func Frama(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Frama", C.ft_frama(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Mcginley wraps ferro_ta_core extended::mcginley.
//
// McGinley Dynamic.
func Mcginley(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Mcginley", C.ft_mcginley(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Vidya wraps ferro_ta_core extended::vidya.
//
// Variable Index Dynamic Average (Chande).
func Vidya(close []float64, timeperiod int, cmoPeriod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Vidya", C.ft_vidya(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.int64_t(cmoPeriod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Alligator wraps ferro_ta_core extended::alligator.
//
// Bill Williams Alligator (jaw / teeth / lips).
func Alligator(high []float64, low []float64, jawPeriod int, jawShift int, teethPeriod int, teethShift int, lipsPeriod int, lipsShift int) (jaw []float64, teeth []float64, lips []float64, err error) {
	n := len(high)
	if err := checkLengths("Alligator", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, nil, nil, err
	}
	jawBuf := make([]float64, n)
	teethBuf := make([]float64, n)
	lipsBuf := make([]float64, n)
	if err := statusError("Alligator", C.ft_alligator(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(jawPeriod), C.int64_t(jawShift), C.int64_t(teethPeriod), C.int64_t(teethShift), C.int64_t(lipsPeriod), C.int64_t(lipsShift), (*C.double)(outPtr(jawBuf)), (*C.double)(outPtr(teethBuf)), (*C.double)(outPtr(lipsBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return jawBuf, teethBuf, lipsBuf, nil
}

// MaEnvelopes wraps ferro_ta_core extended::ma_envelopes.
//
// Moving-average envelopes: `MA * (1 ± percent / 100)`.
func MaEnvelopes(close []float64, timeperiod int, percent float64, matype MAType) (upper []float64, middle []float64, lower []float64, err error) {
	n := len(close)
	upperBuf := make([]float64, n)
	middleBuf := make([]float64, n)
	lowerBuf := make([]float64, n)
	if err := statusError("MaEnvelopes", C.ft_ma_envelopes(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(percent), C.int32_t(matype), (*C.double)(outPtr(upperBuf)), (*C.double)(outPtr(middleBuf)), (*C.double)(outPtr(lowerBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return upperBuf, middleBuf, lowerBuf, nil
}

// ChandeKrollStop wraps ferro_ta_core extended::chande_kroll_stop.
//
// Chande Kroll Stop.
func ChandeKrollStop(high []float64, low []float64, close []float64, timeperiod int, multiplier float64, stopPeriod int) (longStop []float64, shortStop []float64, err error) {
	n := len(high)
	if err := checkLengths("ChandeKrollStop", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	longStopBuf := make([]float64, n)
	shortStopBuf := make([]float64, n)
	if err := statusError("ChandeKrollStop", C.ft_chande_kroll_stop(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(multiplier), C.int64_t(stopPeriod), (*C.double)(outPtr(longStopBuf)), (*C.double)(outPtr(shortStopBuf)))); err != nil {
		return nil, nil, err
	}
	return longStopBuf, shortStopBuf, nil
}

// ChaikinVol wraps ferro_ta_core extended::chaikin_vol.
//
// Chaikin Volatility: rate of change of an EMA of the high–low range.
func ChaikinVol(high []float64, low []float64, timeperiod int, rocperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("ChaikinVol", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("ChaikinVol", C.ft_chaikin_vol(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), C.int64_t(rocperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Mass wraps ferro_ta_core extended::mass.
//
// Mass Index: rolling sum of the single/double EMA ratio of the high–low range.
func Mass(high []float64, low []float64, timeperiod int, sumperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Mass", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Mass", C.ft_mass(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), C.int64_t(sumperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Bbpercent wraps ferro_ta_core extended::bbpercent.
//
// Bollinger %B: `(close - lower) / (upper - lower)` from [`overlap::bbands`].
func Bbpercent(close []float64, timeperiod int, nbdevup float64, nbdevdn float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Bbpercent", C.ft_bbpercent(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(nbdevup), C.double(nbdevdn), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Bbwidth wraps ferro_ta_core extended::bbwidth.
//
// Bollinger Bandwidth: `(upper - lower) / middle` from [`overlap::bbands`].
func Bbwidth(close []float64, timeperiod int, nbdevup float64, nbdevdn float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Bbwidth", C.ft_bbwidth(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(nbdevup), C.double(nbdevdn), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// HistoricalVolatility wraps ferro_ta_core extended::historical_volatility.
//
// Close-to-close historical volatility, annualized and in percent.
func HistoricalVolatility(close []float64, timeperiod int, annual float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("HistoricalVolatility", C.ft_historical_volatility(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(annual), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// UlcerIndex wraps ferro_ta_core extended::ulcer_index.
//
// Ulcer Index: RMS of percent drawdowns versus the rolling highest close.
func UlcerIndex(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("UlcerIndex", C.ft_ulcer_index(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Starc wraps ferro_ta_core extended::starc.
//
// Stoller Average Range Channels: SMA of close ± `multiplier * ATR`.
func Starc(high []float64, low []float64, close []float64, timeperiod int, atrPeriod int, multiplier float64) (upper []float64, middle []float64, lower []float64, err error) {
	n := len(high)
	if err := checkLengths("Starc", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, nil, err
	}
	upperBuf := make([]float64, n)
	middleBuf := make([]float64, n)
	lowerBuf := make([]float64, n)
	if err := statusError("Starc", C.ft_starc(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.int64_t(atrPeriod), C.double(multiplier), (*C.double)(outPtr(upperBuf)), (*C.double)(outPtr(middleBuf)), (*C.double)(outPtr(lowerBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return upperBuf, middleBuf, lowerBuf, nil
}

// ObvSmoothed wraps ferro_ta_core extended::obv_smoothed.
//
// On-Balance Volume smoothed with [`overlap::ma`].
func ObvSmoothed(close []float64, volume []float64, timeperiod int, matype MAType) ([]float64, error) {
	n := len(close)
	if err := checkLengths("ObvSmoothed", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("ObvSmoothed", C.ft_obv_smoothed(inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), C.int32_t(matype), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cmf wraps ferro_ta_core extended::cmf.
//
// Chaikin Money Flow: rolling sum of CLV × volume over rolling volume.
func Cmf(high []float64, low []float64, close []float64, volume []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Cmf", []string{"high", "low", "close", "volume"}, []int{len(high), len(low), len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Cmf", C.ft_cmf(inPtr(high), inPtr(low), inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Emv wraps ferro_ta_core extended::emv.
//
// Ease of Movement, then SMA.
func Emv(high []float64, low []float64, volume []float64, timeperiod int, scale float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Emv", []string{"high", "low", "volume"}, []int{len(high), len(low), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Emv", C.ft_emv(inPtr(high), inPtr(low), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), C.double(scale), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// ForceIndex wraps ferro_ta_core extended::force_index.
//
// Force Index: `(close - close[1]) * volume`, optionally EMA-smoothed.
func ForceIndex(close []float64, volume []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	if err := checkLengths("ForceIndex", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("ForceIndex", C.ft_force_index(inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Nvi wraps ferro_ta_core extended::nvi.
//
// Negative Volume Index, seeded at 1000.
func Nvi(close []float64, volume []float64) ([]float64, error) {
	n := len(close)
	if err := checkLengths("Nvi", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Nvi", C.ft_nvi(inPtr(close), inPtr(volume), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// NviWithEma wraps ferro_ta_core extended::nvi_with_ema.
//
// NVI plus an EMA signal of that series.
func NviWithEma(close []float64, volume []float64, timeperiod int) (nvi []float64, signal []float64, err error) {
	n := len(close)
	if err := checkLengths("NviWithEma", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, nil, err
	}
	nviBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	if err := statusError("NviWithEma", C.ft_nvi_with_ema(inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(nviBuf)), (*C.double)(outPtr(signalBuf)))); err != nil {
		return nil, nil, err
	}
	return nviBuf, signalBuf, nil
}

// Pvi wraps ferro_ta_core extended::pvi.
//
// Positive Volume Index, seeded at 1000.
func Pvi(close []float64, volume []float64) ([]float64, error) {
	n := len(close)
	if err := checkLengths("Pvi", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Pvi", C.ft_pvi(inPtr(close), inPtr(volume), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// PviWithSignal wraps ferro_ta_core extended::pvi_with_signal.
//
// PVI plus a moving-average signal (`matype` matches `MA`, `0`-`8`).
func PviWithSignal(close []float64, volume []float64, timeperiod int, matype MAType) (pvi []float64, signal []float64, err error) {
	n := len(close)
	if err := checkLengths("PviWithSignal", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, nil, err
	}
	pviBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	if err := statusError("PviWithSignal", C.ft_pvi_with_signal(inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), C.int32_t(matype), (*C.double)(outPtr(pviBuf)), (*C.double)(outPtr(signalBuf)))); err != nil {
		return nil, nil, err
	}
	return pviBuf, signalBuf, nil
}

// Volosc wraps ferro_ta_core extended::volosc.
//
// Volume oscillator: `100 * (SMA(vol, fast) - SMA(vol, slow)) / SMA(vol, slow)`.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Volosc(volume []float64, fastperiod int, slowperiod int) ([]float64, error) {
	n := len(volume)
	outBuf := make([]float64, n)
	if err := statusError("Volosc", C.ft_volosc(inPtr(volume), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Vroc wraps ferro_ta_core extended::vroc.
//
// Volume rate of change: `100 * (volume - volume[timeperiod]) / volume[timeperiod]`.
func Vroc(volume []float64, timeperiod int) ([]float64, error) {
	n := len(volume)
	outBuf := make([]float64, n)
	if err := statusError("Vroc", C.ft_vroc(inPtr(volume), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Kvo wraps ferro_ta_core extended::kvo.
//
// Klinger Volume Oscillator and its EMA signal.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Kvo(high []float64, low []float64, close []float64, volume []float64, fastperiod int, slowperiod int, signalperiod int) (kvo []float64, signal []float64, err error) {
	n := len(high)
	if err := checkLengths("Kvo", []string{"high", "low", "close", "volume"}, []int{len(high), len(low), len(close), len(volume)}); err != nil {
		return nil, nil, err
	}
	kvoBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	if err := statusError("Kvo", C.ft_kvo(inPtr(high), inPtr(low), inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), C.int64_t(signalperiod), (*C.double)(outPtr(kvoBuf)), (*C.double)(outPtr(signalBuf)))); err != nil {
		return nil, nil, err
	}
	return kvoBuf, signalBuf, nil
}

// Pvt wraps ferro_ta_core extended::pvt.
//
// Price Volume Trend: cumulative `volume * (close - close[1]) / close[1]`.
func Pvt(close []float64, volume []float64) ([]float64, error) {
	n := len(close)
	if err := checkLengths("Pvt", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Pvt", C.ft_pvt(inPtr(close), inPtr(volume), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Rvol wraps ferro_ta_core extended::rvol.
//
// Relative volume: `volume / SMA(volume, timeperiod)`.
func Rvol(volume []float64, timeperiod int) ([]float64, error) {
	n := len(volume)
	outBuf := make([]float64, n)
	if err := statusError("Rvol", C.ft_rvol(inPtr(volume), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Vwap wraps ferro_ta_core extended::vwap.
//
// Volume Weighted Average Price (cumulative or rolling).
func Vwap(high []float64, low []float64, close []float64, volume []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Vwap", []string{"high", "low", "close", "volume"}, []int{len(high), len(low), len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Vwap", C.ft_vwap(inPtr(high), inPtr(low), inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Vwma wraps ferro_ta_core extended::vwma.
//
// Volume Weighted Moving Average.
func Vwma(close []float64, volume []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	if err := checkLengths("Vwma", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Vwma", C.ft_vwma(inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
