// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

import (
	"unsafe"
)

// Basis wraps ferro_ta_core futures::basis.
//
// Futures basis: futures - spot.
func Basis(spot float64, future float64) (float64, error) {
	var valueOut float64
	if err := statusError("Basis", C.ft_basis(C.double(spot), C.double(future), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// AnnualizedBasis wraps ferro_ta_core futures::annualized_basis.
//
// Annualized simple basis return.
func AnnualizedBasis(spot float64, future float64, timeToExpiry float64) (float64, error) {
	var valueOut float64
	if err := statusError("AnnualizedBasis", C.ft_annualized_basis(C.double(spot), C.double(future), C.double(timeToExpiry), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// ImpliedCarryRate wraps ferro_ta_core futures::implied_carry_rate.
//
// Implied continuously compounded carry rate.
func ImpliedCarryRate(spot float64, future float64, timeToExpiry float64) (float64, error) {
	var valueOut float64
	if err := statusError("ImpliedCarryRate", C.ft_implied_carry_rate(C.double(spot), C.double(future), C.double(timeToExpiry), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// CarrySpread wraps ferro_ta_core futures::carry_spread.
//
// Carry spread relative to the risk-free rate.
func CarrySpread(spot float64, future float64, rate float64, timeToExpiry float64) (float64, error) {
	var valueOut float64
	if err := statusError("CarrySpread", C.ft_carry_spread(C.double(spot), C.double(future), C.double(rate), C.double(timeToExpiry), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// RollYield wraps ferro_ta_core futures::roll_yield.
//
// Annualized roll yield from front and next prices.
func RollYield(frontPrice float64, nextPrice float64, timeToExpiry float64) (float64, error) {
	var valueOut float64
	if err := statusError("RollYield", C.ft_roll_yield(C.double(frontPrice), C.double(nextPrice), C.double(timeToExpiry), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// SyntheticForward wraps ferro_ta_core futures::synthetic_forward.
//
// Synthetic forward price from call/put parity.
func SyntheticForward(callPrice float64, putPrice float64, strike float64, rate float64, timeToExpiry float64) (float64, error) {
	var valueOut float64
	if err := statusError("SyntheticForward", C.ft_synthetic_forward(C.double(callPrice), C.double(putPrice), C.double(strike), C.double(rate), C.double(timeToExpiry), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// SyntheticSpot wraps ferro_ta_core futures::synthetic_spot.
//
// Synthetic spot price implied by call/put parity with continuous carry.
func SyntheticSpot(callPrice float64, putPrice float64, strike float64, rate float64, carry float64, timeToExpiry float64) (float64, error) {
	var valueOut float64
	if err := statusError("SyntheticSpot", C.ft_synthetic_spot(C.double(callPrice), C.double(putPrice), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// ParityGap wraps ferro_ta_core futures::parity_gap.
//
// Put-call parity residual. Zero means the inputs are parity-consistent.
func ParityGap(callPrice float64, putPrice float64, spot float64, strike float64, rate float64, carry float64, timeToExpiry float64) (float64, error) {
	var valueOut float64
	if err := statusError("ParityGap", C.ft_parity_gap(C.double(callPrice), C.double(putPrice), C.double(spot), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}
