// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// WeightedContinuous wraps ferro_ta_core futures::weighted_continuous.
//
// Weighted stitching using next-contract weights in [0, 1].
func WeightedContinuous(front []float64, next []float64, nextWeights []float64) ([]float64, error) {
	n := len(front)
	if err := checkLengths("WeightedContinuous", []string{"front", "next", "nextWeights"}, []int{len(front), len(next), len(nextWeights)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("WeightedContinuous", C.ft_weighted_continuous(inPtr(front), inPtr(next), inPtr(nextWeights), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// BackAdjustedContinuous wraps ferro_ta_core futures::back_adjusted_continuous.
//
// Back-adjusted continuous series using the roll date implied by the weights.
func BackAdjustedContinuous(front []float64, next []float64, nextWeights []float64) ([]float64, error) {
	n := len(front)
	if err := checkLengths("BackAdjustedContinuous", []string{"front", "next", "nextWeights"}, []int{len(front), len(next), len(nextWeights)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("BackAdjustedContinuous", C.ft_back_adjusted_continuous(inPtr(front), inPtr(next), inPtr(nextWeights), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RatioAdjustedContinuous wraps ferro_ta_core futures::ratio_adjusted_continuous.
//
// Ratio-adjusted continuous series using the roll date implied by the weights.
func RatioAdjustedContinuous(front []float64, next []float64, nextWeights []float64) ([]float64, error) {
	n := len(front)
	if err := checkLengths("RatioAdjustedContinuous", []string{"front", "next", "nextWeights"}, []int{len(front), len(next), len(nextWeights)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("RatioAdjustedContinuous", C.ft_ratio_adjusted_continuous(inPtr(front), inPtr(next), inPtr(nextWeights), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
