// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

// goldenFunctions maps each C export to its Go wrapper so golden_test.go
// can replay tests/fixtures/golden/ffi_golden.json by name.
var goldenFunctions = map[string]func(map[string][]float64, map[string]float64) (map[string]any, error){
	"ft_bbands": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		upper, middle, lower, err := Bbands(in["close"], int(p["timeperiod"]), p["nbdevup"], p["nbdevdn"], MAType(p["matype"]))
		return map[string]any{"out_upper": upper, "out_middle": middle, "out_lower": lower}, err
	},
	"ft_macdfix": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		macd, signal, hist, err := Macdfix(in["close"], int(p["signalperiod"]))
		return map[string]any{"out_macd": macd, "out_signal": signal, "out_hist": hist}, err
	},
	"ft_macdext": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		macd, signal, hist, err := Macdext(in["close"], int(p["fastperiod"]), MAType(p["fastmatype"]), int(p["slowperiod"]), MAType(p["slowmatype"]), int(p["signalperiod"]), MAType(p["signalmatype"]))
		return map[string]any{"out_macd": macd, "out_signal": signal, "out_hist": hist}, err
	},
	"ft_ma": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Ma(in["close"], int(p["timeperiod"]), MAType(p["matype"]))
		return map[string]any{"out": out}, err
	},
	"ft_mavp": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Mavp(in["close"], in["periods"], int(p["minperiod"]), int(p["maxperiod"]), MAType(p["matype"]))
		return map[string]any{"out": out}, err
	},
	"ft_ema": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Ema(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_dema": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Dema(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_tema": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Tema(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_t3": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := T3(in["close"], int(p["timeperiod"]), p["vfactor"])
		return map[string]any{"out": out}, err
	},
	"ft_kama": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Kama(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_macd": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		macd, signal, hist, err := Macd(in["close"], int(p["fastperiod"]), int(p["slowperiod"]), int(p["signalperiod"]))
		return map[string]any{"out_macd": macd, "out_signal": signal, "out_hist": hist}, err
	},
	"ft_mama": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		mama, fama, err := Mama(in["close"], p["fastlimit"], p["slowlimit"])
		return map[string]any{"out_mama": mama, "out_fama": fama}, err
	},
	"ft_midpoint": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Midpoint(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_midprice": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Midprice(in["high"], in["low"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_sar": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Sar(in["high"], in["low"], p["acceleration"], p["maximum"])
		return map[string]any{"out": out}, err
	},
	"ft_sarext": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Sarext(in["high"], in["low"], p["startvalue"], p["offsetonreverse"], p["accelerationinitlong"], p["accelerationlong"], p["accelerationmaxlong"], p["accelerationinitshort"], p["accelerationshort"], p["accelerationmaxshort"])
		return map[string]any{"out": out}, err
	},
	"ft_sma": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Sma(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_trima": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Trima(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_wma": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Wma(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_plus_dm": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := PlusDm(in["high"], in["low"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_minus_dm": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := MinusDm(in["high"], in["low"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_plus_di": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := PlusDi(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_minus_di": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := MinusDi(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_dx": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Dx(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_adx": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Adx(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_adxr": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Adxr(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_aroon": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		aroondown, aroonup, err := Aroon(in["high"], in["low"], int(p["timeperiod"]))
		return map[string]any{"out_aroondown": aroondown, "out_aroonup": aroonup}, err
	},
	"ft_aroonosc": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Aroonosc(in["high"], in["low"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_apo": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Apo(in["close"], int(p["fastperiod"]), int(p["slowperiod"]), MAType(p["matype"]))
		return map[string]any{"out": out}, err
	},
	"ft_ppo": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		ppo, signal, hist, err := Ppo(in["close"], int(p["fastperiod"]), int(p["slowperiod"]), int(p["signalperiod"]), MAType(p["matype"]))
		return map[string]any{"out_ppo": ppo, "out_signal": signal, "out_hist": hist}, err
	},
	"ft_trix": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Trix(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_willr": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Willr(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_cci": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cci(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_bop": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Bop(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_mom": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Mom(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_roc": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Roc(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rocp": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Rocp(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rocr": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Rocr(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rocr100": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Rocr100(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rsi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Rsi(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_cmo": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cmo(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_stoch": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		slowk, slowd, err := Stoch(in["high"], in["low"], in["close"], int(p["fastk_period"]), int(p["slowk_period"]), MAType(p["slowk_matype"]), int(p["slowd_period"]), MAType(p["slowd_matype"]))
		return map[string]any{"out_slowk": slowk, "out_slowd": slowd}, err
	},
	"ft_stochf": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		fastk, fastd, err := Stochf(in["high"], in["low"], in["close"], int(p["fastk_period"]), int(p["fastd_period"]), MAType(p["fastd_matype"]))
		return map[string]any{"out_fastk": fastk, "out_fastd": fastd}, err
	},
	"ft_stochrsi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		fastk, fastd, err := Stochrsi(in["close"], int(p["timeperiod"]), int(p["fastk_period"]), int(p["fastd_period"]), MAType(p["fastd_matype"]))
		return map[string]any{"out_fastk": fastk, "out_fastd": fastd}, err
	},
	"ft_ultosc": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Ultosc(in["high"], in["low"], in["close"], int(p["timeperiod1"]), int(p["timeperiod2"]), int(p["timeperiod3"]))
		return map[string]any{"out": out}, err
	},
	"ft_atr": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Atr(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_trange": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Trange(in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_natr": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Natr(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_obv": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Obv(in["close"], in["volume"])
		return map[string]any{"out": out}, err
	},
	"ft_mfi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Mfi(in["high"], in["low"], in["close"], in["volume"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_ad": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Ad(in["high"], in["low"], in["close"], in["volume"])
		return map[string]any{"out": out}, err
	},
	"ft_adosc": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Adosc(in["high"], in["low"], in["close"], in["volume"], int(p["fastperiod"]), int(p["slowperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_ht_trendline": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := HtTrendline(in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_ht_dcperiod": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := HtDcperiod(in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_ht_dcphase": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := HtDcphase(in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_ht_phasor": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		inphase, quadrature, err := HtPhasor(in["close"])
		return map[string]any{"out_inphase": inphase, "out_quadrature": quadrature}, err
	},
	"ft_ht_sine": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		sine, leadsine, err := HtSine(in["close"])
		return map[string]any{"out_sine": sine, "out_leadsine": leadsine}, err
	},
	"ft_ht_trendmode": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := HtTrendmode(in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_stddev": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Stddev(in["real"], int(p["timeperiod"]), p["nbdev"])
		return map[string]any{"out": out}, err
	},
	"ft_var": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Var(in["real"], int(p["timeperiod"]), p["nbdev"])
		return map[string]any{"out": out}, err
	},
	"ft_linearreg": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Linearreg(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_linearreg_slope": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := LinearregSlope(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_linearreg_intercept": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := LinearregIntercept(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_linearreg_angle": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := LinearregAngle(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_tsf": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Tsf(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_beta": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Beta(in["real0"], in["real1"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_correl": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Correl(in["real0"], in["real1"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_sum": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Sum(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_max": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Max(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_min": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Min(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_sliding_max": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := SlidingMax(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_sliding_min": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := SlidingMin(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_add": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Add(in["a"], in["b"])
		return map[string]any{"out": out}, err
	},
	"ft_sub": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Sub(in["a"], in["b"])
		return map[string]any{"out": out}, err
	},
	"ft_mult": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Mult(in["a"], in["b"])
		return map[string]any{"out": out}, err
	},
	"ft_div": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Div(in["a"], in["b"])
		return map[string]any{"out": out}, err
	},
	"ft_rolling_sum": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RollingSum(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rolling_max": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RollingMax(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rolling_min": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RollingMin(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rolling_maxindex": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RollingMaxindex(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rolling_minindex": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RollingMinindex(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_avgprice": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Avgprice(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_medprice": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Medprice(in["high"], in["low"])
		return map[string]any{"out": out}, err
	},
	"ft_typprice": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Typprice(in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_wclprice": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Wclprice(in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdl2crows": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdl2crows(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdl3blackcrows": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdl3blackcrows(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdl3inside": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdl3inside(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdl3linestrike": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdl3linestrike(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdl3outside": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdl3outside(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdl3starsinsouth": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdl3starsinsouth(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdl3whitesoldiers": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdl3whitesoldiers(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlabandonedbaby": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlabandonedbaby(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdladvanceblock": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdladvanceblock(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlbelthold": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlbelthold(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlbreakaway": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlbreakaway(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlclosingmarubozu": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlclosingmarubozu(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlconcealbabyswall": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlconcealbabyswall(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlcounterattack": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlcounterattack(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdldarkcloudcover": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdldarkcloudcover(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdldoji": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdldoji(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdldojistar": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdldojistar(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdldragonflydoji": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdldragonflydoji(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlengulfing": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlengulfing(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdleveningdojistar": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdleveningdojistar(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdleveningstar": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdleveningstar(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlgapsidesidewhite": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlgapsidesidewhite(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlgravestonedoji": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlgravestonedoji(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlhammer": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlhammer(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlhangingman": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlhangingman(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlharami": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlharami(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlharamicross": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlharamicross(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlhighwave": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlhighwave(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlhikkake": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlhikkake(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlhikkakemod": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlhikkakemod(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlhomingpigeon": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlhomingpigeon(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlidentical3crows": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlidentical3crows(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlinneck": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlinneck(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlinvertedhammer": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlinvertedhammer(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlkicking": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlkicking(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlkickingbylength": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlkickingbylength(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlladderbottom": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlladderbottom(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdllongleggeddoji": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdllongleggeddoji(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdllongline": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdllongline(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlmarubozu": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlmarubozu(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlmatchinglow": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlmatchinglow(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlmathold": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlmathold(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlmorningdojistar": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlmorningdojistar(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlmorningstar": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlmorningstar(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlonneck": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlonneck(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlpiercing": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlpiercing(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlrickshawman": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlrickshawman(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlrisefall3methods": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlrisefall3methods(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlseparatinglines": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlseparatinglines(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlshootingstar": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlshootingstar(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlshortline": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlshortline(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlspinningtop": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlspinningtop(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlstalledpattern": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlstalledpattern(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlsticksandwich": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlsticksandwich(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdltakuri": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdltakuri(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdltasukigap": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdltasukigap(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlthrusting": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlthrusting(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdltristar": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdltristar(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlunique3river": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlunique3river(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlupsidegap2crows": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlupsidegap2crows(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_cdlxsidegap3methods": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cdlxsidegap3methods(in["open"], in["high"], in["low"], in["close"])
		return map[string]any{"out": out}, err
	},
	"ft_supertrend": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		line, direction, err := Supertrend(in["high"], in["low"], in["close"], int(p["timeperiod"]), p["multiplier"])
		return map[string]any{"out_line": line, "out_direction": direction}, err
	},
	"ft_donchian": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		upper, middle, lower, err := Donchian(in["high"], in["low"], int(p["timeperiod"]))
		return map[string]any{"out_upper": upper, "out_middle": middle, "out_lower": lower}, err
	},
	"ft_keltner_channels": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		upper, middle, lower, err := KeltnerChannels(in["high"], in["low"], in["close"], int(p["timeperiod"]), int(p["atr_period"]), p["multiplier"])
		return map[string]any{"out_upper": upper, "out_middle": middle, "out_lower": lower}, err
	},
	"ft_chandelier_exit": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		longExit, shortExit, err := ChandelierExit(in["high"], in["low"], in["close"], int(p["timeperiod"]), p["multiplier"])
		return map[string]any{"out_long_exit": longExit, "out_short_exit": shortExit}, err
	},
	"ft_choppiness_index": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := ChoppinessIndex(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_hull_ma": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := HullMa(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_dmi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		plusDi, minusDi, adx, err := Dmi(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out_plus_di": plusDi, "out_minus_di": minusDi, "out_adx": adx}, err
	},
	"ft_williams_fractals": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		up, down, err := WilliamsFractals(in["high"], in["low"], int(p["timeperiod"]))
		return map[string]any{"out_up": up, "out_down": down}, err
	},
	"ft_rwi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		rwiHigh, rwiLow, err := Rwi(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out_rwi_high": rwiHigh, "out_rwi_low": rwiLow}, err
	},
	"ft_ichimoku": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		tenkan, kijun, senkouA, senkouB, chikou, err := Ichimoku(in["high"], in["low"], in["close"], int(p["tenkan_period"]), int(p["kijun_period"]), int(p["senkou_b_period"]), int(p["displacement"]))
		return map[string]any{"out_tenkan": tenkan, "out_kijun": kijun, "out_senkou_a": senkouA, "out_senkou_b": senkouB, "out_chikou": chikou}, err
	},
	"ft_elder_ray": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		bull, bear, err := ElderRay(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out_bull": bull, "out_bear": bear}, err
	},
	"ft_fisher": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		fisher, signal, err := Fisher(in["high"], in["low"], int(p["timeperiod"]))
		return map[string]any{"out_fisher": fisher, "out_signal": signal}, err
	},
	"ft_crsi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Crsi(in["close"], int(p["timeperiod"]), int(p["streakperiod"]), int(p["rankperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_ao": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Ao(in["high"], in["low"], int(p["fastperiod"]), int(p["slowperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_ac": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Ac(in["high"], in["low"], int(p["fastperiod"]), int(p["slowperiod"]), int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_po": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Po(in["close"], int(p["fastperiod"]), int(p["slowperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_dpo": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Dpo(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_rvi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		rvi, signal, err := Rvi(in["open"], in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out_rvi": rvi, "out_signal": signal}, err
	},
	"ft_cho": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cho(in["high"], in["low"], in["close"], in["volume"], int(p["fastperiod"]), int(p["slowperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_kst": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		kst, signal, err := Kst(in["close"], int(p["roc1"]), int(p["roc2"]), int(p["roc3"]), int(p["roc4"]), int(p["sma1"]), int(p["sma2"]), int(p["sma3"]), int(p["sma4"]), int(p["signalperiod"]))
		return map[string]any{"out_kst": kst, "out_signal": signal}, err
	},
	"ft_tsi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		tsi, signal, err := Tsi(in["close"], int(p["longperiod"]), int(p["shortperiod"]), int(p["signalperiod"]))
		return map[string]any{"out_tsi": tsi, "out_signal": signal}, err
	},
	"ft_vortex": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		plusVi, minusVi, err := Vortex(in["high"], in["low"], in["close"], int(p["timeperiod"]))
		return map[string]any{"out_plus_vi": plusVi, "out_minus_vi": minusVi}, err
	},
	"ft_stc": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Stc(in["close"], int(p["fastperiod"]), int(p["slowperiod"]), int(p["cycleperiod"]), int(p["d1"]), int(p["d2"]))
		return map[string]any{"out": out}, err
	},
	"ft_gator": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		upper, lower, err := Gator(in["high"], in["low"], int(p["jaw_period"]), int(p["jaw_shift"]), int(p["teeth_period"]), int(p["teeth_shift"]), int(p["lips_period"]), int(p["lips_shift"]))
		return map[string]any{"out_upper": upper, "out_lower": lower}, err
	},
	"ft_coppock": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Coppock(in["close"], int(p["wma_period"]), int(p["roc1"]), int(p["roc2"]))
		return map[string]any{"out": out}, err
	},
	"ft_median": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Median(in["real"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_median_bands": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		median, upper, lower, medianEma, err := MedianBands(in["high"], in["low"], in["close"], int(p["timeperiod"]), int(p["atr_period"]), p["multiplier"])
		return map[string]any{"out_median": median, "out_upper": upper, "out_lower": lower, "out_median_ema": medianEma}, err
	},
	"ft_mode": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Mode(in["real"], int(p["timeperiod"]), int(p["bins"]))
		return map[string]any{"out": out}, err
	},
	"ft_alma": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Alma(in["close"], int(p["timeperiod"]), p["offset"], p["sigma"])
		return map[string]any{"out": out}, err
	},
	"ft_zlema": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Zlema(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_frama": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Frama(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_mcginley": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Mcginley(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_vidya": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Vidya(in["close"], int(p["timeperiod"]), int(p["cmo_period"]))
		return map[string]any{"out": out}, err
	},
	"ft_alligator": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		jaw, teeth, lips, err := Alligator(in["high"], in["low"], int(p["jaw_period"]), int(p["jaw_shift"]), int(p["teeth_period"]), int(p["teeth_shift"]), int(p["lips_period"]), int(p["lips_shift"]))
		return map[string]any{"out_jaw": jaw, "out_teeth": teeth, "out_lips": lips}, err
	},
	"ft_ma_envelopes": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		upper, middle, lower, err := MaEnvelopes(in["close"], int(p["timeperiod"]), p["percent"], MAType(p["matype"]))
		return map[string]any{"out_upper": upper, "out_middle": middle, "out_lower": lower}, err
	},
	"ft_chande_kroll_stop": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		longStop, shortStop, err := ChandeKrollStop(in["high"], in["low"], in["close"], int(p["timeperiod"]), p["multiplier"], int(p["stop_period"]))
		return map[string]any{"out_long_stop": longStop, "out_short_stop": shortStop}, err
	},
	"ft_chaikin_vol": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := ChaikinVol(in["high"], in["low"], int(p["timeperiod"]), int(p["rocperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_mass": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Mass(in["high"], in["low"], int(p["timeperiod"]), int(p["sumperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_bbpercent": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Bbpercent(in["close"], int(p["timeperiod"]), p["nbdevup"], p["nbdevdn"])
		return map[string]any{"out": out}, err
	},
	"ft_bbwidth": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Bbwidth(in["close"], int(p["timeperiod"]), p["nbdevup"], p["nbdevdn"])
		return map[string]any{"out": out}, err
	},
	"ft_historical_volatility": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := HistoricalVolatility(in["close"], int(p["timeperiod"]), p["annual"])
		return map[string]any{"out": out}, err
	},
	"ft_ulcer_index": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := UlcerIndex(in["close"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_starc": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		upper, middle, lower, err := Starc(in["high"], in["low"], in["close"], int(p["timeperiod"]), int(p["atr_period"]), p["multiplier"])
		return map[string]any{"out_upper": upper, "out_middle": middle, "out_lower": lower}, err
	},
	"ft_obv_smoothed": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := ObvSmoothed(in["close"], in["volume"], int(p["timeperiod"]), MAType(p["matype"]))
		return map[string]any{"out": out}, err
	},
	"ft_cmf": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Cmf(in["high"], in["low"], in["close"], in["volume"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_emv": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Emv(in["high"], in["low"], in["volume"], int(p["timeperiod"]), p["scale"])
		return map[string]any{"out": out}, err
	},
	"ft_force_index": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := ForceIndex(in["close"], in["volume"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_nvi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Nvi(in["close"], in["volume"])
		return map[string]any{"out": out}, err
	},
	"ft_nvi_with_ema": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		nvi, signal, err := NviWithEma(in["close"], in["volume"], int(p["timeperiod"]))
		return map[string]any{"out_nvi": nvi, "out_signal": signal}, err
	},
	"ft_pvi": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Pvi(in["close"], in["volume"])
		return map[string]any{"out": out}, err
	},
	"ft_pvi_with_signal": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		pvi, signal, err := PviWithSignal(in["close"], in["volume"], int(p["timeperiod"]), MAType(p["matype"]))
		return map[string]any{"out_pvi": pvi, "out_signal": signal}, err
	},
	"ft_volosc": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Volosc(in["volume"], int(p["fastperiod"]), int(p["slowperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_vroc": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Vroc(in["volume"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_kvo": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		kvo, signal, err := Kvo(in["high"], in["low"], in["close"], in["volume"], int(p["fastperiod"]), int(p["slowperiod"]), int(p["signalperiod"]))
		return map[string]any{"out_kvo": kvo, "out_signal": signal}, err
	},
	"ft_pvt": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Pvt(in["close"], in["volume"])
		return map[string]any{"out": out}, err
	},
	"ft_rvol": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Rvol(in["volume"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_vwap": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Vwap(in["high"], in["low"], in["close"], in["volume"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_vwma": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Vwma(in["close"], in["volume"], int(p["timeperiod"]))
		return map[string]any{"out": out}, err
	},
	"ft_iv_rank": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := IvRank(in["iv_series"], int(p["window"]))
		return map[string]any{"out": out}, err
	},
	"ft_iv_percentile": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := IvPercentile(in["iv_series"], int(p["window"]))
		return map[string]any{"out": out}, err
	},
	"ft_iv_zscore": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := IvZscore(in["iv_series"], int(p["window"]))
		return map[string]any{"out": out}, err
	},
	"ft_close_to_close_vol": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := CloseToCloseVol(in["close"], int(p["window"]), p["trading_days"])
		return map[string]any{"out": out}, err
	},
	"ft_parkinson_vol": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := ParkinsonVol(in["high"], in["low"], int(p["window"]), p["trading_days"])
		return map[string]any{"out": out}, err
	},
	"ft_garman_klass_vol": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := GarmanKlassVol(in["open"], in["high"], in["low"], in["close"], int(p["window"]), p["trading_days"])
		return map[string]any{"out": out}, err
	},
	"ft_rogers_satchell_vol": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RogersSatchellVol(in["open"], in["high"], in["low"], in["close"], int(p["window"]), p["trading_days"])
		return map[string]any{"out": out}, err
	},
	"ft_yang_zhang_vol": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := YangZhangVol(in["open"], in["high"], in["low"], in["close"], int(p["window"]), p["trading_days"])
		return map[string]any{"out": out}, err
	},
	"ft_weighted_continuous": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := WeightedContinuous(in["front"], in["next"], in["next_weights"])
		return map[string]any{"out": out}, err
	},
	"ft_back_adjusted_continuous": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := BackAdjustedContinuous(in["front"], in["next"], in["next_weights"])
		return map[string]any{"out": out}, err
	},
	"ft_ratio_adjusted_continuous": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RatioAdjustedContinuous(in["front"], in["next"], in["next_weights"])
		return map[string]any{"out": out}, err
	},
	"ft_regime_adx": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RegimeAdx(in["adx"], p["threshold"])
		return map[string]any{"out": out}, err
	},
	"ft_regime_combined": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RegimeCombined(in["adx"], in["atr"], in["close"], p["adx_threshold"], p["atr_pct_threshold"])
		return map[string]any{"out": out}, err
	},
	"ft_detect_breaks_cusum": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := DetectBreaksCusum(in["series"], int(p["window"]), p["threshold"], p["slack"])
		return map[string]any{"out": out}, err
	},
	"ft_rolling_variance_break": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RollingVarianceBreak(in["series"], int(p["short_window"]), int(p["long_window"]), p["threshold"])
		return map[string]any{"out": out}, err
	},
	"ft_rolling_beta": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RollingBeta(in["asset"], in["benchmark"], int(p["window"]))
		return map[string]any{"out": out}, err
	},
	"ft_relative_strength": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RelativeStrength(in["asset_returns"], in["benchmark_returns"])
		return map[string]any{"out": out}, err
	},
	"ft_spread": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Spread(in["a"], in["b"], p["hedge"])
		return map[string]any{"out": out}, err
	},
	"ft_ratio": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := Ratio(in["a"], in["b"])
		return map[string]any{"out": out}, err
	},
	"ft_zscore_series": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := ZscoreSeries(in["x"], int(p["window"]))
		return map[string]any{"out": out}, err
	},
	"ft_rank_values": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RankValues(in["x"])
		return map[string]any{"out": out}, err
	},
	"ft_check_cross": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := CheckCross(in["fast"], in["slow"])
		return map[string]any{"out": out}, err
	},
	"ft_funding_cumulative_pnl": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := FundingCumulativePnl(in["position_size"], in["funding_rate"])
		return map[string]any{"out": out}, err
	},
	"ft_forward_fill_nan": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := ForwardFillNan(in["values"])
		return map[string]any{"out": out}, err
	},
	"ft_rsi_threshold_signals": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {
		out, err := RsiThresholdSignals(in["close"], int(p["timeperiod"]), p["oversold"], p["overbought"])
		return map[string]any{"out": out}, err
	},
}

// goldenScalars maps each scalar C export to its Go wrapper.
var goldenScalars = map[string]func(map[string]float64) (map[string]any, error){
	"ft_black_scholes_price": func(p map[string]float64) (map[string]any, error) {
		value, err := BlackScholesPrice(p["spot"], p["strike"], p["rate"], p["dividend_yield"], p["time_to_expiry"], p["volatility"], OptionKind(p["kind"]))
		return map[string]any{"out_value": value}, err
	},
	"ft_black_76_price": func(p map[string]float64) (map[string]any, error) {
		value, err := Black76Price(p["forward"], p["strike"], p["rate"], p["time_to_expiry"], p["volatility"], OptionKind(p["kind"]))
		return map[string]any{"out_value": value}, err
	},
	"ft_black_scholes_greeks": func(p map[string]float64) (map[string]any, error) {
		delta, gamma, vega, theta, rho, err := BlackScholesGreeks(p["spot"], p["strike"], p["rate"], p["dividend_yield"], p["time_to_expiry"], p["volatility"], OptionKind(p["kind"]))
		return map[string]any{"out_delta": delta, "out_gamma": gamma, "out_vega": vega, "out_theta": theta, "out_rho": rho}, err
	},
	"ft_black_76_greeks": func(p map[string]float64) (map[string]any, error) {
		delta, gamma, vega, theta, rho, err := Black76Greeks(p["forward"], p["strike"], p["rate"], p["time_to_expiry"], p["volatility"], OptionKind(p["kind"]))
		return map[string]any{"out_delta": delta, "out_gamma": gamma, "out_vega": vega, "out_theta": theta, "out_rho": rho}, err
	},
	"ft_black_scholes_extended_greeks": func(p map[string]float64) (map[string]any, error) {
		vanna, volga, charm, speed, color, err := BlackScholesExtendedGreeks(p["spot"], p["strike"], p["rate"], p["dividend_yield"], p["time_to_expiry"], p["volatility"], OptionKind(p["kind"]))
		return map[string]any{"out_vanna": vanna, "out_volga": volga, "out_charm": charm, "out_speed": speed, "out_color": color}, err
	},
	"ft_american_price_baw": func(p map[string]float64) (map[string]any, error) {
		value, err := AmericanPriceBaw(p["spot"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"], p["volatility"], OptionKind(p["kind"]))
		return map[string]any{"out_value": value}, err
	},
	"ft_early_exercise_premium": func(p map[string]float64) (map[string]any, error) {
		value, err := EarlyExercisePremium(p["spot"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"], p["volatility"], OptionKind(p["kind"]))
		return map[string]any{"out_value": value}, err
	},
	"ft_digital_price": func(p map[string]float64) (map[string]any, error) {
		value, err := DigitalPrice(p["spot"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"], p["volatility"], OptionKind(p["option_kind"]), DigitalKind(p["digital_kind"]))
		return map[string]any{"out_value": value}, err
	},
	"ft_digital_greeks": func(p map[string]float64) (map[string]any, error) {
		delta, gamma, vega, err := DigitalGreeks(p["spot"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"], p["volatility"], OptionKind(p["option_kind"]), DigitalKind(p["digital_kind"]))
		return map[string]any{"out_delta": delta, "out_gamma": gamma, "out_vega": vega}, err
	},
	"ft_put_call_parity_deviation": func(p map[string]float64) (map[string]any, error) {
		value, err := PutCallParityDeviation(p["call_price"], p["put_price"], p["spot"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"])
		return map[string]any{"out_value": value}, err
	},
	"ft_expected_move": func(p map[string]float64) (map[string]any, error) {
		lower, upper, err := ExpectedMove(p["spot"], p["iv"], p["days_to_expiry"], p["trading_days_per_year"])
		return map[string]any{"out_lower": lower, "out_upper": upper}, err
	},
	"ft_implied_volatility": func(p map[string]float64) (map[string]any, error) {
		value, err := ImpliedVolatility(p["target_price"], PricingModel(p["model"]), p["underlying"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"], OptionKind(p["kind"]), p["initial_guess"], p["tolerance"], int(p["max_iterations"]))
		return map[string]any{"out_value": value}, err
	},
	"ft_price_lower_bound": func(p map[string]float64) (map[string]any, error) {
		value, err := PriceLowerBound(PricingModel(p["model"]), p["underlying"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"], OptionKind(p["kind"]))
		return map[string]any{"out_value": value}, err
	},
	"ft_price_upper_bound": func(p map[string]float64) (map[string]any, error) {
		value, err := PriceUpperBound(PricingModel(p["model"]), p["underlying"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"], OptionKind(p["kind"]))
		return map[string]any{"out_value": value}, err
	},
	"ft_basis": func(p map[string]float64) (map[string]any, error) {
		value, err := Basis(p["spot"], p["future"])
		return map[string]any{"out_value": value}, err
	},
	"ft_annualized_basis": func(p map[string]float64) (map[string]any, error) {
		value, err := AnnualizedBasis(p["spot"], p["future"], p["time_to_expiry"])
		return map[string]any{"out_value": value}, err
	},
	"ft_implied_carry_rate": func(p map[string]float64) (map[string]any, error) {
		value, err := ImpliedCarryRate(p["spot"], p["future"], p["time_to_expiry"])
		return map[string]any{"out_value": value}, err
	},
	"ft_carry_spread": func(p map[string]float64) (map[string]any, error) {
		value, err := CarrySpread(p["spot"], p["future"], p["rate"], p["time_to_expiry"])
		return map[string]any{"out_value": value}, err
	},
	"ft_roll_yield": func(p map[string]float64) (map[string]any, error) {
		value, err := RollYield(p["front_price"], p["next_price"], p["time_to_expiry"])
		return map[string]any{"out_value": value}, err
	},
	"ft_synthetic_forward": func(p map[string]float64) (map[string]any, error) {
		value, err := SyntheticForward(p["call_price"], p["put_price"], p["strike"], p["rate"], p["time_to_expiry"])
		return map[string]any{"out_value": value}, err
	},
	"ft_synthetic_spot": func(p map[string]float64) (map[string]any, error) {
		value, err := SyntheticSpot(p["call_price"], p["put_price"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"])
		return map[string]any{"out_value": value}, err
	},
	"ft_parity_gap": func(p map[string]float64) (map[string]any, error) {
		value, err := ParityGap(p["call_price"], p["put_price"], p["spot"], p["strike"], p["rate"], p["carry"], p["time_to_expiry"])
		return map[string]any{"out_value": value}, err
	},
	"ft_kelly_fraction": func(p map[string]float64) (map[string]any, error) {
		value, err := KellyFraction(p["win_rate"], p["avg_win"], p["avg_loss"])
		return map[string]any{"out_value": value}, err
	},
	"ft_half_kelly_fraction": func(p map[string]float64) (map[string]any, error) {
		value, err := HalfKellyFraction(p["win_rate"], p["avg_win"], p["avg_loss"])
		return map[string]any{"out_value": value}, err
	},
}

// goldenStreams builds each streaming wrapper for golden replay.
var goldenStreams = map[string]func(map[string]float64) (goldenStepper, error){
	"sma": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamSma(int(p["period"]))
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			out, err := s.Update(bar["value"])
			return map[string]any{"out": out}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
	"ema": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamEma(int(p["period"]))
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			out, err := s.Update(bar["value"])
			return map[string]any{"out": out}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
	"rsi": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamRsi(int(p["period"]))
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			out, err := s.Update(bar["value"])
			return map[string]any{"out": out}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
	"atr": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamAtr(int(p["period"]))
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			out, err := s.Update(bar["high"], bar["low"], bar["close"])
			return map[string]any{"out": out}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
	"bbands": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamBbands(int(p["period"]), p["nbdevup"], p["nbdevdn"])
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			upper, middle, lower, err := s.Update(bar["value"])
			return map[string]any{"out_upper": upper, "out_middle": middle, "out_lower": lower}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
	"macd": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamMacd(int(p["fastperiod"]), int(p["slowperiod"]), int(p["signalperiod"]))
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			macd, signal, hist, err := s.Update(bar["value"])
			return map[string]any{"out_macd": macd, "out_signal": signal, "out_hist": hist}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
	"stoch": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamStoch(int(p["fastk_period"]), int(p["slowk_period"]), int(p["slowd_period"]))
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			slowk, slowd, err := s.Update(bar["high"], bar["low"], bar["close"])
			return map[string]any{"out_slowk": slowk, "out_slowd": slowd}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
	"vwap": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamVwap()
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			out, err := s.Update(bar["high"], bar["low"], bar["close"], bar["volume"])
			return map[string]any{"out": out}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
	"supertrend": func(p map[string]float64) (goldenStepper, error) {
		s, err := NewStreamSupertrend(int(p["period"]), p["multiplier"])
		if err != nil {
			return goldenStepper{}, err
		}
		step := func(bar map[string]float64) (map[string]any, error) {
			line, direction, err := s.Update(bar["high"], bar["low"], bar["close"])
			return map[string]any{"out_line": line, "out_direction": direction}, err
		}
		return goldenStepper{step: step, close: s.Close}, nil
	},
}
