// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// RollingSum wraps ferro_ta_core math_ops::rolling_sum.
//
// Rolling sum over `timeperiod` bars using an O(n) sliding window.
func RollingSum(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("RollingSum", C.ft_rolling_sum(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RollingMax wraps ferro_ta_core math_ops::rolling_max.
//
// Rolling maximum over `timeperiod` bars (O(n) monotonic deque).
func RollingMax(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("RollingMax", C.ft_rolling_max(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RollingMin wraps ferro_ta_core math_ops::rolling_min.
//
// Rolling minimum over `timeperiod` bars (O(n) monotonic deque).
func RollingMin(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("RollingMin", C.ft_rolling_min(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RollingMaxindex wraps ferro_ta_core math_ops::rolling_maxindex.
//
// Index of rolling maximum over `timeperiod` bars.
func RollingMaxindex(real []float64, timeperiod int) ([]int64, error) {
	n := len(real)
	outBuf := make([]int64, n)
	if err := statusError("RollingMaxindex", C.ft_rolling_maxindex(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.int64_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RollingMinindex wraps ferro_ta_core math_ops::rolling_minindex.
//
// Index of rolling minimum over `timeperiod` bars.
func RollingMinindex(real []float64, timeperiod int) ([]int64, error) {
	n := len(real)
	outBuf := make([]int64, n)
	if err := statusError("RollingMinindex", C.ft_rolling_minindex(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.int64_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
