// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// Sum wraps ferro_ta_core math::sum.
//
// Compute the rolling sum over `timeperiod` bars.
func Sum(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("Sum", C.ft_sum(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Max wraps ferro_ta_core math::max.
//
// Compute the rolling maximum over `timeperiod` bars.
func Max(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("Max", C.ft_max(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Min wraps ferro_ta_core math::min.
//
// Compute the rolling minimum over `timeperiod` bars.
func Min(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("Min", C.ft_min(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// SlidingMax wraps ferro_ta_core math::sliding_max.
//
// Compute the sliding maximum over `timeperiod` bars in O(n) time.
func SlidingMax(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("SlidingMax", C.ft_sliding_max(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// SlidingMin wraps ferro_ta_core math::sliding_min.
//
// Compute the sliding minimum over `timeperiod` bars in O(n) time.
func SlidingMin(real []float64, timeperiod int) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("SlidingMin", C.ft_sliding_min(inPtr(real), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Add wraps ferro_ta_core math::add.
//
// Element-wise addition of two arrays.
func Add(a []float64, b []float64) ([]float64, error) {
	n := len(a)
	if err := checkLengths("Add", []string{"a", "b"}, []int{len(a), len(b)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Add", C.ft_add(inPtr(a), inPtr(b), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Sub wraps ferro_ta_core math::sub.
//
// Element-wise subtraction of two arrays.
func Sub(a []float64, b []float64) ([]float64, error) {
	n := len(a)
	if err := checkLengths("Sub", []string{"a", "b"}, []int{len(a), len(b)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Sub", C.ft_sub(inPtr(a), inPtr(b), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Mult wraps ferro_ta_core math::mult.
//
// Element-wise multiplication of two arrays.
func Mult(a []float64, b []float64) ([]float64, error) {
	n := len(a)
	if err := checkLengths("Mult", []string{"a", "b"}, []int{len(a), len(b)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Mult", C.ft_mult(inPtr(a), inPtr(b), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Div wraps ferro_ta_core math::div.
//
// Element-wise division of two arrays (NaN where b=0).
func Div(a []float64, b []float64) ([]float64, error) {
	n := len(a)
	if err := checkLengths("Div", []string{"a", "b"}, []int{len(a), len(b)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Div", C.ft_div(inPtr(a), inPtr(b), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
