// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// PlusDm wraps ferro_ta_core momentum::plus_dm.
//
// Compute the Plus Directional Movement (+DM), Wilder smoothed.
func PlusDm(high []float64, low []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("PlusDm", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("PlusDm", C.ft_plus_dm(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// MinusDm wraps ferro_ta_core momentum::minus_dm.
//
// Compute the Minus Directional Movement (-DM), Wilder smoothed.
func MinusDm(high []float64, low []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("MinusDm", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("MinusDm", C.ft_minus_dm(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// PlusDi wraps ferro_ta_core momentum::plus_di.
//
// Compute the Plus Directional Indicator (+DI), Wilder smoothed.
func PlusDi(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("PlusDi", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("PlusDi", C.ft_plus_di(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// MinusDi wraps ferro_ta_core momentum::minus_di.
//
// Compute the Minus Directional Indicator (-DI), Wilder smoothed.
func MinusDi(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("MinusDi", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("MinusDi", C.ft_minus_di(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Dx wraps ferro_ta_core momentum::dx.
//
// Compute the Directional Movement Index (DX).
func Dx(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Dx", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Dx", C.ft_dx(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Adx wraps ferro_ta_core momentum::adx.
//
// Compute the Average Directional Movement Index (ADX).
func Adx(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Adx", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Adx", C.ft_adx(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Adxr wraps ferro_ta_core momentum::adxr.
//
// Compute the ADX Rating (ADXR).
func Adxr(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Adxr", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Adxr", C.ft_adxr(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Aroon wraps ferro_ta_core momentum::aroon.
//
// Aroon indicator. Returns `(aroon_down, aroon_up)`.
func Aroon(high []float64, low []float64, timeperiod int) (aroondown []float64, aroonup []float64, err error) {
	n := len(high)
	if err := checkLengths("Aroon", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, nil, err
	}
	aroondownBuf := make([]float64, n)
	aroonupBuf := make([]float64, n)
	if err := statusError("Aroon", C.ft_aroon(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(aroondownBuf)), (*C.double)(outPtr(aroonupBuf)))); err != nil {
		return nil, nil, err
	}
	return aroondownBuf, aroonupBuf, nil
}

// Aroonosc wraps ferro_ta_core momentum::aroonosc.
//
// Aroon Oscillator: `aroon_up - aroon_down`.
func Aroonosc(high []float64, low []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Aroonosc", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Aroonosc", C.ft_aroonosc(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Apo wraps ferro_ta_core momentum::apo.
//
// Absolute Price Oscillator: `fast MA - slow MA`.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Apo(close []float64, fastperiod int, slowperiod int, matype MAType) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Apo", C.ft_apo(inPtr(close), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), C.int32_t(matype), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Ppo wraps ferro_ta_core momentum::ppo.
//
// Percentage Price Oscillator: `(fast MA - slow MA) / slow MA * 100`. Returns `(ppo_line, signal_line, histogram)`.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Ppo(close []float64, fastperiod int, slowperiod int, signalperiod int, matype MAType) (ppo []float64, signal []float64, hist []float64, err error) {
	n := len(close)
	ppoBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	histBuf := make([]float64, n)
	if err := statusError("Ppo", C.ft_ppo(inPtr(close), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), C.int64_t(signalperiod), C.int32_t(matype), (*C.double)(outPtr(ppoBuf)), (*C.double)(outPtr(signalBuf)), (*C.double)(outPtr(histBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return ppoBuf, signalBuf, histBuf, nil
}

// Trix wraps ferro_ta_core momentum::trix.
//
// TRIX: 1-period rate of change of triple-smoothed EMA.
func Trix(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Trix", C.ft_trix(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Willr wraps ferro_ta_core momentum::willr.
//
// Williams %R: `-100 * (HH - close) / (HH - LL)` over the window. Returns values in `[-100, 0]`.
func Willr(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Willr", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Willr", C.ft_willr(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cci wraps ferro_ta_core momentum::cci.
//
// Commodity Channel Index: `(tp - SMA(tp)) / (0.015 * MAD)`.
func Cci(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Cci", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Cci", C.ft_cci(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Bop wraps ferro_ta_core momentum::bop.
//
// Balance of Power: `(close - open) / (high - low)`.
func Bop(open []float64, high []float64, low []float64, close []float64) ([]float64, error) {
	n := len(open)
	if err := checkLengths("Bop", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Bop", C.ft_bop(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Mom wraps ferro_ta_core momentum::mom.
//
// Compute the Momentum indicator: `close[i] - close[i - timeperiod]`.
func Mom(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Mom", C.ft_mom(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Roc wraps ferro_ta_core momentum::roc.
//
// Rate of Change: `(close[i] - close[i-p]) / close[i-p] * 100`.
func Roc(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Roc", C.ft_roc(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Rocp wraps ferro_ta_core momentum::rocp.
//
// Rate of Change Percentage: `(close[i] - close[i-p]) / close[i-p]`.
func Rocp(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Rocp", C.ft_rocp(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Rocr wraps ferro_ta_core momentum::rocr.
//
// Rate of Change Ratio: `close[i] / close[i-p]`.
func Rocr(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Rocr", C.ft_rocr(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Rocr100 wraps ferro_ta_core momentum::rocr100.
//
// Rate of Change Ratio x 100: `close[i] / close[i-p] * 100`.
func Rocr100(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Rocr100", C.ft_rocr100(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Rsi wraps ferro_ta_core momentum::rsi.
//
// Compute the Relative Strength Index (RSI).
func Rsi(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Rsi", C.ft_rsi(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cmo wraps ferro_ta_core momentum::cmo.
//
// Chande Momentum Oscillator: `100 * (gains - losses) / (gains + losses)`.
func Cmo(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Cmo", C.ft_cmo(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Stoch wraps ferro_ta_core momentum::stoch.
//
// Compute the Stochastic Oscillator (TA-Lib compatible).
func Stoch(high []float64, low []float64, close []float64, fastkPeriod int, slowkPeriod int, slowkMatype MAType, slowdPeriod int, slowdMatype MAType) (slowk []float64, slowd []float64, err error) {
	n := len(high)
	if err := checkLengths("Stoch", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	slowkBuf := make([]float64, n)
	slowdBuf := make([]float64, n)
	if err := statusError("Stoch", C.ft_stoch(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(fastkPeriod), C.int64_t(slowkPeriod), C.int32_t(slowkMatype), C.int64_t(slowdPeriod), C.int32_t(slowdMatype), (*C.double)(outPtr(slowkBuf)), (*C.double)(outPtr(slowdBuf)))); err != nil {
		return nil, nil, err
	}
	return slowkBuf, slowdBuf, nil
}

// Stochf wraps ferro_ta_core momentum::stochf.
//
// Fast Stochastic. Returns `(fastk, fastd)`.
func Stochf(high []float64, low []float64, close []float64, fastkPeriod int, fastdPeriod int, fastdMatype MAType) (fastk []float64, fastd []float64, err error) {
	n := len(high)
	if err := checkLengths("Stochf", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, nil, err
	}
	fastkBuf := make([]float64, n)
	fastdBuf := make([]float64, n)
	if err := statusError("Stochf", C.ft_stochf(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(fastkPeriod), C.int64_t(fastdPeriod), C.int32_t(fastdMatype), (*C.double)(outPtr(fastkBuf)), (*C.double)(outPtr(fastdBuf)))); err != nil {
		return nil, nil, err
	}
	return fastkBuf, fastdBuf, nil
}

// Stochrsi wraps ferro_ta_core momentum::stochrsi.
//
// Stochastic RSI. Returns `(fastk, fastd)`.
func Stochrsi(close []float64, timeperiod int, fastkPeriod int, fastdPeriod int, fastdMatype MAType) (fastk []float64, fastd []float64, err error) {
	n := len(close)
	fastkBuf := make([]float64, n)
	fastdBuf := make([]float64, n)
	if err := statusError("Stochrsi", C.ft_stochrsi(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.int64_t(fastkPeriod), C.int64_t(fastdPeriod), C.int32_t(fastdMatype), (*C.double)(outPtr(fastkBuf)), (*C.double)(outPtr(fastdBuf)))); err != nil {
		return nil, nil, err
	}
	return fastkBuf, fastdBuf, nil
}

// Ultosc wraps ferro_ta_core momentum::ultosc.
//
// Ultimate Oscillator: weighted average of buying pressure over three periods.
func Ultosc(high []float64, low []float64, close []float64, timeperiod1 int, timeperiod2 int, timeperiod3 int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Ultosc", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Ultosc", C.ft_ultosc(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod1), C.int64_t(timeperiod2), C.int64_t(timeperiod3), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
