// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

import (
	"unsafe"
)

// BlackScholesPrice wraps ferro_ta_core options::black_scholes_price.
//
// Black-Scholes-Merton price with continuous carry/dividend yield.
func BlackScholesPrice(spot float64, strike float64, rate float64, dividendYield float64, timeToExpiry float64, volatility float64, kind OptionKind) (float64, error) {
	var valueOut float64
	if err := statusError("BlackScholesPrice", C.ft_black_scholes_price(C.double(spot), C.double(strike), C.double(rate), C.double(dividendYield), C.double(timeToExpiry), C.double(volatility), C.int32_t(kind), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// Black76Price wraps ferro_ta_core options::black_76_price.
//
// Black-76 price using the forward price as the underlying input.
func Black76Price(forward float64, strike float64, rate float64, timeToExpiry float64, volatility float64, kind OptionKind) (float64, error) {
	var valueOut float64
	if err := statusError("Black76Price", C.ft_black_76_price(C.double(forward), C.double(strike), C.double(rate), C.double(timeToExpiry), C.double(volatility), C.int32_t(kind), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// BlackScholesGreeks wraps ferro_ta_core options::black_scholes_greeks.
//
// Black-Scholes-Merton Greeks.
func BlackScholesGreeks(spot float64, strike float64, rate float64, dividendYield float64, timeToExpiry float64, volatility float64, kind OptionKind) (delta float64, gamma float64, vega float64, theta float64, rho float64, err error) {
	var deltaOut float64
	var gammaOut float64
	var vegaOut float64
	var thetaOut float64
	var rhoOut float64
	if err := statusError("BlackScholesGreeks", C.ft_black_scholes_greeks(C.double(spot), C.double(strike), C.double(rate), C.double(dividendYield), C.double(timeToExpiry), C.double(volatility), C.int32_t(kind), (*C.double)(unsafe.Pointer(&deltaOut)), (*C.double)(unsafe.Pointer(&gammaOut)), (*C.double)(unsafe.Pointer(&vegaOut)), (*C.double)(unsafe.Pointer(&thetaOut)), (*C.double)(unsafe.Pointer(&rhoOut)))); err != nil {
		return 0, 0, 0, 0, 0, err
	}
	return deltaOut, gammaOut, vegaOut, thetaOut, rhoOut, nil
}

// Black76Greeks wraps ferro_ta_core options::black_76_greeks.
//
// Black-76 Greeks with respect to the forward.
func Black76Greeks(forward float64, strike float64, rate float64, timeToExpiry float64, volatility float64, kind OptionKind) (delta float64, gamma float64, vega float64, theta float64, rho float64, err error) {
	var deltaOut float64
	var gammaOut float64
	var vegaOut float64
	var thetaOut float64
	var rhoOut float64
	if err := statusError("Black76Greeks", C.ft_black_76_greeks(C.double(forward), C.double(strike), C.double(rate), C.double(timeToExpiry), C.double(volatility), C.int32_t(kind), (*C.double)(unsafe.Pointer(&deltaOut)), (*C.double)(unsafe.Pointer(&gammaOut)), (*C.double)(unsafe.Pointer(&vegaOut)), (*C.double)(unsafe.Pointer(&thetaOut)), (*C.double)(unsafe.Pointer(&rhoOut)))); err != nil {
		return 0, 0, 0, 0, 0, err
	}
	return deltaOut, gammaOut, vegaOut, thetaOut, rhoOut, nil
}

// BlackScholesExtendedGreeks wraps ferro_ta_core options::black_scholes_extended_greeks.
//
// Extended Greeks under Black-Scholes-Merton (closed-form).
func BlackScholesExtendedGreeks(spot float64, strike float64, rate float64, dividendYield float64, timeToExpiry float64, volatility float64, kind OptionKind) (vanna float64, volga float64, charm float64, speed float64, color float64, err error) {
	var vannaOut float64
	var volgaOut float64
	var charmOut float64
	var speedOut float64
	var colorOut float64
	if err := statusError("BlackScholesExtendedGreeks", C.ft_black_scholes_extended_greeks(C.double(spot), C.double(strike), C.double(rate), C.double(dividendYield), C.double(timeToExpiry), C.double(volatility), C.int32_t(kind), (*C.double)(unsafe.Pointer(&vannaOut)), (*C.double)(unsafe.Pointer(&volgaOut)), (*C.double)(unsafe.Pointer(&charmOut)), (*C.double)(unsafe.Pointer(&speedOut)), (*C.double)(unsafe.Pointer(&colorOut)))); err != nil {
		return 0, 0, 0, 0, 0, err
	}
	return vannaOut, volgaOut, charmOut, speedOut, colorOut, nil
}

// AmericanPriceBaw wraps ferro_ta_core options::american_price_baw.
//
// American option price using the Barone-Adesi-Whaley (1987) quadratic approximation.
func AmericanPriceBaw(spot float64, strike float64, rate float64, carry float64, timeToExpiry float64, volatility float64, kind OptionKind) (float64, error) {
	var valueOut float64
	if err := statusError("AmericanPriceBaw", C.ft_american_price_baw(C.double(spot), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), C.double(volatility), C.int32_t(kind), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// EarlyExercisePremium wraps ferro_ta_core options::early_exercise_premium.
//
// Early exercise premium = american_price - european_bsm_price.
func EarlyExercisePremium(spot float64, strike float64, rate float64, carry float64, timeToExpiry float64, volatility float64, kind OptionKind) (float64, error) {
	var valueOut float64
	if err := statusError("EarlyExercisePremium", C.ft_early_exercise_premium(C.double(spot), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), C.double(volatility), C.int32_t(kind), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// DigitalPrice wraps ferro_ta_core options::digital_price.
//
// Price a digital (binary) option under BSM.
func DigitalPrice(spot float64, strike float64, rate float64, carry float64, timeToExpiry float64, volatility float64, optionKind OptionKind, digitalKind DigitalKind) (float64, error) {
	var valueOut float64
	if err := statusError("DigitalPrice", C.ft_digital_price(C.double(spot), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), C.double(volatility), C.int32_t(optionKind), C.int32_t(digitalKind), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// DigitalGreeks wraps ferro_ta_core options::digital_greeks.
//
// Compute numerical delta, gamma, and vega for a digital option.
func DigitalGreeks(spot float64, strike float64, rate float64, carry float64, timeToExpiry float64, volatility float64, optionKind OptionKind, digitalKind DigitalKind) (delta float64, gamma float64, vega float64, err error) {
	var deltaOut float64
	var gammaOut float64
	var vegaOut float64
	if err := statusError("DigitalGreeks", C.ft_digital_greeks(C.double(spot), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), C.double(volatility), C.int32_t(optionKind), C.int32_t(digitalKind), (*C.double)(unsafe.Pointer(&deltaOut)), (*C.double)(unsafe.Pointer(&gammaOut)), (*C.double)(unsafe.Pointer(&vegaOut)))); err != nil {
		return 0, 0, 0, err
	}
	return deltaOut, gammaOut, vegaOut, nil
}

// PutCallParityDeviation wraps ferro_ta_core options::put_call_parity_deviation.
//
// Put-call parity deviation: `C - P - (S·e^{-q·T} - K·e^{-r·T})`.
func PutCallParityDeviation(callPrice float64, putPrice float64, spot float64, strike float64, rate float64, carry float64, timeToExpiry float64) (float64, error) {
	var valueOut float64
	if err := statusError("PutCallParityDeviation", C.ft_put_call_parity_deviation(C.double(callPrice), C.double(putPrice), C.double(spot), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// ExpectedMove wraps ferro_ta_core options::expected_move.
//
// Expected ±1σ move over `days_to_expiry` calendar days.
func ExpectedMove(spot float64, iv float64, daysToExpiry float64, tradingDaysPerYear float64) (lower float64, upper float64, err error) {
	var lowerOut float64
	var upperOut float64
	if err := statusError("ExpectedMove", C.ft_expected_move(C.double(spot), C.double(iv), C.double(daysToExpiry), C.double(tradingDaysPerYear), (*C.double)(unsafe.Pointer(&lowerOut)), (*C.double)(unsafe.Pointer(&upperOut)))); err != nil {
		return 0, 0, err
	}
	return lowerOut, upperOut, nil
}

// ImpliedVolatility wraps ferro_ta_core options::implied_volatility.
//
// Solve implied volatility with guarded Newton iterations and bisection fallback.
func ImpliedVolatility(targetPrice float64, model PricingModel, underlying float64, strike float64, rate float64, carry float64, timeToExpiry float64, kind OptionKind, initialGuess float64, tolerance float64, maxIterations int) (float64, error) {
	var valueOut float64
	if err := statusError("ImpliedVolatility", C.ft_implied_volatility(C.double(targetPrice), C.int32_t(model), C.double(underlying), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), C.int32_t(kind), C.double(initialGuess), C.double(tolerance), C.int64_t(maxIterations), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// PriceLowerBound wraps ferro_ta_core options::price_lower_bound.
//
// Lower no-arbitrage bound for the option price.
func PriceLowerBound(model PricingModel, underlying float64, strike float64, rate float64, carry float64, timeToExpiry float64, kind OptionKind) (float64, error) {
	var valueOut float64
	if err := statusError("PriceLowerBound", C.ft_price_lower_bound(C.int32_t(model), C.double(underlying), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), C.int32_t(kind), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// PriceUpperBound wraps ferro_ta_core options::price_upper_bound.
//
// Upper no-arbitrage bound for the option price.
func PriceUpperBound(model PricingModel, underlying float64, strike float64, rate float64, carry float64, timeToExpiry float64, kind OptionKind) (float64, error) {
	var valueOut float64
	if err := statusError("PriceUpperBound", C.ft_price_upper_bound(C.int32_t(model), C.double(underlying), C.double(strike), C.double(rate), C.double(carry), C.double(timeToExpiry), C.int32_t(kind), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}
