// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// IvRank wraps ferro_ta_core options::iv_rank.
//
// Rolling IV rank.
func IvRank(ivSeries []float64, window int) ([]float64, error) {
	n := len(ivSeries)
	outBuf := make([]float64, n)
	if err := statusError("IvRank", C.ft_iv_rank(inPtr(ivSeries), C.size_t(n), C.int64_t(window), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// IvPercentile wraps ferro_ta_core options::iv_percentile.
//
// Rolling IV percentile.
func IvPercentile(ivSeries []float64, window int) ([]float64, error) {
	n := len(ivSeries)
	outBuf := make([]float64, n)
	if err := statusError("IvPercentile", C.ft_iv_percentile(inPtr(ivSeries), C.size_t(n), C.int64_t(window), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// IvZscore wraps ferro_ta_core options::iv_zscore.
//
// Rolling IV z-score.
func IvZscore(ivSeries []float64, window int) ([]float64, error) {
	n := len(ivSeries)
	outBuf := make([]float64, n)
	if err := statusError("IvZscore", C.ft_iv_zscore(inPtr(ivSeries), C.size_t(n), C.int64_t(window), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// CloseToCloseVol wraps ferro_ta_core options::close_to_close_vol.
//
// Rolling close-to-close realized volatility.
func CloseToCloseVol(close []float64, window int, tradingDays float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("CloseToCloseVol", C.ft_close_to_close_vol(inPtr(close), C.size_t(n), C.int64_t(window), C.double(tradingDays), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// ParkinsonVol wraps ferro_ta_core options::parkinson_vol.
//
// Rolling Parkinson high-low realized volatility estimator.
func ParkinsonVol(high []float64, low []float64, window int, tradingDays float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("ParkinsonVol", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("ParkinsonVol", C.ft_parkinson_vol(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(window), C.double(tradingDays), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// GarmanKlassVol wraps ferro_ta_core options::garman_klass_vol.
//
// Rolling Garman-Klass OHLC realized volatility estimator.
func GarmanKlassVol(open []float64, high []float64, low []float64, close []float64, window int, tradingDays float64) ([]float64, error) {
	n := len(open)
	if err := checkLengths("GarmanKlassVol", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("GarmanKlassVol", C.ft_garman_klass_vol(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(window), C.double(tradingDays), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RogersSatchellVol wraps ferro_ta_core options::rogers_satchell_vol.
//
// Rolling Rogers-Satchell OHLC realized volatility estimator.
func RogersSatchellVol(open []float64, high []float64, low []float64, close []float64, window int, tradingDays float64) ([]float64, error) {
	n := len(open)
	if err := checkLengths("RogersSatchellVol", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("RogersSatchellVol", C.ft_rogers_satchell_vol(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(window), C.double(tradingDays), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// YangZhangVol wraps ferro_ta_core options::yang_zhang_vol.
//
// Rolling Yang-Zhang OHLC realized volatility estimator.
func YangZhangVol(open []float64, high []float64, low []float64, close []float64, window int, tradingDays float64) ([]float64, error) {
	n := len(open)
	if err := checkLengths("YangZhangVol", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("YangZhangVol", C.ft_yang_zhang_vol(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(window), C.double(tradingDays), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
