// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// Bbands wraps ferro_ta_core overlap::bbands.
//
// Compute Bollinger Bands, returning `(upper, middle, lower)`.
func Bbands(close []float64, timeperiod int, nbdevup float64, nbdevdn float64, matype MAType) (upper []float64, middle []float64, lower []float64, err error) {
	n := len(close)
	upperBuf := make([]float64, n)
	middleBuf := make([]float64, n)
	lowerBuf := make([]float64, n)
	if err := statusError("Bbands", C.ft_bbands(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(nbdevup), C.double(nbdevdn), C.int32_t(matype), (*C.double)(outPtr(upperBuf)), (*C.double)(outPtr(middleBuf)), (*C.double)(outPtr(lowerBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return upperBuf, middleBuf, lowerBuf, nil
}

// Macdfix wraps ferro_ta_core overlap::macdfix.
//
// MACD with fixed 12/26 periods.
func Macdfix(close []float64, signalperiod int) (macd []float64, signal []float64, hist []float64, err error) {
	n := len(close)
	macdBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	histBuf := make([]float64, n)
	if err := statusError("Macdfix", C.ft_macdfix(inPtr(close), C.size_t(n), C.int64_t(signalperiod), (*C.double)(outPtr(macdBuf)), (*C.double)(outPtr(signalBuf)), (*C.double)(outPtr(histBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return macdBuf, signalBuf, histBuf, nil
}

// Macdext wraps ferro_ta_core overlap::macdext.
//
// MACD with configurable MA types for fast/slow/signal.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Macdext(close []float64, fastperiod int, fastmatype MAType, slowperiod int, slowmatype MAType, signalperiod int, signalmatype MAType) (macd []float64, signal []float64, hist []float64, err error) {
	n := len(close)
	macdBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	histBuf := make([]float64, n)
	if err := statusError("Macdext", C.ft_macdext(inPtr(close), C.size_t(n), C.int64_t(fastperiod), C.int32_t(fastmatype), C.int64_t(slowperiod), C.int32_t(slowmatype), C.int64_t(signalperiod), C.int32_t(signalmatype), (*C.double)(outPtr(macdBuf)), (*C.double)(outPtr(signalBuf)), (*C.double)(outPtr(histBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return macdBuf, signalBuf, histBuf, nil
}

// Ma wraps ferro_ta_core overlap::ma.
//
// Generic Moving Average. matype: 0=SMA, 1=EMA, 2=WMA, 3=DEMA, 4=TEMA, 5=TRIMA, 6=KAMA, 7=T3, 8=T3 (TA-Lib's T3 number, an alias of `7`).
func Ma(close []float64, timeperiod int, matype MAType) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Ma", C.ft_ma(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.int32_t(matype), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Mavp wraps ferro_ta_core overlap::mavp.
//
// Moving Average with Variable Period per bar.
// Requires: maxperiod >= minperiod (else ErrInvalidParam).
func Mavp(close []float64, periods []float64, minperiod int, maxperiod int, matype MAType) ([]float64, error) {
	n := len(close)
	if err := checkLengths("Mavp", []string{"close", "periods"}, []int{len(close), len(periods)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Mavp", C.ft_mavp(inPtr(close), inPtr(periods), C.size_t(n), C.int64_t(minperiod), C.int64_t(maxperiod), C.int32_t(matype), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Ema wraps ferro_ta_core overlap::ema.
//
// Compute the Exponential Moving Average (EMA).
func Ema(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Ema", C.ft_ema(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Dema wraps ferro_ta_core overlap::dema.
//
// Double Exponential Moving Average: `2*EMA - EMA(EMA)`.
func Dema(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Dema", C.ft_dema(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Tema wraps ferro_ta_core overlap::tema.
//
// Triple Exponential Moving Average: `3*EMA - 3*EMA(EMA) + EMA(EMA(EMA))`.
func Tema(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Tema", C.ft_tema(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// T3 wraps ferro_ta_core overlap::t3.
//
// Tillson T3: 6 cascaded SMA-seeded EMAs with volume factor.
func T3(close []float64, timeperiod int, vfactor float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("T3", C.ft_t3(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(vfactor), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Kama wraps ferro_ta_core overlap::kama.
//
// Kaufman Adaptive Moving Average (TA-Lib).
func Kama(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Kama", C.ft_kama(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Macd wraps ferro_ta_core overlap::macd.
//
// Compute the Moving Average Convergence/Divergence (MACD).
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Macd(close []float64, fastperiod int, slowperiod int, signalperiod int) (macd []float64, signal []float64, hist []float64, err error) {
	n := len(close)
	macdBuf := make([]float64, n)
	signalBuf := make([]float64, n)
	histBuf := make([]float64, n)
	if err := statusError("Macd", C.ft_macd(inPtr(close), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), C.int64_t(signalperiod), (*C.double)(outPtr(macdBuf)), (*C.double)(outPtr(signalBuf)), (*C.double)(outPtr(histBuf)))); err != nil {
		return nil, nil, nil, err
	}
	return macdBuf, signalBuf, histBuf, nil
}

// Mama wraps ferro_ta_core overlap::mama.
//
// MESA Adaptive Moving Average. Returns `(mama, fama)`.
func Mama(close []float64, fastlimit float64, slowlimit float64) (mama []float64, fama []float64, err error) {
	n := len(close)
	mamaBuf := make([]float64, n)
	famaBuf := make([]float64, n)
	if err := statusError("Mama", C.ft_mama(inPtr(close), C.size_t(n), C.double(fastlimit), C.double(slowlimit), (*C.double)(outPtr(mamaBuf)), (*C.double)(outPtr(famaBuf)))); err != nil {
		return nil, nil, err
	}
	return mamaBuf, famaBuf, nil
}

// Midpoint wraps ferro_ta_core overlap::midpoint.
//
// Midpoint: `(max(close) + min(close)) / 2` over rolling window.
func Midpoint(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Midpoint", C.ft_midpoint(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Midprice wraps ferro_ta_core overlap::midprice.
//
// MidPrice: `(highest_high + lowest_low) / 2` over rolling window.
func Midprice(high []float64, low []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Midprice", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Midprice", C.ft_midprice(inPtr(high), inPtr(low), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Sar wraps ferro_ta_core overlap::sar.
//
// Parabolic SAR.
func Sar(high []float64, low []float64, acceleration float64, maximum float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Sar", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Sar", C.ft_sar(inPtr(high), inPtr(low), C.size_t(n), C.double(acceleration), C.double(maximum), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Sarext wraps ferro_ta_core overlap::sarext.
//
// Parabolic SAR Extended with configurable acceleration factors.
func Sarext(high []float64, low []float64, startvalue float64, offsetonreverse float64, accelerationinitlong float64, accelerationlong float64, accelerationmaxlong float64, accelerationinitshort float64, accelerationshort float64, accelerationmaxshort float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Sarext", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Sarext", C.ft_sarext(inPtr(high), inPtr(low), C.size_t(n), C.double(startvalue), C.double(offsetonreverse), C.double(accelerationinitlong), C.double(accelerationlong), C.double(accelerationmaxlong), C.double(accelerationinitshort), C.double(accelerationshort), C.double(accelerationmaxshort), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Sma wraps ferro_ta_core overlap::sma.
//
// Compute the Simple Moving Average (SMA) over a rolling window.
func Sma(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Sma", C.ft_sma(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Trima wraps ferro_ta_core overlap::trima.
//
// Triangular Moving Average (triangle-weighted).
func Trima(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Trima", C.ft_trima(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Wma wraps ferro_ta_core overlap::wma.
//
// Compute the Weighted Moving Average (WMA).
func Wma(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Wma", C.ft_wma(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
