// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// Cdl2crows wraps ferro_ta_core pattern::cdl2crows.
//
// Two Crows (bearish)
func Cdl2crows(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdl2crows", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdl2crows", C.ft_cdl2crows(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdl3blackcrows wraps ferro_ta_core pattern::cdl3blackcrows.
//
// Three Black Crows (bearish)
func Cdl3blackcrows(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdl3blackcrows", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdl3blackcrows", C.ft_cdl3blackcrows(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdl3inside wraps ferro_ta_core pattern::cdl3inside.
//
// Three Inside Up/Down
func Cdl3inside(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdl3inside", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdl3inside", C.ft_cdl3inside(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdl3linestrike wraps ferro_ta_core pattern::cdl3linestrike.
//
// Three-Line Strike
func Cdl3linestrike(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdl3linestrike", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdl3linestrike", C.ft_cdl3linestrike(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdl3outside wraps ferro_ta_core pattern::cdl3outside.
//
// Three Outside Up/Down
func Cdl3outside(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdl3outside", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdl3outside", C.ft_cdl3outside(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdl3starsinsouth wraps ferro_ta_core pattern::cdl3starsinsouth.
//
// Three Stars In The South (bullish)
func Cdl3starsinsouth(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdl3starsinsouth", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdl3starsinsouth", C.ft_cdl3starsinsouth(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdl3whitesoldiers wraps ferro_ta_core pattern::cdl3whitesoldiers.
//
// Three Advancing White Soldiers (bullish)
func Cdl3whitesoldiers(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdl3whitesoldiers", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdl3whitesoldiers", C.ft_cdl3whitesoldiers(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlabandonedbaby wraps ferro_ta_core pattern::cdlabandonedbaby.
//
// Abandoned Baby
func Cdlabandonedbaby(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlabandonedbaby", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlabandonedbaby", C.ft_cdlabandonedbaby(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdladvanceblock wraps ferro_ta_core pattern::cdladvanceblock.
//
// Advance Block (bearish)
func Cdladvanceblock(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdladvanceblock", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdladvanceblock", C.ft_cdladvanceblock(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlbelthold wraps ferro_ta_core pattern::cdlbelthold.
//
// Belt-hold
func Cdlbelthold(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlbelthold", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlbelthold", C.ft_cdlbelthold(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlbreakaway wraps ferro_ta_core pattern::cdlbreakaway.
//
// Breakaway
func Cdlbreakaway(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlbreakaway", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlbreakaway", C.ft_cdlbreakaway(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlclosingmarubozu wraps ferro_ta_core pattern::cdlclosingmarubozu.
//
// Closing Marubozu
func Cdlclosingmarubozu(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlclosingmarubozu", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlclosingmarubozu", C.ft_cdlclosingmarubozu(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlconcealbabyswall wraps ferro_ta_core pattern::cdlconcealbabyswall.
//
// Concealing Baby Swallow (bullish)
func Cdlconcealbabyswall(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlconcealbabyswall", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlconcealbabyswall", C.ft_cdlconcealbabyswall(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlcounterattack wraps ferro_ta_core pattern::cdlcounterattack.
//
// Counterattack
func Cdlcounterattack(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlcounterattack", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlcounterattack", C.ft_cdlcounterattack(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdldarkcloudcover wraps ferro_ta_core pattern::cdldarkcloudcover.
//
// Dark Cloud Cover (bearish)
func Cdldarkcloudcover(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdldarkcloudcover", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdldarkcloudcover", C.ft_cdldarkcloudcover(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdldoji wraps ferro_ta_core pattern::cdldoji.
//
// Doji
func Cdldoji(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdldoji", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdldoji", C.ft_cdldoji(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdldojistar wraps ferro_ta_core pattern::cdldojistar.
//
// Doji Star
func Cdldojistar(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdldojistar", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdldojistar", C.ft_cdldojistar(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdldragonflydoji wraps ferro_ta_core pattern::cdldragonflydoji.
//
// Dragonfly Doji (bullish)
func Cdldragonflydoji(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdldragonflydoji", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdldragonflydoji", C.ft_cdldragonflydoji(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlengulfing wraps ferro_ta_core pattern::cdlengulfing.
//
// Engulfing
func Cdlengulfing(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlengulfing", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlengulfing", C.ft_cdlengulfing(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdleveningdojistar wraps ferro_ta_core pattern::cdleveningdojistar.
//
// Evening Doji Star (bearish)
func Cdleveningdojistar(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdleveningdojistar", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdleveningdojistar", C.ft_cdleveningdojistar(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdleveningstar wraps ferro_ta_core pattern::cdleveningstar.
//
// Evening Star (bearish)
func Cdleveningstar(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdleveningstar", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdleveningstar", C.ft_cdleveningstar(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlgapsidesidewhite wraps ferro_ta_core pattern::cdlgapsidesidewhite.
//
// Up/Down-gap side-by-side white lines
func Cdlgapsidesidewhite(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlgapsidesidewhite", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlgapsidesidewhite", C.ft_cdlgapsidesidewhite(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlgravestonedoji wraps ferro_ta_core pattern::cdlgravestonedoji.
//
// Gravestone Doji (bearish)
func Cdlgravestonedoji(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlgravestonedoji", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlgravestonedoji", C.ft_cdlgravestonedoji(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlhammer wraps ferro_ta_core pattern::cdlhammer.
//
// Hammer (bullish)
func Cdlhammer(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlhammer", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlhammer", C.ft_cdlhammer(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlhangingman wraps ferro_ta_core pattern::cdlhangingman.
//
// Hanging Man (bearish)
func Cdlhangingman(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlhangingman", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlhangingman", C.ft_cdlhangingman(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlharami wraps ferro_ta_core pattern::cdlharami.
//
// Harami
func Cdlharami(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlharami", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlharami", C.ft_cdlharami(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlharamicross wraps ferro_ta_core pattern::cdlharamicross.
//
// Harami Cross
func Cdlharamicross(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlharamicross", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlharamicross", C.ft_cdlharamicross(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlhighwave wraps ferro_ta_core pattern::cdlhighwave.
//
// High-Wave Candle
func Cdlhighwave(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlhighwave", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlhighwave", C.ft_cdlhighwave(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlhikkake wraps ferro_ta_core pattern::cdlhikkake.
//
// Hikkake Pattern
func Cdlhikkake(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlhikkake", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlhikkake", C.ft_cdlhikkake(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlhikkakemod wraps ferro_ta_core pattern::cdlhikkakemod.
//
// Modified Hikkake Pattern
func Cdlhikkakemod(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlhikkakemod", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlhikkakemod", C.ft_cdlhikkakemod(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlhomingpigeon wraps ferro_ta_core pattern::cdlhomingpigeon.
//
// Homing Pigeon (bullish)
func Cdlhomingpigeon(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlhomingpigeon", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlhomingpigeon", C.ft_cdlhomingpigeon(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlidentical3crows wraps ferro_ta_core pattern::cdlidentical3crows.
//
// Identical Three Crows (bearish)
func Cdlidentical3crows(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlidentical3crows", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlidentical3crows", C.ft_cdlidentical3crows(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlinneck wraps ferro_ta_core pattern::cdlinneck.
//
// In-Neck Pattern (bearish)
func Cdlinneck(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlinneck", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlinneck", C.ft_cdlinneck(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlinvertedhammer wraps ferro_ta_core pattern::cdlinvertedhammer.
//
// Inverted Hammer (bullish)
func Cdlinvertedhammer(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlinvertedhammer", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlinvertedhammer", C.ft_cdlinvertedhammer(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlkicking wraps ferro_ta_core pattern::cdlkicking.
//
// Kicking
func Cdlkicking(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlkicking", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlkicking", C.ft_cdlkicking(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlkickingbylength wraps ferro_ta_core pattern::cdlkickingbylength.
//
// Kicking — bull/bear determined by longer of the two marubozu
func Cdlkickingbylength(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlkickingbylength", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlkickingbylength", C.ft_cdlkickingbylength(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlladderbottom wraps ferro_ta_core pattern::cdlladderbottom.
//
// Ladder Bottom (bullish)
func Cdlladderbottom(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlladderbottom", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlladderbottom", C.ft_cdlladderbottom(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdllongleggeddoji wraps ferro_ta_core pattern::cdllongleggeddoji.
//
// Long Legged Doji
func Cdllongleggeddoji(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdllongleggeddoji", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdllongleggeddoji", C.ft_cdllongleggeddoji(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdllongline wraps ferro_ta_core pattern::cdllongline.
//
// Long Line Candle
func Cdllongline(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdllongline", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdllongline", C.ft_cdllongline(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlmarubozu wraps ferro_ta_core pattern::cdlmarubozu.
//
// Marubozu
func Cdlmarubozu(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlmarubozu", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlmarubozu", C.ft_cdlmarubozu(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlmatchinglow wraps ferro_ta_core pattern::cdlmatchinglow.
//
// Matching Low (bullish)
func Cdlmatchinglow(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlmatchinglow", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlmatchinglow", C.ft_cdlmatchinglow(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlmathold wraps ferro_ta_core pattern::cdlmathold.
//
// Mat Hold (bullish)
func Cdlmathold(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlmathold", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlmathold", C.ft_cdlmathold(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlmorningdojistar wraps ferro_ta_core pattern::cdlmorningdojistar.
//
// Morning Doji Star (bullish)
func Cdlmorningdojistar(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlmorningdojistar", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlmorningdojistar", C.ft_cdlmorningdojistar(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlmorningstar wraps ferro_ta_core pattern::cdlmorningstar.
//
// Morning Star (bullish)
func Cdlmorningstar(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlmorningstar", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlmorningstar", C.ft_cdlmorningstar(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlonneck wraps ferro_ta_core pattern::cdlonneck.
//
// On-Neck Pattern (bearish)
func Cdlonneck(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlonneck", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlonneck", C.ft_cdlonneck(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlpiercing wraps ferro_ta_core pattern::cdlpiercing.
//
// Piercing Pattern (bullish)
func Cdlpiercing(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlpiercing", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlpiercing", C.ft_cdlpiercing(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlrickshawman wraps ferro_ta_core pattern::cdlrickshawman.
//
// Rickshaw Man
func Cdlrickshawman(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlrickshawman", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlrickshawman", C.ft_cdlrickshawman(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlrisefall3methods wraps ferro_ta_core pattern::cdlrisefall3methods.
//
// Rising/Falling Three Methods
func Cdlrisefall3methods(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlrisefall3methods", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlrisefall3methods", C.ft_cdlrisefall3methods(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlseparatinglines wraps ferro_ta_core pattern::cdlseparatinglines.
//
// Separating Lines
func Cdlseparatinglines(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlseparatinglines", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlseparatinglines", C.ft_cdlseparatinglines(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlshootingstar wraps ferro_ta_core pattern::cdlshootingstar.
//
// Shooting Star (bearish)
func Cdlshootingstar(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlshootingstar", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlshootingstar", C.ft_cdlshootingstar(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlshortline wraps ferro_ta_core pattern::cdlshortline.
//
// Short Line Candle
func Cdlshortline(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlshortline", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlshortline", C.ft_cdlshortline(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlspinningtop wraps ferro_ta_core pattern::cdlspinningtop.
//
// Spinning Top
func Cdlspinningtop(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlspinningtop", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlspinningtop", C.ft_cdlspinningtop(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlstalledpattern wraps ferro_ta_core pattern::cdlstalledpattern.
//
// Stalled Pattern (bearish)
func Cdlstalledpattern(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlstalledpattern", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlstalledpattern", C.ft_cdlstalledpattern(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlsticksandwich wraps ferro_ta_core pattern::cdlsticksandwich.
//
// Stick Sandwich (bullish)
func Cdlsticksandwich(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlsticksandwich", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlsticksandwich", C.ft_cdlsticksandwich(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdltakuri wraps ferro_ta_core pattern::cdltakuri.
//
// Takuri (Dragonfly Doji with very long lower shadow)
func Cdltakuri(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdltakuri", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdltakuri", C.ft_cdltakuri(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdltasukigap wraps ferro_ta_core pattern::cdltasukigap.
//
// Tasuki Gap
func Cdltasukigap(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdltasukigap", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdltasukigap", C.ft_cdltasukigap(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlthrusting wraps ferro_ta_core pattern::cdlthrusting.
//
// Thrusting Pattern (bearish)
func Cdlthrusting(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlthrusting", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlthrusting", C.ft_cdlthrusting(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdltristar wraps ferro_ta_core pattern::cdltristar.
//
// Tristar Pattern
func Cdltristar(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdltristar", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdltristar", C.ft_cdltristar(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlunique3river wraps ferro_ta_core pattern::cdlunique3river.
//
// Unique 3 River (bullish)
func Cdlunique3river(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlunique3river", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlunique3river", C.ft_cdlunique3river(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlupsidegap2crows wraps ferro_ta_core pattern::cdlupsidegap2crows.
//
// Upside Gap Two Crows (bearish)
func Cdlupsidegap2crows(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlupsidegap2crows", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlupsidegap2crows", C.ft_cdlupsidegap2crows(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Cdlxsidegap3methods wraps ferro_ta_core pattern::cdlxsidegap3methods.
//
// Upside/Downside Gap Three Methods
func Cdlxsidegap3methods(open []float64, high []float64, low []float64, close []float64) ([]int32, error) {
	n := len(open)
	if err := checkLengths("Cdlxsidegap3methods", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int32, n)
	if err := statusError("Cdlxsidegap3methods", C.ft_cdlxsidegap3methods(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.int32_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
