// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// RollingBeta wraps ferro_ta_core portfolio::rolling_beta.
//
// Compute rolling beta of `asset` vs `benchmark` over a sliding `window`.
func RollingBeta(asset []float64, benchmark []float64, window int) ([]float64, error) {
	n := len(asset)
	if err := checkLengths("RollingBeta", []string{"asset", "benchmark"}, []int{len(asset), len(benchmark)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("RollingBeta", C.ft_rolling_beta(inPtr(asset), inPtr(benchmark), C.size_t(n), C.int64_t(window), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RelativeStrength wraps ferro_ta_core portfolio::relative_strength.
//
// Compute relative strength of an asset vs a benchmark.
func RelativeStrength(assetReturns []float64, benchmarkReturns []float64) ([]float64, error) {
	n := len(assetReturns)
	if err := checkLengths("RelativeStrength", []string{"asset_returns", "benchmark_returns"}, []int{len(assetReturns), len(benchmarkReturns)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("RelativeStrength", C.ft_relative_strength(inPtr(assetReturns), inPtr(benchmarkReturns), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Spread wraps ferro_ta_core portfolio::spread.
//
// Compute the spread between two series: a - hedge * b.
func Spread(a []float64, b []float64, hedge float64) ([]float64, error) {
	n := len(a)
	if err := checkLengths("Spread", []string{"a", "b"}, []int{len(a), len(b)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Spread", C.ft_spread(inPtr(a), inPtr(b), C.size_t(n), C.double(hedge), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Ratio wraps ferro_ta_core portfolio::ratio.
//
// Compute the ratio between two series: a / b.
func Ratio(a []float64, b []float64) ([]float64, error) {
	n := len(a)
	if err := checkLengths("Ratio", []string{"a", "b"}, []int{len(a), len(b)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Ratio", C.ft_ratio(inPtr(a), inPtr(b), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// ZscoreSeries wraps ferro_ta_core portfolio::zscore_series.
//
// Compute the rolling Z-score of a 1-D series.
func ZscoreSeries(x []float64, window int) ([]float64, error) {
	n := len(x)
	outBuf := make([]float64, n)
	if err := statusError("ZscoreSeries", C.ft_zscore_series(inPtr(x), C.size_t(n), C.int64_t(window), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
