// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// Avgprice wraps ferro_ta_core price_transform::avgprice.
//
// Average Price: (open + high + low + close) / 4.
func Avgprice(open []float64, high []float64, low []float64, close []float64) ([]float64, error) {
	n := len(open)
	if err := checkLengths("Avgprice", []string{"open", "high", "low", "close"}, []int{len(open), len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Avgprice", C.ft_avgprice(inPtr(open), inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Medprice wraps ferro_ta_core price_transform::medprice.
//
// Median Price: (high + low) / 2.
func Medprice(high []float64, low []float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Medprice", []string{"high", "low"}, []int{len(high), len(low)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Medprice", C.ft_medprice(inPtr(high), inPtr(low), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Typprice wraps ferro_ta_core price_transform::typprice.
//
// Typical Price: (high + low + close) / 3.
func Typprice(high []float64, low []float64, close []float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Typprice", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Typprice", C.ft_typprice(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Wclprice wraps ferro_ta_core price_transform::wclprice.
//
// Weighted Close Price: (high + low + close * 2) / 4.
func Wclprice(high []float64, low []float64, close []float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Wclprice", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Wclprice", C.ft_wclprice(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
