// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// RegimeAdx wraps ferro_ta_core regime::regime_adx.
//
// Label each bar as trend (1) or range (0) based on ADX level.
func RegimeAdx(adx []float64, threshold float64) ([]int8, error) {
	n := len(adx)
	outBuf := make([]int8, n)
	if err := statusError("RegimeAdx", C.ft_regime_adx(inPtr(adx), C.size_t(n), C.double(threshold), (*C.int8_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RegimeCombined wraps ferro_ta_core regime::regime_combined.
//
// Label each bar as trend (1) or range (0) using ADX + ATR-ratio rule.
func RegimeCombined(adx []float64, atr []float64, close []float64, adxThreshold float64, atrPctThreshold float64) ([]int8, error) {
	n := len(adx)
	if err := checkLengths("RegimeCombined", []string{"adx", "atr", "close"}, []int{len(adx), len(atr), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]int8, n)
	if err := statusError("RegimeCombined", C.ft_regime_combined(inPtr(adx), inPtr(atr), inPtr(close), C.size_t(n), C.double(adxThreshold), C.double(atrPctThreshold), (*C.int8_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// DetectBreaksCusum wraps ferro_ta_core regime::detect_breaks_cusum.
//
// Detect structural breaks using a CUSUM (cumulative sum) approach.
func DetectBreaksCusum(series []float64, window int, threshold float64, slack float64) ([]int8, error) {
	n := len(series)
	outBuf := make([]int8, n)
	if err := statusError("DetectBreaksCusum", C.ft_detect_breaks_cusum(inPtr(series), C.size_t(n), C.int64_t(window), C.double(threshold), C.double(slack), (*C.int8_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RollingVarianceBreak wraps ferro_ta_core regime::rolling_variance_break.
//
// Detect volatility regime breaks using rolling variance ratio.
// Requires: long_window > short_window (else ErrInvalidParam).
func RollingVarianceBreak(series []float64, shortWindow int, longWindow int, threshold float64) ([]int8, error) {
	n := len(series)
	outBuf := make([]int8, n)
	if err := statusError("RollingVarianceBreak", C.ft_rolling_variance_break(inPtr(series), C.size_t(n), C.int64_t(shortWindow), C.int64_t(longWindow), C.double(threshold), (*C.int8_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
