// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

import (
	"unsafe"
)

// KellyFraction wraps ferro_ta_core sizing::kelly_fraction.
//
// Compute the Kelly fraction: f = win_rate - (1 - win_rate) * (|avg_loss| / avg_win), clamped to [0, 1].
func KellyFraction(winRate float64, avgWin float64, avgLoss float64) (float64, error) {
	var valueOut float64
	if err := statusError("KellyFraction", C.ft_kelly_fraction(C.double(winRate), C.double(avgWin), C.double(avgLoss), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}

// HalfKellyFraction wraps ferro_ta_core sizing::half_kelly_fraction.
//
// Half-Kelly fraction (conservative position sizing).
func HalfKellyFraction(winRate float64, avgWin float64, avgLoss float64) (float64, error) {
	var valueOut float64
	if err := statusError("HalfKellyFraction", C.ft_half_kelly_fraction(C.double(winRate), C.double(avgWin), C.double(avgLoss), (*C.double)(unsafe.Pointer(&valueOut)))); err != nil {
		return 0, err
	}
	return valueOut, nil
}
