// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// Stddev wraps ferro_ta_core statistic::stddev.
//
// Compute the rolling population standard deviation, scaled by `nbdev`.
func Stddev(real []float64, timeperiod int, nbdev float64) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("Stddev", C.ft_stddev(inPtr(real), C.size_t(n), C.int64_t(timeperiod), C.double(nbdev), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Var wraps ferro_ta_core statistic::var.
//
// Rolling population variance, scaled by `nbdev**2`.
func Var(real []float64, timeperiod int, nbdev float64) ([]float64, error) {
	n := len(real)
	outBuf := make([]float64, n)
	if err := statusError("Var", C.ft_var(inPtr(real), C.size_t(n), C.int64_t(timeperiod), C.double(nbdev), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Linearreg wraps ferro_ta_core statistic::linearreg.
//
// Linear regression fitted value at the last point of the window.
func Linearreg(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Linearreg", C.ft_linearreg(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// LinearregSlope wraps ferro_ta_core statistic::linearreg_slope.
//
// Slope of the rolling linear regression line.
func LinearregSlope(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("LinearregSlope", C.ft_linearreg_slope(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// LinearregIntercept wraps ferro_ta_core statistic::linearreg_intercept.
//
// Intercept of the rolling linear regression line.
func LinearregIntercept(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("LinearregIntercept", C.ft_linearreg_intercept(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// LinearregAngle wraps ferro_ta_core statistic::linearreg_angle.
//
// Angle of the regression line in degrees.
func LinearregAngle(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("LinearregAngle", C.ft_linearreg_angle(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Tsf wraps ferro_ta_core statistic::tsf.
//
// Time Series Forecast: linear regression extrapolated one period ahead.
func Tsf(close []float64, timeperiod int) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("Tsf", C.ft_tsf(inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Beta wraps ferro_ta_core statistic::beta.
//
// Rolling beta: regression of real1 daily returns on real0 daily returns.
func Beta(real0 []float64, real1 []float64, timeperiod int) ([]float64, error) {
	n := len(real0)
	if err := checkLengths("Beta", []string{"real0", "real1"}, []int{len(real0), len(real1)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Beta", C.ft_beta(inPtr(real0), inPtr(real1), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Correl wraps ferro_ta_core statistic::correl.
//
// Rolling Pearson correlation coefficient between two series.
func Correl(real0 []float64, real1 []float64, timeperiod int) ([]float64, error) {
	n := len(real0)
	if err := checkLengths("Correl", []string{"real0", "real1"}, []int{len(real0), len(real1)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Correl", C.ft_correl(inPtr(real0), inPtr(real1), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
