// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

import (
	"runtime"
	"sync"
	"unsafe"
)

// StreamSma is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming simple moving average.
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamSma struct {
	mu sync.Mutex
	h  *C.FtStreamSma
}

// NewStreamSma creates a StreamSma.
func NewStreamSma(period int) (*StreamSma, error) {
	var h *C.FtStreamSma
	if err := statusError("NewStreamSma", C.ft_stream_sma_new(C.int64_t(period), &h)); err != nil {
		return nil, err
	}
	s := &StreamSma{h: h}
	runtime.SetFinalizer(s, (*StreamSma).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamSma) Update(value float64) (float64, error) {
	var out float64
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, closedError("StreamSma.Update")
	}
	if err := statusError("StreamSma.Update", C.ft_stream_sma_update(s.h, C.double(value), (*C.double)(unsafe.Pointer(&out)))); err != nil {
		return 0, err
	}
	return out, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamSma) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamSma.Reset")
	}
	return statusError("StreamSma.Reset", C.ft_stream_sma_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamSma) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_sma_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}

// StreamEma is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming exponential moving average (SMA-seeded, TA-Lib compatible).
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamEma struct {
	mu sync.Mutex
	h  *C.FtStreamEma
}

// NewStreamEma creates a StreamEma.
func NewStreamEma(period int) (*StreamEma, error) {
	var h *C.FtStreamEma
	if err := statusError("NewStreamEma", C.ft_stream_ema_new(C.int64_t(period), &h)); err != nil {
		return nil, err
	}
	s := &StreamEma{h: h}
	runtime.SetFinalizer(s, (*StreamEma).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamEma) Update(value float64) (float64, error) {
	var out float64
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, closedError("StreamEma.Update")
	}
	if err := statusError("StreamEma.Update", C.ft_stream_ema_update(s.h, C.double(value), (*C.double)(unsafe.Pointer(&out)))); err != nil {
		return 0, err
	}
	return out, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamEma) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamEma.Reset")
	}
	return statusError("StreamEma.Reset", C.ft_stream_ema_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamEma) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_ema_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}

// StreamRsi is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming RSI (Wilder smoothing).
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamRsi struct {
	mu sync.Mutex
	h  *C.FtStreamRsi
}

// NewStreamRsi creates a StreamRsi.
func NewStreamRsi(period int) (*StreamRsi, error) {
	var h *C.FtStreamRsi
	if err := statusError("NewStreamRsi", C.ft_stream_rsi_new(C.int64_t(period), &h)); err != nil {
		return nil, err
	}
	s := &StreamRsi{h: h}
	runtime.SetFinalizer(s, (*StreamRsi).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamRsi) Update(value float64) (float64, error) {
	var out float64
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, closedError("StreamRsi.Update")
	}
	if err := statusError("StreamRsi.Update", C.ft_stream_rsi_update(s.h, C.double(value), (*C.double)(unsafe.Pointer(&out)))); err != nil {
		return 0, err
	}
	return out, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamRsi) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamRsi.Reset")
	}
	return statusError("StreamRsi.Reset", C.ft_stream_rsi_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamRsi) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_rsi_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}

// StreamAtr is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming average true range.
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamAtr struct {
	mu sync.Mutex
	h  *C.FtStreamAtr
}

// NewStreamAtr creates a StreamAtr.
func NewStreamAtr(period int) (*StreamAtr, error) {
	var h *C.FtStreamAtr
	if err := statusError("NewStreamAtr", C.ft_stream_atr_new(C.int64_t(period), &h)); err != nil {
		return nil, err
	}
	s := &StreamAtr{h: h}
	runtime.SetFinalizer(s, (*StreamAtr).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamAtr) Update(high float64, low float64, close float64) (float64, error) {
	var out float64
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, closedError("StreamAtr.Update")
	}
	if err := statusError("StreamAtr.Update", C.ft_stream_atr_update(s.h, C.double(high), C.double(low), C.double(close), (*C.double)(unsafe.Pointer(&out)))); err != nil {
		return 0, err
	}
	return out, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamAtr) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamAtr.Reset")
	}
	return statusError("StreamAtr.Reset", C.ft_stream_atr_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamAtr) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_atr_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}

// StreamBbands is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming Bollinger Bands.
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamBbands struct {
	mu sync.Mutex
	h  *C.FtStreamBbands
}

// NewStreamBbands creates a StreamBbands.
func NewStreamBbands(period int, nbdevup float64, nbdevdn float64) (*StreamBbands, error) {
	var h *C.FtStreamBbands
	if err := statusError("NewStreamBbands", C.ft_stream_bbands_new(C.int64_t(period), C.double(nbdevup), C.double(nbdevdn), &h)); err != nil {
		return nil, err
	}
	s := &StreamBbands{h: h}
	runtime.SetFinalizer(s, (*StreamBbands).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamBbands) Update(value float64) (upper float64, middle float64, lower float64, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, 0, 0, closedError("StreamBbands.Update")
	}
	if err := statusError("StreamBbands.Update", C.ft_stream_bbands_update(s.h, C.double(value), (*C.double)(unsafe.Pointer(&upper)), (*C.double)(unsafe.Pointer(&middle)), (*C.double)(unsafe.Pointer(&lower)))); err != nil {
		return 0, 0, 0, err
	}
	return upper, middle, lower, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamBbands) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamBbands.Reset")
	}
	return statusError("StreamBbands.Reset", C.ft_stream_bbands_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamBbands) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_bbands_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}

// StreamMacd is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming MACD. Requires `fastperiod < slowperiod`.
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamMacd struct {
	mu sync.Mutex
	h  *C.FtStreamMacd
}

// NewStreamMacd creates a StreamMacd.
func NewStreamMacd(fastperiod int, slowperiod int, signalperiod int) (*StreamMacd, error) {
	var h *C.FtStreamMacd
	if err := statusError("NewStreamMacd", C.ft_stream_macd_new(C.int64_t(fastperiod), C.int64_t(slowperiod), C.int64_t(signalperiod), &h)); err != nil {
		return nil, err
	}
	s := &StreamMacd{h: h}
	runtime.SetFinalizer(s, (*StreamMacd).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamMacd) Update(value float64) (macd float64, signal float64, hist float64, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, 0, 0, closedError("StreamMacd.Update")
	}
	if err := statusError("StreamMacd.Update", C.ft_stream_macd_update(s.h, C.double(value), (*C.double)(unsafe.Pointer(&macd)), (*C.double)(unsafe.Pointer(&signal)), (*C.double)(unsafe.Pointer(&hist)))); err != nil {
		return 0, 0, 0, err
	}
	return macd, signal, hist, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamMacd) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamMacd.Reset")
	}
	return statusError("StreamMacd.Reset", C.ft_stream_macd_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamMacd) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_macd_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}

// StreamStoch is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming slow stochastic.
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamStoch struct {
	mu sync.Mutex
	h  *C.FtStreamStoch
}

// NewStreamStoch creates a StreamStoch.
func NewStreamStoch(fastkPeriod int, slowkPeriod int, slowdPeriod int) (*StreamStoch, error) {
	var h *C.FtStreamStoch
	if err := statusError("NewStreamStoch", C.ft_stream_stoch_new(C.int64_t(fastkPeriod), C.int64_t(slowkPeriod), C.int64_t(slowdPeriod), &h)); err != nil {
		return nil, err
	}
	s := &StreamStoch{h: h}
	runtime.SetFinalizer(s, (*StreamStoch).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamStoch) Update(high float64, low float64, close float64) (slowk float64, slowd float64, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, 0, closedError("StreamStoch.Update")
	}
	if err := statusError("StreamStoch.Update", C.ft_stream_stoch_update(s.h, C.double(high), C.double(low), C.double(close), (*C.double)(unsafe.Pointer(&slowk)), (*C.double)(unsafe.Pointer(&slowd)))); err != nil {
		return 0, 0, err
	}
	return slowk, slowd, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamStoch) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamStoch.Reset")
	}
	return statusError("StreamStoch.Reset", C.ft_stream_stoch_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamStoch) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_stoch_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}

// StreamVwap is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming cumulative VWAP (session-anchored; `reset` starts a new session).
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamVwap struct {
	mu sync.Mutex
	h  *C.FtStreamVwap
}

// NewStreamVwap creates a StreamVwap.
func NewStreamVwap() (*StreamVwap, error) {
	var h *C.FtStreamVwap
	if err := statusError("NewStreamVwap", C.ft_stream_vwap_new(&h)); err != nil {
		return nil, err
	}
	s := &StreamVwap{h: h}
	runtime.SetFinalizer(s, (*StreamVwap).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamVwap) Update(high float64, low float64, close float64, volume float64) (float64, error) {
	var out float64
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, closedError("StreamVwap.Update")
	}
	if err := statusError("StreamVwap.Update", C.ft_stream_vwap_update(s.h, C.double(high), C.double(low), C.double(close), C.double(volume), (*C.double)(unsafe.Pointer(&out)))); err != nil {
		return 0, err
	}
	return out, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamVwap) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamVwap.Reset")
	}
	return statusError("StreamVwap.Reset", C.ft_stream_vwap_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamVwap) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_vwap_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}

// StreamSupertrend is a stateful, bar-by-bar indicator backed by a Rust handle.
//
// Streaming Supertrend. `out_direction` is 1 (up) / -1 (down), 0 in warm-up.
//
// Methods are safe for concurrent use. Call Close when done; a finalizer
// releases the handle if Close is forgotten.
type StreamSupertrend struct {
	mu sync.Mutex
	h  *C.FtStreamSupertrend
}

// NewStreamSupertrend creates a StreamSupertrend.
func NewStreamSupertrend(period int, multiplier float64) (*StreamSupertrend, error) {
	var h *C.FtStreamSupertrend
	if err := statusError("NewStreamSupertrend", C.ft_stream_supertrend_new(C.int64_t(period), C.double(multiplier), &h)); err != nil {
		return nil, err
	}
	s := &StreamSupertrend{h: h}
	runtime.SetFinalizer(s, (*StreamSupertrend).Close)
	return s, nil
}

// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).
func (s *StreamSupertrend) Update(high float64, low float64, close float64) (line float64, direction int8, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return 0, 0, closedError("StreamSupertrend.Update")
	}
	if err := statusError("StreamSupertrend.Update", C.ft_stream_supertrend_update(s.h, C.double(high), C.double(low), C.double(close), (*C.double)(unsafe.Pointer(&line)), (*C.int8_t)(unsafe.Pointer(&direction)))); err != nil {
		return 0, 0, err
	}
	return line, direction, nil
}

// Reset clears all state; subsequent bars warm up again.
func (s *StreamSupertrend) Reset() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h == nil {
		return closedError("StreamSupertrend.Reset")
	}
	return statusError("StreamSupertrend.Reset", C.ft_stream_supertrend_reset(s.h))
}

// Close releases the underlying handle. It is safe to call more than once.
func (s *StreamSupertrend) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.h != nil {
		C.ft_stream_supertrend_free(s.h)
		s.h = nil
		runtime.SetFinalizer(s, nil)
	}
	return nil
}
