// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// RankValues wraps ferro_ta_core utilities::rank_values.
//
// Compute fractional rank of each element (1-based, ascending). Ties receive the average of their rank positions.
func RankValues(x []float64) ([]float64, error) {
	n := len(x)
	outBuf := make([]float64, n)
	if err := statusError("RankValues", C.ft_rank_values(inPtr(x), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// CheckCross wraps ferro_ta_core utilities::check_cross.
//
// Detect cross-over / cross-under events between two series.
func CheckCross(fast []float64, slow []float64) ([]int8, error) {
	n := len(fast)
	if err := checkLengths("CheckCross", []string{"fast", "slow"}, []int{len(fast), len(slow)}); err != nil {
		return nil, err
	}
	outBuf := make([]int8, n)
	if err := statusError("CheckCross", C.ft_check_cross(inPtr(fast), inPtr(slow), C.size_t(n), (*C.int8_t)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// FundingCumulativePnl wraps ferro_ta_core utilities::funding_cumulative_pnl.
//
// Compute the cumulative PnL from funding rate payments.
func FundingCumulativePnl(positionSize []float64, fundingRate []float64) ([]float64, error) {
	n := len(positionSize)
	if err := checkLengths("FundingCumulativePnl", []string{"position_size", "funding_rate"}, []int{len(positionSize), len(fundingRate)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("FundingCumulativePnl", C.ft_funding_cumulative_pnl(inPtr(positionSize), inPtr(fundingRate), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// ForwardFillNan wraps ferro_ta_core utilities::forward_fill_nan.
//
// Forward-fill NaN values in a 1-D array. Leading NaN values are preserved until the first non-NaN value appears.
func ForwardFillNan(values []float64) ([]float64, error) {
	n := len(values)
	outBuf := make([]float64, n)
	if err := statusError("ForwardFillNan", C.ft_forward_fill_nan(inPtr(values), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// RsiThresholdSignals wraps ferro_ta_core utilities::rsi_threshold_signals.
//
// RSI threshold strategy: +1 when RSI <= oversold, -1 when RSI >= overbought, 0 otherwise.
func RsiThresholdSignals(close []float64, timeperiod int, oversold float64, overbought float64) ([]float64, error) {
	n := len(close)
	outBuf := make([]float64, n)
	if err := statusError("RsiThresholdSignals", C.ft_rsi_threshold_signals(inPtr(close), C.size_t(n), C.int64_t(timeperiod), C.double(oversold), C.double(overbought), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
