// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// Atr wraps ferro_ta_core volatility::atr.
//
// Compute the Average True Range (ATR), Wilder smoothed (TA-Lib compatible).
func Atr(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Atr", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Atr", C.ft_atr(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Trange wraps ferro_ta_core volatility::trange.
//
// Compute the True Range for each bar.
func Trange(high []float64, low []float64, close []float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Trange", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Trange", C.ft_trange(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Natr wraps ferro_ta_core volatility::natr.
//
// Normalized Average True Range: `ATR / close * 100`.
func Natr(high []float64, low []float64, close []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Natr", []string{"high", "low", "close"}, []int{len(high), len(low), len(close)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Natr", C.ft_natr(inPtr(high), inPtr(low), inPtr(close), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
