// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.

package ferrota

/*
#include "ferro_ta.h"
*/
import "C"

// Obv wraps ferro_ta_core volume::obv.
//
// Compute On-Balance Volume (OBV).
func Obv(close []float64, volume []float64) ([]float64, error) {
	n := len(close)
	if err := checkLengths("Obv", []string{"close", "volume"}, []int{len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Obv", C.ft_obv(inPtr(close), inPtr(volume), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Mfi wraps ferro_ta_core volume::mfi.
//
// Compute the Money Flow Index (MFI).
func Mfi(high []float64, low []float64, close []float64, volume []float64, timeperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Mfi", []string{"high", "low", "close", "volume"}, []int{len(high), len(low), len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Mfi", C.ft_mfi(inPtr(high), inPtr(low), inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(timeperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Ad wraps ferro_ta_core volume::ad.
//
// Chaikin Accumulation/Distribution Line.
func Ad(high []float64, low []float64, close []float64, volume []float64) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Ad", []string{"high", "low", "close", "volume"}, []int{len(high), len(low), len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Ad", C.ft_ad(inPtr(high), inPtr(low), inPtr(close), inPtr(volume), C.size_t(n), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}

// Adosc wraps ferro_ta_core volume::adosc.
//
// Chaikin A/D Oscillator: fast EMA of AD minus slow EMA of AD.
// Requires: fastperiod < slowperiod (else ErrInvalidParam).
func Adosc(high []float64, low []float64, close []float64, volume []float64, fastperiod int, slowperiod int) ([]float64, error) {
	n := len(high)
	if err := checkLengths("Adosc", []string{"high", "low", "close", "volume"}, []int{len(high), len(low), len(close), len(volume)}); err != nil {
		return nil, err
	}
	outBuf := make([]float64, n)
	if err := statusError("Adosc", C.ft_adosc(inPtr(high), inPtr(low), inPtr(close), inPtr(volume), C.size_t(n), C.int64_t(fastperiod), C.int64_t(slowperiod), (*C.double)(outPtr(outBuf)))); err != nil {
		return nil, err
	}
	return outBuf, nil
}
