/* Generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT. */

/*
 * ferro_ta C API v1.3.1
 *
 * Conventions:
 *  - Every function returns an int32_t status (FT_OK == 0); see ft_status_message().
 *  - Inputs are `const double *` arrays sharing one `size_t len`.
 *  - Outputs are caller-allocated arrays of length `len`, written only on success.
 *    An output may alias an input (in-place). Any array may be NULL when len == 0.
 *  - Periods are int64_t (validated >= their minimum), MA types int32_t in 0..8.
 *  - Float parameters must be finite.
 *  - Leading warm-up values are NaN; output length always equals input length.
 *  - Streaming handles are not thread-safe; free each exactly once.
 */

#ifndef FERRO_TA_H
#define FERRO_TA_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FT_VERSION "1.3.1"

#define FT_OK 0
#define FT_ERR_NULL_PTR 1
#define FT_ERR_INVALID_PARAM 2
#define FT_ERR_LENGTH_MISMATCH 3
#define FT_ERR_PANIC 4

/** Static description of a status code. Never NULL; do not free. */
const char *ft_status_message(int32_t code);
/** Library version string. Static; do not free. */
const char *ft_version(void);

/* ---- overlap --------------------------------------------------------------- */

/**
 * Compute Bollinger Bands, returning `(upper, middle, lower)`.
 */
int32_t ft_bbands(const double *close, size_t len, int64_t timeperiod, double nbdevup, double nbdevdn, int32_t matype, double *out_upper, double *out_middle, double *out_lower);

/**
 * MACD with fixed 12/26 periods.
 */
int32_t ft_macdfix(const double *close, size_t len, int64_t signalperiod, double *out_macd, double *out_signal, double *out_hist);

/**
 * MACD with configurable MA types for fast/slow/signal.
 */
int32_t ft_macdext(const double *close, size_t len, int64_t fastperiod, int32_t fastmatype, int64_t slowperiod, int32_t slowmatype, int64_t signalperiod, int32_t signalmatype, double *out_macd, double *out_signal, double *out_hist);

/**
 * Generic Moving Average. matype: 0=SMA, 1=EMA, 2=WMA, 3=DEMA, 4=TEMA,
 */
int32_t ft_ma(const double *close, size_t len, int64_t timeperiod, int32_t matype, double *out);

/**
 * Moving Average with Variable Period per bar.
 */
int32_t ft_mavp(const double *close, const double *periods, size_t len, int64_t minperiod, int64_t maxperiod, int32_t matype, double *out);

/**
 * Compute the Exponential Moving Average (EMA).
 */
int32_t ft_ema(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Double Exponential Moving Average: `2*EMA - EMA(EMA)`.
 */
int32_t ft_dema(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Triple Exponential Moving Average: `3*EMA - 3*EMA(EMA) + EMA(EMA(EMA))`.
 */
int32_t ft_tema(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Tillson T3: 6 cascaded SMA-seeded EMAs with volume factor.
 */
int32_t ft_t3(const double *close, size_t len, int64_t timeperiod, double vfactor, double *out);

/**
 * Kaufman Adaptive Moving Average (TA-Lib).
 */
int32_t ft_kama(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Moving Average Convergence/Divergence (MACD).
 */
int32_t ft_macd(const double *close, size_t len, int64_t fastperiod, int64_t slowperiod, int64_t signalperiod, double *out_macd, double *out_signal, double *out_hist);

/**
 * MESA Adaptive Moving Average. Returns `(mama, fama)`.
 */
int32_t ft_mama(const double *close, size_t len, double fastlimit, double slowlimit, double *out_mama, double *out_fama);

/**
 * Midpoint: `(max(close) + min(close)) / 2` over rolling window.
 */
int32_t ft_midpoint(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * MidPrice: `(highest_high + lowest_low) / 2` over rolling window.
 */
int32_t ft_midprice(const double *high, const double *low, size_t len, int64_t timeperiod, double *out);

/**
 * Parabolic SAR.
 */
int32_t ft_sar(const double *high, const double *low, size_t len, double acceleration, double maximum, double *out);

/**
 * Parabolic SAR Extended with configurable acceleration factors.
 */
int32_t ft_sarext(const double *high, const double *low, size_t len, double startvalue, double offsetonreverse, double accelerationinitlong, double accelerationlong, double accelerationmaxlong, double accelerationinitshort, double accelerationshort, double accelerationmaxshort, double *out);

/**
 * Compute the Simple Moving Average (SMA) over a rolling window.
 */
int32_t ft_sma(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Triangular Moving Average (triangle-weighted).
 */
int32_t ft_trima(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Weighted Moving Average (WMA).
 */
int32_t ft_wma(const double *close, size_t len, int64_t timeperiod, double *out);

/* ---- momentum -------------------------------------------------------------- */

/**
 * Compute the Plus Directional Movement (+DM), Wilder smoothed.
 */
int32_t ft_plus_dm(const double *high, const double *low, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Minus Directional Movement (-DM), Wilder smoothed.
 */
int32_t ft_minus_dm(const double *high, const double *low, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Plus Directional Indicator (+DI), Wilder smoothed.
 */
int32_t ft_plus_di(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Minus Directional Indicator (-DI), Wilder smoothed.
 */
int32_t ft_minus_di(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Directional Movement Index (DX).
 */
int32_t ft_dx(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Average Directional Movement Index (ADX).
 */
int32_t ft_adx(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the ADX Rating (ADXR).
 */
int32_t ft_adxr(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Aroon indicator. Returns `(aroon_down, aroon_up)`.
 */
int32_t ft_aroon(const double *high, const double *low, size_t len, int64_t timeperiod, double *out_aroondown, double *out_aroonup);

/**
 * Aroon Oscillator: `aroon_up - aroon_down`.
 */
int32_t ft_aroonosc(const double *high, const double *low, size_t len, int64_t timeperiod, double *out);

/**
 * Absolute Price Oscillator: `fast MA - slow MA`.
 */
int32_t ft_apo(const double *close, size_t len, int64_t fastperiod, int64_t slowperiod, int32_t matype, double *out);

/**
 * Percentage Price Oscillator: `(fast MA - slow MA) / slow MA * 100`.
 */
int32_t ft_ppo(const double *close, size_t len, int64_t fastperiod, int64_t slowperiod, int64_t signalperiod, int32_t matype, double *out_ppo, double *out_signal, double *out_hist);

/**
 * TRIX: 1-period rate of change of triple-smoothed EMA.
 */
int32_t ft_trix(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Williams %R: `-100 * (HH - close) / (HH - LL)` over the window.
 */
int32_t ft_willr(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Commodity Channel Index: `(tp - SMA(tp)) / (0.015 * MAD)`.
 */
int32_t ft_cci(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Balance of Power: `(close - open) / (high - low)`.
 */
int32_t ft_bop(const double *open, const double *high, const double *low, const double *close, size_t len, double *out);

/**
 * Compute the Momentum indicator: `close[i] - close[i - timeperiod]`.
 */
int32_t ft_mom(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Rate of Change: `(close[i] - close[i-p]) / close[i-p] * 100`.
 */
int32_t ft_roc(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Rate of Change Percentage: `(close[i] - close[i-p]) / close[i-p]`.
 */
int32_t ft_rocp(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Rate of Change Ratio: `close[i] / close[i-p]`.
 */
int32_t ft_rocr(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Rate of Change Ratio x 100: `close[i] / close[i-p] * 100`.
 */
int32_t ft_rocr100(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Relative Strength Index (RSI).
 */
int32_t ft_rsi(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Chande Momentum Oscillator: `100 * (gains - losses) / (gains + losses)`.
 */
int32_t ft_cmo(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the Stochastic Oscillator (TA-Lib compatible).
 */
int32_t ft_stoch(const double *high, const double *low, const double *close, size_t len, int64_t fastk_period, int64_t slowk_period, int32_t slowk_matype, int64_t slowd_period, int32_t slowd_matype, double *out_slowk, double *out_slowd);

/**
 * Fast Stochastic. Returns `(fastk, fastd)`.
 */
int32_t ft_stochf(const double *high, const double *low, const double *close, size_t len, int64_t fastk_period, int64_t fastd_period, int32_t fastd_matype, double *out_fastk, double *out_fastd);

/**
 * Stochastic RSI. Returns `(fastk, fastd)`.
 */
int32_t ft_stochrsi(const double *close, size_t len, int64_t timeperiod, int64_t fastk_period, int64_t fastd_period, int32_t fastd_matype, double *out_fastk, double *out_fastd);

/**
 * Ultimate Oscillator: weighted average of buying pressure over three periods.
 */
int32_t ft_ultosc(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod1, int64_t timeperiod2, int64_t timeperiod3, double *out);

/* ---- volatility ------------------------------------------------------------ */

/**
 * Compute the Average True Range (ATR), Wilder smoothed (TA-Lib compatible).
 */
int32_t ft_atr(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the True Range for each bar.
 */
int32_t ft_trange(const double *high, const double *low, const double *close, size_t len, double *out);

/**
 * Normalized Average True Range: `ATR / close * 100`.
 */
int32_t ft_natr(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/* ---- volume ---------------------------------------------------------------- */

/**
 * Compute On-Balance Volume (OBV).
 */
int32_t ft_obv(const double *close, const double *volume, size_t len, double *out);

/**
 * Compute the Money Flow Index (MFI).
 */
int32_t ft_mfi(const double *high, const double *low, const double *close, const double *volume, size_t len, int64_t timeperiod, double *out);

/**
 * Chaikin Accumulation/Distribution Line.
 */
int32_t ft_ad(const double *high, const double *low, const double *close, const double *volume, size_t len, double *out);

/**
 * Chaikin A/D Oscillator: fast EMA of AD minus slow EMA of AD.
 */
int32_t ft_adosc(const double *high, const double *low, const double *close, const double *volume, size_t len, int64_t fastperiod, int64_t slowperiod, double *out);

/* ---- cycle ----------------------------------------------------------------- */

/**
 * Hilbert Transform Instantaneous Trendline (Ehlers).
 */
int32_t ft_ht_trendline(const double *close, size_t len, double *out);

/**
 * Hilbert Transform Dominant Cycle Period in bars.
 */
int32_t ft_ht_dcperiod(const double *close, size_t len, double *out);

/**
 * Hilbert Transform Dominant Cycle Phase in degrees.
 */
int32_t ft_ht_dcphase(const double *close, size_t len, double *out);

/**
 * Hilbert Transform Phasor components. Returns `(inphase, quadrature)`.
 */
int32_t ft_ht_phasor(const double *close, size_t len, double *out_inphase, double *out_quadrature);

/**
 * Hilbert Transform SineWave. Returns `(sine, leadsine)` where leadsine
 */
int32_t ft_ht_sine(const double *close, size_t len, double *out_sine, double *out_leadsine);

/**
 * Hilbert Transform Trend vs Cycle Mode: 1 = trending, 0 = cycling.
 */
int32_t ft_ht_trendmode(const double *close, size_t len, int32_t *out);

/* ---- statistic ------------------------------------------------------------- */

/**
 * Compute the rolling population standard deviation, scaled by `nbdev`.
 */
int32_t ft_stddev(const double *real, size_t len, int64_t timeperiod, double nbdev, double *out);

/**
 * Rolling population variance, scaled by `nbdev**2`.
 */
int32_t ft_var(const double *real, size_t len, int64_t timeperiod, double nbdev, double *out);

/**
 * Linear regression fitted value at the last point of the window.
 */
int32_t ft_linearreg(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Slope of the rolling linear regression line.
 */
int32_t ft_linearreg_slope(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Intercept of the rolling linear regression line.
 */
int32_t ft_linearreg_intercept(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Angle of the regression line in degrees.
 */
int32_t ft_linearreg_angle(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Time Series Forecast: linear regression extrapolated one period ahead.
 */
int32_t ft_tsf(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Rolling beta: regression of real1 daily returns on real0 daily returns.
 */
int32_t ft_beta(const double *real0, const double *real1, size_t len, int64_t timeperiod, double *out);

/**
 * Rolling Pearson correlation coefficient between two series.
 */
int32_t ft_correl(const double *real0, const double *real1, size_t len, int64_t timeperiod, double *out);

/* ---- math ------------------------------------------------------------------ */

/**
 * Compute the rolling sum over `timeperiod` bars.
 */
int32_t ft_sum(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the rolling maximum over `timeperiod` bars.
 */
int32_t ft_max(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the rolling minimum over `timeperiod` bars.
 */
int32_t ft_min(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the sliding maximum over `timeperiod` bars in O(n) time.
 */
int32_t ft_sliding_max(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Compute the sliding minimum over `timeperiod` bars in O(n) time.
 */
int32_t ft_sliding_min(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Element-wise addition of two arrays.
 */
int32_t ft_add(const double *a, const double *b, size_t len, double *out);

/**
 * Element-wise subtraction of two arrays.
 */
int32_t ft_sub(const double *a, const double *b, size_t len, double *out);

/**
 * Element-wise multiplication of two arrays.
 */
int32_t ft_mult(const double *a, const double *b, size_t len, double *out);

/**
 * Element-wise division of two arrays (NaN where b=0).
 */
int32_t ft_div(const double *a, const double *b, size_t len, double *out);

/* ---- math_ops -------------------------------------------------------------- */

/**
 * Rolling sum over `timeperiod` bars using an O(n) sliding window.
 */
int32_t ft_rolling_sum(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Rolling maximum over `timeperiod` bars (O(n) monotonic deque).
 */
int32_t ft_rolling_max(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Rolling minimum over `timeperiod` bars (O(n) monotonic deque).
 */
int32_t ft_rolling_min(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Index of rolling maximum over `timeperiod` bars.
 */
int32_t ft_rolling_maxindex(const double *real, size_t len, int64_t timeperiod, int64_t *out);

/**
 * Index of rolling minimum over `timeperiod` bars.
 */
int32_t ft_rolling_minindex(const double *real, size_t len, int64_t timeperiod, int64_t *out);

/* ---- price_transform ------------------------------------------------------- */

/**
 * Average Price: (open + high + low + close) / 4.
 */
int32_t ft_avgprice(const double *open, const double *high, const double *low, const double *close, size_t len, double *out);

/**
 * Median Price: (high + low) / 2.
 */
int32_t ft_medprice(const double *high, const double *low, size_t len, double *out);

/**
 * Typical Price: (high + low + close) / 3.
 */
int32_t ft_typprice(const double *high, const double *low, const double *close, size_t len, double *out);

/**
 * Weighted Close Price: (high + low + close * 2) / 4.
 */
int32_t ft_wclprice(const double *high, const double *low, const double *close, size_t len, double *out);

/* ---- pattern --------------------------------------------------------------- */

/**
 * Two Crows (bearish)
 */
int32_t ft_cdl2crows(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Three Black Crows (bearish)
 */
int32_t ft_cdl3blackcrows(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Three Inside Up/Down
 */
int32_t ft_cdl3inside(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Three-Line Strike
 */
int32_t ft_cdl3linestrike(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Three Outside Up/Down
 */
int32_t ft_cdl3outside(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Three Stars In The South (bullish)
 */
int32_t ft_cdl3starsinsouth(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Three Advancing White Soldiers (bullish)
 */
int32_t ft_cdl3whitesoldiers(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Abandoned Baby
 */
int32_t ft_cdlabandonedbaby(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Advance Block (bearish)
 */
int32_t ft_cdladvanceblock(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Belt-hold
 */
int32_t ft_cdlbelthold(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Breakaway
 */
int32_t ft_cdlbreakaway(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Closing Marubozu
 */
int32_t ft_cdlclosingmarubozu(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Concealing Baby Swallow (bullish)
 */
int32_t ft_cdlconcealbabyswall(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Counterattack
 */
int32_t ft_cdlcounterattack(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Dark Cloud Cover (bearish)
 */
int32_t ft_cdldarkcloudcover(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Doji
 */
int32_t ft_cdldoji(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Doji Star
 */
int32_t ft_cdldojistar(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Dragonfly Doji (bullish)
 */
int32_t ft_cdldragonflydoji(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Engulfing
 */
int32_t ft_cdlengulfing(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Evening Doji Star (bearish)
 */
int32_t ft_cdleveningdojistar(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Evening Star (bearish)
 */
int32_t ft_cdleveningstar(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Up/Down-gap side-by-side white lines
 */
int32_t ft_cdlgapsidesidewhite(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Gravestone Doji (bearish)
 */
int32_t ft_cdlgravestonedoji(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Hammer (bullish)
 */
int32_t ft_cdlhammer(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Hanging Man (bearish)
 */
int32_t ft_cdlhangingman(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Harami
 */
int32_t ft_cdlharami(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Harami Cross
 */
int32_t ft_cdlharamicross(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * High-Wave Candle
 */
int32_t ft_cdlhighwave(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Hikkake Pattern
 */
int32_t ft_cdlhikkake(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Modified Hikkake Pattern
 */
int32_t ft_cdlhikkakemod(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Homing Pigeon (bullish)
 */
int32_t ft_cdlhomingpigeon(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Identical Three Crows (bearish)
 */
int32_t ft_cdlidentical3crows(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * In-Neck Pattern (bearish)
 */
int32_t ft_cdlinneck(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Inverted Hammer (bullish)
 */
int32_t ft_cdlinvertedhammer(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Kicking
 */
int32_t ft_cdlkicking(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Kicking — bull/bear determined by longer of the two marubozu
 */
int32_t ft_cdlkickingbylength(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Ladder Bottom (bullish)
 */
int32_t ft_cdlladderbottom(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Long Legged Doji
 */
int32_t ft_cdllongleggeddoji(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Long Line Candle
 */
int32_t ft_cdllongline(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Marubozu
 */
int32_t ft_cdlmarubozu(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Matching Low (bullish)
 */
int32_t ft_cdlmatchinglow(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Mat Hold (bullish)
 */
int32_t ft_cdlmathold(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Morning Doji Star (bullish)
 */
int32_t ft_cdlmorningdojistar(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Morning Star (bullish)
 */
int32_t ft_cdlmorningstar(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * On-Neck Pattern (bearish)
 */
int32_t ft_cdlonneck(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Piercing Pattern (bullish)
 */
int32_t ft_cdlpiercing(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Rickshaw Man
 */
int32_t ft_cdlrickshawman(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Rising/Falling Three Methods
 */
int32_t ft_cdlrisefall3methods(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Separating Lines
 */
int32_t ft_cdlseparatinglines(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Shooting Star (bearish)
 */
int32_t ft_cdlshootingstar(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Short Line Candle
 */
int32_t ft_cdlshortline(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Spinning Top
 */
int32_t ft_cdlspinningtop(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Stalled Pattern (bearish)
 */
int32_t ft_cdlstalledpattern(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Stick Sandwich (bullish)
 */
int32_t ft_cdlsticksandwich(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Takuri (Dragonfly Doji with very long lower shadow)
 */
int32_t ft_cdltakuri(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Tasuki Gap
 */
int32_t ft_cdltasukigap(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Thrusting Pattern (bearish)
 */
int32_t ft_cdlthrusting(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Tristar Pattern
 */
int32_t ft_cdltristar(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Unique 3 River (bullish)
 */
int32_t ft_cdlunique3river(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Upside Gap Two Crows (bearish)
 */
int32_t ft_cdlupsidegap2crows(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/**
 * Upside/Downside Gap Three Methods
 */
int32_t ft_cdlxsidegap3methods(const double *open, const double *high, const double *low, const double *close, size_t len, int32_t *out);

/* ---- extended -------------------------------------------------------------- */

/**
 * ATR-based Supertrend indicator.
 */
int32_t ft_supertrend(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double multiplier, double *out_line, int8_t *out_direction);

/**
 * Donchian Channels — rolling highest high / lowest low.
 */
int32_t ft_donchian(const double *high, const double *low, size_t len, int64_t timeperiod, double *out_upper, double *out_middle, double *out_lower);

/**
 * Keltner Channels — EMA +/- (multiplier x ATR).
 */
int32_t ft_keltner_channels(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, int64_t atr_period, double multiplier, double *out_upper, double *out_middle, double *out_lower);

/**
 * Chandelier Exit — ATR-based trailing stop levels.
 */
int32_t ft_chandelier_exit(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double multiplier, double *out_long_exit, double *out_short_exit);

/**
 * Choppiness Index — measures market choppiness vs trending.
 */
int32_t ft_choppiness_index(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Hull Moving Average (HMA).
 */
int32_t ft_hull_ma(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Directional Movement Index as `(PLUS_DI, MINUS_DI, ADX)`.
 */
int32_t ft_dmi(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out_plus_di, double *out_minus_di, double *out_adx);

/**
 * Williams Fractals: local swing high / swing low with `timeperiod` bars
 */
int32_t ft_williams_fractals(const double *high, const double *low, size_t len, int64_t timeperiod, double *out_up, double *out_down);

/**
 * Random Walk Index (Poulos): max over lookbacks `2..=timeperiod` of
 */
int32_t ft_rwi(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out_rwi_high, double *out_rwi_low);

/**
 * # Returns
 */
int32_t ft_ichimoku(const double *high, const double *low, const double *close, size_t len, int64_t tenkan_period, int64_t kijun_period, int64_t senkou_b_period, int64_t displacement, double *out_tenkan, double *out_kijun, double *out_senkou_a, double *out_senkou_b, double *out_chikou);

/**
 * Elder Ray Index: bull power and bear power versus an EMA of close.
 */
int32_t ft_elder_ray(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out_bull, double *out_bear);

/**
 * Ehlers Fisher Transform of median price, plus a 1-bar trigger.
 */
int32_t ft_fisher(const double *high, const double *low, size_t len, int64_t timeperiod, double *out_fisher, double *out_signal);

/**
 * Connors RSI: average of price RSI, streak RSI, and percent rank of ROC.
 */
int32_t ft_crsi(const double *close, size_t len, int64_t timeperiod, int64_t streakperiod, int64_t rankperiod, double *out);

/**
 * Awesome Oscillator: `SMA(median, fast) − SMA(median, slow)`.
 */
int32_t ft_ao(const double *high, const double *low, size_t len, int64_t fastperiod, int64_t slowperiod, double *out);

/**
 * Accelerator Oscillator: `AO − SMA(AO, timeperiod)`.
 */
int32_t ft_ac(const double *high, const double *low, size_t len, int64_t fastperiod, int64_t slowperiod, int64_t timeperiod, double *out);

/**
 * Price Oscillator (SMA): `SMA(close, fast) − SMA(close, slow)`.
 */
int32_t ft_po(const double *close, size_t len, int64_t fastperiod, int64_t slowperiod, double *out);

/**
 * Detrended Price Oscillator: `close[i − shift] − SMA(close, timeperiod)`,
 */
int32_t ft_dpo(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Relative Vigor Index and its 4-bar weighted signal.
 */
int32_t ft_rvi(const double *open, const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out_rvi, double *out_signal);

/**
 * Chaikin Oscillator — same math as [`volume::adosc`].
 */
int32_t ft_cho(const double *high, const double *low, const double *close, const double *volume, size_t len, int64_t fastperiod, int64_t slowperiod, double *out);

/**
 * Know Sure Thing: weighted sum of four ROC SMAs, plus a signal SMA.
 */
int32_t ft_kst(const double *close, size_t len, int64_t roc1, int64_t roc2, int64_t roc3, int64_t roc4, int64_t sma1, int64_t sma2, int64_t sma3, int64_t sma4, int64_t signalperiod, double *out_kst, double *out_signal);

/**
 * True Strength Index and an EMA signal of that series.
 */
int32_t ft_tsi(const double *close, size_t len, int64_t longperiod, int64_t shortperiod, int64_t signalperiod, double *out_tsi, double *out_signal);

/**
 * Vortex Indicator: `+VI` and `−VI` over `timeperiod`.
 */
int32_t ft_vortex(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double *out_plus_vi, double *out_minus_vi);

/**
 * Schaff Trend Cycle: stochastic of MACD, double-smoothed (`d1`, `d2`).
 */
int32_t ft_stc(const double *close, size_t len, int64_t fastperiod, int64_t slowperiod, int64_t cycleperiod, int64_t d1, int64_t d2, double *out);

/**
 * Gator Oscillator from the Alligator jaw / teeth / lips.
 */
int32_t ft_gator(const double *high, const double *low, size_t len, int64_t jaw_period, int64_t jaw_shift, int64_t teeth_period, int64_t teeth_shift, int64_t lips_period, int64_t lips_shift, double *out_upper, double *out_lower);

/**
 * Coppock Curve: `WMA(ROC(roc1) + ROC(roc2), wma_period)`.
 */
int32_t ft_coppock(const double *close, size_t len, int64_t wma_period, int64_t roc1, int64_t roc2, double *out);

/**
 * Rolling median of `real` over `timeperiod`.
 */
int32_t ft_median(const double *real, size_t len, int64_t timeperiod, double *out);

/**
 * Median bands: rolling median of `(high + low) / 2`, ATR envelopes, and an
 */
int32_t ft_median_bands(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, int64_t atr_period, double multiplier, double *out_median, double *out_upper, double *out_lower, double *out_median_ema);

/**
 * Rolling mode via equal-width discretization of each window.
 */
int32_t ft_mode(const double *real, size_t len, int64_t timeperiod, int64_t bins, double *out);

/**
 * Arnaud Legoux Moving Average.
 */
int32_t ft_alma(const double *close, size_t len, int64_t timeperiod, double offset, double sigma, double *out);

/**
 * Zero-lag exponential moving average.
 */
int32_t ft_zlema(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Fractal Adaptive Moving Average (Ehlers).
 */
int32_t ft_frama(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * McGinley Dynamic.
 */
int32_t ft_mcginley(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Variable Index Dynamic Average (Chande).
 */
int32_t ft_vidya(const double *close, size_t len, int64_t timeperiod, int64_t cmo_period, double *out);

/**
 * Bill Williams Alligator (jaw / teeth / lips).
 */
int32_t ft_alligator(const double *high, const double *low, size_t len, int64_t jaw_period, int64_t jaw_shift, int64_t teeth_period, int64_t teeth_shift, int64_t lips_period, int64_t lips_shift, double *out_jaw, double *out_teeth, double *out_lips);

/**
 * Moving-average envelopes: `MA * (1 ± percent / 100)`.
 */
int32_t ft_ma_envelopes(const double *close, size_t len, int64_t timeperiod, double percent, int32_t matype, double *out_upper, double *out_middle, double *out_lower);

/**
 * Chande Kroll Stop.
 */
int32_t ft_chande_kroll_stop(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, double multiplier, int64_t stop_period, double *out_long_stop, double *out_short_stop);

/**
 * Chaikin Volatility: rate of change of an EMA of the high–low range.
 */
int32_t ft_chaikin_vol(const double *high, const double *low, size_t len, int64_t timeperiod, int64_t rocperiod, double *out);

/**
 * Mass Index: rolling sum of the single/double EMA ratio of the high–low range.
 */
int32_t ft_mass(const double *high, const double *low, size_t len, int64_t timeperiod, int64_t sumperiod, double *out);

/**
 * Bollinger %B: `(close - lower) / (upper - lower)` from [`overlap::bbands`].
 */
int32_t ft_bbpercent(const double *close, size_t len, int64_t timeperiod, double nbdevup, double nbdevdn, double *out);

/**
 * Bollinger Bandwidth: `(upper - lower) / middle` from [`overlap::bbands`].
 */
int32_t ft_bbwidth(const double *close, size_t len, int64_t timeperiod, double nbdevup, double nbdevdn, double *out);

/**
 * Close-to-close historical volatility, annualized and in percent.
 */
int32_t ft_historical_volatility(const double *close, size_t len, int64_t timeperiod, double annual, double *out);

/**
 * Ulcer Index: RMS of percent drawdowns versus the rolling highest close.
 */
int32_t ft_ulcer_index(const double *close, size_t len, int64_t timeperiod, double *out);

/**
 * Stoller Average Range Channels: SMA of close ± `multiplier * ATR`.
 */
int32_t ft_starc(const double *high, const double *low, const double *close, size_t len, int64_t timeperiod, int64_t atr_period, double multiplier, double *out_upper, double *out_middle, double *out_lower);

/**
 * On-Balance Volume smoothed with [`overlap::ma`].
 */
int32_t ft_obv_smoothed(const double *close, const double *volume, size_t len, int64_t timeperiod, int32_t matype, double *out);

/**
 * Chaikin Money Flow: rolling sum of CLV × volume over rolling volume.
 */
int32_t ft_cmf(const double *high, const double *low, const double *close, const double *volume, size_t len, int64_t timeperiod, double *out);

/**
 * Ease of Movement, then SMA.
 */
int32_t ft_emv(const double *high, const double *low, const double *volume, size_t len, int64_t timeperiod, double scale, double *out);

/**
 * Force Index: `(close - close[1]) * volume`, optionally EMA-smoothed.
 */
int32_t ft_force_index(const double *close, const double *volume, size_t len, int64_t timeperiod, double *out);

/**
 * Negative Volume Index, seeded at 1000.
 */
int32_t ft_nvi(const double *close, const double *volume, size_t len, double *out);

/**
 * NVI plus an EMA signal of that series.
 */
int32_t ft_nvi_with_ema(const double *close, const double *volume, size_t len, int64_t timeperiod, double *out_nvi, double *out_signal);

/**
 * Positive Volume Index, seeded at 1000.
 */
int32_t ft_pvi(const double *close, const double *volume, size_t len, double *out);

/**
 * PVI plus a moving-average signal (`matype` matches `MA`, `0`-`8`).
 */
int32_t ft_pvi_with_signal(const double *close, const double *volume, size_t len, int64_t timeperiod, int32_t matype, double *out_pvi, double *out_signal);

/**
 * Volume oscillator: `100 * (SMA(vol, fast) - SMA(vol, slow)) / SMA(vol, slow)`.
 */
int32_t ft_volosc(const double *volume, size_t len, int64_t fastperiod, int64_t slowperiod, double *out);

/**
 * Volume rate of change: `100 * (volume - volume[timeperiod]) / volume[timeperiod]`.
 */
int32_t ft_vroc(const double *volume, size_t len, int64_t timeperiod, double *out);

/**
 * Klinger Volume Oscillator and its EMA signal.
 */
int32_t ft_kvo(const double *high, const double *low, const double *close, const double *volume, size_t len, int64_t fastperiod, int64_t slowperiod, int64_t signalperiod, double *out_kvo, double *out_signal);

/**
 * Price Volume Trend: cumulative `volume * (close - close[1]) / close[1]`.
 */
int32_t ft_pvt(const double *close, const double *volume, size_t len, double *out);

/**
 * Relative volume: `volume / SMA(volume, timeperiod)`.
 */
int32_t ft_rvol(const double *volume, size_t len, int64_t timeperiod, double *out);

/**
 * Volume Weighted Average Price (cumulative or rolling).
 */
int32_t ft_vwap(const double *high, const double *low, const double *close, const double *volume, size_t len, int64_t timeperiod, double *out);

/**
 * Volume Weighted Moving Average.
 */
int32_t ft_vwma(const double *close, const double *volume, size_t len, int64_t timeperiod, double *out);

/* ---- streaming ------------------------------------------------------------- */

/**
 * Streaming simple moving average.
 */
typedef struct FtStreamSma FtStreamSma;
int32_t ft_stream_sma_new(int64_t period, FtStreamSma **out_handle);
int32_t ft_stream_sma_update(FtStreamSma *handle, double value, double *out);
int32_t ft_stream_sma_reset(FtStreamSma *handle);
void ft_stream_sma_free(FtStreamSma *handle);

/**
 * Streaming exponential moving average (SMA-seeded, TA-Lib compatible).
 */
typedef struct FtStreamEma FtStreamEma;
int32_t ft_stream_ema_new(int64_t period, FtStreamEma **out_handle);
int32_t ft_stream_ema_update(FtStreamEma *handle, double value, double *out);
int32_t ft_stream_ema_reset(FtStreamEma *handle);
void ft_stream_ema_free(FtStreamEma *handle);

/**
 * Streaming RSI (Wilder smoothing).
 */
typedef struct FtStreamRsi FtStreamRsi;
int32_t ft_stream_rsi_new(int64_t period, FtStreamRsi **out_handle);
int32_t ft_stream_rsi_update(FtStreamRsi *handle, double value, double *out);
int32_t ft_stream_rsi_reset(FtStreamRsi *handle);
void ft_stream_rsi_free(FtStreamRsi *handle);

/**
 * Streaming average true range.
 */
typedef struct FtStreamAtr FtStreamAtr;
int32_t ft_stream_atr_new(int64_t period, FtStreamAtr **out_handle);
int32_t ft_stream_atr_update(FtStreamAtr *handle, double high, double low, double close, double *out);
int32_t ft_stream_atr_reset(FtStreamAtr *handle);
void ft_stream_atr_free(FtStreamAtr *handle);

/**
 * Streaming Bollinger Bands.
 */
typedef struct FtStreamBbands FtStreamBbands;
int32_t ft_stream_bbands_new(int64_t period, double nbdevup, double nbdevdn, FtStreamBbands **out_handle);
int32_t ft_stream_bbands_update(FtStreamBbands *handle, double value, double *out_upper, double *out_middle, double *out_lower);
int32_t ft_stream_bbands_reset(FtStreamBbands *handle);
void ft_stream_bbands_free(FtStreamBbands *handle);

/**
 * Streaming MACD. Requires `fastperiod < slowperiod`.
 */
typedef struct FtStreamMacd FtStreamMacd;
int32_t ft_stream_macd_new(int64_t fastperiod, int64_t slowperiod, int64_t signalperiod, FtStreamMacd **out_handle);
int32_t ft_stream_macd_update(FtStreamMacd *handle, double value, double *out_macd, double *out_signal, double *out_hist);
int32_t ft_stream_macd_reset(FtStreamMacd *handle);
void ft_stream_macd_free(FtStreamMacd *handle);

/**
 * Streaming slow stochastic.
 */
typedef struct FtStreamStoch FtStreamStoch;
int32_t ft_stream_stoch_new(int64_t fastk_period, int64_t slowk_period, int64_t slowd_period, FtStreamStoch **out_handle);
int32_t ft_stream_stoch_update(FtStreamStoch *handle, double high, double low, double close, double *out_slowk, double *out_slowd);
int32_t ft_stream_stoch_reset(FtStreamStoch *handle);
void ft_stream_stoch_free(FtStreamStoch *handle);

/**
 * Streaming cumulative VWAP (session-anchored; `reset` starts a new session).
 */
typedef struct FtStreamVwap FtStreamVwap;
int32_t ft_stream_vwap_new(FtStreamVwap **out_handle);
int32_t ft_stream_vwap_update(FtStreamVwap *handle, double high, double low, double close, double volume, double *out);
int32_t ft_stream_vwap_reset(FtStreamVwap *handle);
void ft_stream_vwap_free(FtStreamVwap *handle);

/**
 * Streaming Supertrend. `out_direction` is 1 (up) / -1 (down), 0 in warm-up.
 */
typedef struct FtStreamSupertrend FtStreamSupertrend;
int32_t ft_stream_supertrend_new(int64_t period, double multiplier, FtStreamSupertrend **out_handle);
int32_t ft_stream_supertrend_update(FtStreamSupertrend *handle, double high, double low, double close, double *out_line, int8_t *out_direction);
int32_t ft_stream_supertrend_reset(FtStreamSupertrend *handle);
void ft_stream_supertrend_free(FtStreamSupertrend *handle);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* FERRO_TA_H */
