/*!
# ferro-ta Flutter bindings

`flutter_rust_bridge` bindings for the ferro-ta technical analysis library.

The [`api`] module holds plain-Rust `pub fn` wrappers over `ferro_ta_core`
(generated by `scripts/build_flutter_bridge.py`). flutter_rust_bridge scans that
module and emits the Dart↔Rust glue into `frb_generated.rs` / the Dart package.

The generated glue is compiled only under the `frb` feature so that
`cargo build -p ferro_ta_flutter` (default features) verifies indicator parity
against the core crate without requiring a codegen run.
*/

pub mod api;

// Emitted by `flutter_rust_bridge_codegen generate` (run in CI / via
// `make flutter-gen`). Kept behind the `frb` feature so the crate still builds
// before codegen has produced the file.
#[cfg(feature = "frb")]
mod frb_generated;
