#!/usr/bin/env python3
"""Generate the C header and C-ABI language wrappers from the FFI spec.

``crates/ferro_ta_ffi`` records the signature of every export it defines (the
``ffi_exports!`` / ``ffi_streams!`` macros emit metadata next to each
``extern "C"`` function). Its ``dump_spec`` example serialises that metadata to
``crates/ferro_ta_ffi/ffi_spec.json``; this script turns the spec into:

- ``crates/ferro_ta_ffi/include/ferro_ta.h``  (the public C header)
- ``bindings/go/include/ferro_ta.h``           (copy; Go modules are self-contained)
- ``bindings/go/<group>_gen.go``               (idiomatic Go wrappers)

cbindgen is not used because it cannot see macro-generated items on stable Rust.

Usage
-----
python3 scripts/build_ffi_bindings.py           # regenerate spec, header and wrappers
python3 scripts/build_ffi_bindings.py --check   # fail if anything is out of date
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FFI_DIR = ROOT / "crates" / "ferro_ta_ffi"
SPEC_PATH = FFI_DIR / "ffi_spec.json"
HEADER_PATH = FFI_DIR / "include" / "ferro_ta.h"
GO_DIR = ROOT / "bindings" / "go"
GO_HEADER_PATH = GO_DIR / "include" / "ferro_ta.h"

GENERATED_NOTE = (
    "Generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT."
)

GO_ELEM = {"f64": "float64", "i32": "int32", "i64": "int64", "i8": "int8"}
C_ELEM = {"f64": "C.double", "i32": "C.int32_t", "i64": "C.int64_t", "i8": "C.int8_t"}


# ---------------------------------------------------------------------------
# Spec
# ---------------------------------------------------------------------------


def dump_spec() -> str:
    """Run the Rust dump_spec example and return its JSON output."""
    result = subprocess.run(
        ["cargo", "run", "-q", "-p", "ferro_ta_ffi", "--example", "dump_spec"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.exit(f"dump_spec failed:\n{result.stderr}")
    return result.stdout


# ---------------------------------------------------------------------------
# C header
# ---------------------------------------------------------------------------


def c_doc(doc: str, indent: str = "") -> list[str]:
    if not doc:
        return []
    lines = [f"{indent}/**"]
    lines += [f"{indent} * {line}".rstrip() for line in doc.splitlines()]
    lines.append(f"{indent} */")
    return lines


def c_function(fn: dict) -> str:
    args = [f"const double *{name}" for name in fn["inputs"]]
    args.append("size_t len")
    args += [f"{p['c_type']} {p['name']}" for p in fn["params"]]
    args += [f"{o['c_type']} *{o['name']}" for o in fn["outputs"]]
    return f"int32_t {fn['name']}({', '.join(args)});"


def c_stream(stream: dict) -> list[str]:
    handle = stream["handle"]
    new_args = [f"{p['c_type']} {p['name']}" for p in stream["params"]]
    new_args.append(f"{handle} **out_handle")
    update_args = [f"{handle} *handle"]
    update_args += [f"double {name}" for name in stream["inputs"]]
    update_args += [f"{o['c_type']} *{o['name']}" for o in stream["outputs"]]
    return [
        *c_doc(stream["doc"]),
        f"typedef struct {handle} {handle};",
        f"int32_t {stream['new_fn']}({', '.join(new_args)});",
        f"int32_t {stream['update_fn']}({', '.join(update_args)});",
        f"int32_t {stream['reset_fn']}({handle} *handle);",
        f"void {stream['free_fn']}({handle} *handle);",
    ]


def render_header(spec: dict) -> str:
    out = [
        f"/* {GENERATED_NOTE} */",
        "",
        "/*",
        f" * ferro_ta C API v{spec['version']}",
        " *",
        " * Conventions:",
        " *  - Every function returns an int32_t status (FT_OK == 0); see ft_status_message().",
        " *  - Inputs are `const double *` arrays sharing one `size_t len`.",
        " *  - Outputs are caller-allocated arrays of length `len`, written only on success.",
        " *    An output may alias an input (in-place). Any array may be NULL when len == 0.",
        " *  - Periods are int64_t (validated >= their minimum), MA types int32_t in 0..8.",
        " *  - Float parameters must be finite.",
        " *  - Leading warm-up values are NaN; output length always equals input length.",
        " *  - Streaming handles are not thread-safe; free each exactly once.",
        " */",
        "",
        "#ifndef FERRO_TA_H",
        "#define FERRO_TA_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f'#define FT_VERSION "{spec["version"]}"',
        "",
    ]
    out += [f"#define {s['name']} {s['value']}" for s in spec["status_codes"]]
    out += [
        "",
        "/** Static description of a status code. Never NULL; do not free. */",
        "const char *ft_status_message(int32_t code);",
        "/** Library version string. Static; do not free. */",
        "const char *ft_version(void);",
    ]
    group = None
    for fn in spec["functions"]:
        if fn["group"] != group:
            group = fn["group"]
            out += ["", f"/* ---- {group} " + "-" * (70 - len(group)) + " */"]
        out += ["", *c_doc(fn["doc"]), c_function(fn)]
    out += ["", "/* ---- streaming " + "-" * 61 + " */"]
    for stream in spec["streams"]:
        out += ["", *c_stream(stream)]
    out += [
        "",
        "#ifdef __cplusplus",
        '}  /* extern "C" */',
        "#endif",
        "",
        "#endif  /* FERRO_TA_H */",
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Go
# ---------------------------------------------------------------------------


def go_name(snake: str) -> str:
    """`linearreg_slope` -> `LinearregSlope`, `cdl3blackcrows` -> `Cdl3blackcrows`."""
    return "".join(part[:1].upper() + part[1:] for part in snake.split("_") if part)


def go_ident(snake: str) -> str:
    """Lower-camel local identifier: `fastk_period` -> `fastkPeriod`."""
    name = go_name(snake)
    return name[:1].lower() + name[1:]


def go_out_name(out_name: str) -> str:
    """`out` -> `out`, `out_upper` -> `upper`."""
    return "out" if out_name == "out" else go_ident(out_name.removeprefix("out_"))


def go_param_type(param: dict) -> str:
    return {"period": "int", "count": "int", "matype": "MAType", "float": "float64"}[
        param["kind"]
    ]


def go_param_arg(param: dict) -> str:
    ident = go_ident(param["name"])
    return {
        "period": f"C.int64_t({ident})",
        "count": f"C.int64_t({ident})",
        "matype": f"C.int32_t({ident})",
        "float": f"C.double({ident})",
    }[param["kind"]]


def go_doc(name: str, summary: str, doc: str) -> list[str]:
    lines = [f"// {name} {summary}"]
    if doc:
        lines.append("//")
        lines += [f"// {line}".rstrip() for line in doc.splitlines()]
    return lines


def go_signature_params(inputs: list[str], params: list[dict], input_type: str) -> str:
    parts = [f"{go_ident(name)} {input_type}" for name in inputs]
    parts += [f"{go_ident(p['name'])} {go_param_type(p)}" for p in params]
    return ", ".join(parts)


def go_function(fn: dict) -> list[str]:
    core = fn["name"].removeprefix("ft_")
    name = go_name(core)
    inputs = [go_ident(i) for i in fn["inputs"]]
    outs = [(go_out_name(o["name"]), o) for o in fn["outputs"]]
    single = len(outs) == 1
    if single:
        results = f"([]{GO_ELEM[outs[0][1]['elem']]}, error)"
    else:
        named = ", ".join(f"{n} []{GO_ELEM[o['elem']]}" for n, o in outs)
        results = f"({named}, err error)"
    zero_return = "nil, err" if single else ", ".join(["nil"] * len(outs)) + ", err"

    body = [
        *go_doc(name, f"wraps ferro_ta_core {fn['group']}::{core}.", fn["doc"]),
        f"func {name}({go_signature_params(fn['inputs'], fn['params'], '[]float64')}) {results} {{",
        f"\tn := len({inputs[0]})",
    ]
    if len(inputs) > 1:
        names = ", ".join(f'"{i}"' for i in fn["inputs"])
        lens = ", ".join(f"len({i})" for i in inputs)
        body += [
            f'\tif err := checkLengths("{name}", []string{{{names}}}, []int{{{lens}}}); err != nil {{',
            f"\t\treturn {zero_return}",
            "\t}",
        ]
    for out_name, out in outs:
        body.append(f"\t{out_name}Buf := make([]{GO_ELEM[out['elem']]}, n)")
    args = [f"inPtr({i})" for i in inputs]
    args.append("C.size_t(n)")
    args += [go_param_arg(p) for p in fn["params"]]
    args += [f"(*{C_ELEM[o['elem']]})(outPtr({n}Buf))" for n, o in outs]
    body += [
        f'\tif err := statusError("{name}", C.{fn["name"]}({", ".join(args)})); err != nil {{',
        f"\t\treturn {zero_return}",
        "\t}",
        f"\treturn {', '.join(f'{n}Buf' for n, _ in outs)}, nil",
        "}",
    ]
    return body


def go_stream(stream: dict) -> list[str]:
    name = "Stream" + go_name(stream["name"])
    handle = f"*C.{stream['handle']}"
    outs = [(go_out_name(o["name"]), o) for o in stream["outputs"]]
    single = len(outs) == 1
    if single:
        update_results = f"({GO_ELEM[outs[0][1]['elem']]}, error)"
    else:
        named = ", ".join(f"{n} {GO_ELEM[o['elem']]}" for n, o in outs)
        update_results = f"({named}, err error)"
    update_zero = "0, err" if single else ", ".join(["0"] * len(outs)) + ", err"
    closed_return = update_zero.replace("err", f'closedError("{name}.Update")')
    new_params = ", ".join(
        f"{go_ident(p['name'])} {go_param_type(p)}" for p in stream["params"]
    )
    new_args = [go_param_arg(p) for p in stream["params"]] + ["&h"]
    update_params = ", ".join(f"{go_ident(i)} float64" for i in stream["inputs"])
    update_args = ["s.h"] + [f"C.double({go_ident(i)})" for i in stream["inputs"]]
    update_args += [f"(*{C_ELEM[o['elem']]})(unsafe.Pointer(&{n}))" for n, o in outs]
    return [
        *go_doc(
            name,
            "is a stateful, bar-by-bar indicator backed by a Rust handle.",
            stream["doc"],
        ),
        "//",
        "// Methods are safe for concurrent use. Call Close when done; a finalizer",
        "// releases the handle if Close is forgotten.",
        f"type {name} struct {{",
        "\tmu sync.Mutex",
        f"\th  {handle}",
        "}",
        "",
        f"// New{name} creates a {name}.",
        f"func New{name}({new_params}) (*{name}, error) {{",
        f"\tvar h {handle}",
        f'\tif err := statusError("New{name}", C.{stream["new_fn"]}({", ".join(new_args)})); err != nil {{',
        "\t\treturn nil, err",
        "\t}",
        f"\ts := &{name}{{h: h}}",
        f"\truntime.SetFinalizer(s, (*{name}).Close)",
        "\treturn s, nil",
        "}",
        "",
        "// Update feeds one bar and returns this bar's value(s) (NaN during warm-up).",
        f"func (s *{name}) Update({update_params}) {update_results} {{",
        # Multi-output Update uses named results; a single output needs a local.
        *([f"\tvar {outs[0][0]} {GO_ELEM[outs[0][1]['elem']]}"] if single else []),
        "\ts.mu.Lock()",
        "\tdefer s.mu.Unlock()",
        "\tif s.h == nil {",
        f"\t\treturn {closed_return}",
        "\t}",
        f'\tif err := statusError("{name}.Update", C.{stream["update_fn"]}({", ".join(update_args)})); err != nil {{',
        f"\t\treturn {update_zero}",
        "\t}",
        f"\treturn {', '.join(n for n, _ in outs)}, nil",
        "}",
        "",
        "// Reset clears all state; subsequent bars warm up again.",
        f"func (s *{name}) Reset() error {{",
        "\ts.mu.Lock()",
        "\tdefer s.mu.Unlock()",
        "\tif s.h == nil {",
        f'\t\treturn closedError("{name}.Reset")',
        "\t}",
        f'\treturn statusError("{name}.Reset", C.{stream["reset_fn"]}(s.h))',
        "}",
        "",
        "// Close releases the underlying handle. It is safe to call more than once.",
        f"func (s *{name}) Close() error {{",
        "\ts.mu.Lock()",
        "\tdefer s.mu.Unlock()",
        "\tif s.h != nil {",
        f"\t\tC.{stream['free_fn']}(s.h)",
        "\t\ts.h = nil",
        "\t\truntime.SetFinalizer(s, nil)",
        "\t}",
        "\treturn nil",
        "}",
    ]


def go_file(imports: list[str], blocks: list[list[str]]) -> str:
    out = [
        "// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.",
        "",
        "package ferrota",
        "",
        "/*",
        '#include "ferro_ta.h"',
        "*/",
        'import "C"',
    ]
    if imports:
        out += ["", "import ("] + [f'\t"{i}"' for i in imports] + [")"]
    for block in blocks:
        out += [""] + block
    return "\n".join(out) + "\n"


def go_param_from_map(param: dict) -> str:
    """Golden-test expression converting a JSON number to the wrapper's param type."""
    key = f'p["{param["name"]}"]'
    return {
        "period": f"int({key})",
        "count": f"int({key})",
        "matype": f"MAType({key})",
        "float": key,
    }[param["kind"]]


def go_golden_function(fn: dict) -> list[str]:
    name = go_name(fn["name"].removeprefix("ft_"))
    args = [f'in["{i}"]' for i in fn["inputs"]] + [
        go_param_from_map(p) for p in fn["params"]
    ]
    outs = [go_out_name(o["name"]) for o in fn["outputs"]]
    results = ", ".join(outs)
    pairs = ", ".join(f'"{o["name"]}": {n}' for o, n in zip(fn["outputs"], outs))
    return [
        f'	"{fn["name"]}": func(in map[string][]float64, p map[string]float64) (map[string]any, error) {{',
        f"		{results}, err := {name}({', '.join(args)})",
        f"		return map[string]any{{{pairs}}}, err",
        "	},",
    ]


def go_golden_stream(stream: dict) -> list[str]:
    name = "Stream" + go_name(stream["name"])
    ctor_args = ", ".join(go_param_from_map(p) for p in stream["params"])
    bar_args = ", ".join(f'bar["{i}"]' for i in stream["inputs"])
    outs = [go_out_name(o["name"]) for o in stream["outputs"]]
    pairs = ", ".join(f'"{o["name"]}": {n}' for o, n in zip(stream["outputs"], outs))
    return [
        f'	"{stream["name"]}": func(p map[string]float64) (goldenStepper, error) {{',
        f"		s, err := New{name}({ctor_args})",
        "		if err != nil {",
        "			return goldenStepper{}, err",
        "		}",
        "		step := func(bar map[string]float64) (map[string]any, error) {",
        f"			{', '.join(outs)}, err := s.Update({bar_args})",
        f"			return map[string]any{{{pairs}}}, err",
        "		}",
        "		return goldenStepper{step: step, close: s.Close}, nil",
        "	},",
    ]


def render_go_golden_dispatch(spec: dict) -> str:
    out = [
        "// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.",
        "",
        "package ferrota",
        "",
        "// goldenFunctions maps each C export to its Go wrapper so golden_test.go",
        "// can replay tests/fixtures/golden/ffi_golden.json by name.",
        "var goldenFunctions = map[string]func(map[string][]float64, map[string]float64) (map[string]any, error){",
    ]
    for fn in spec["functions"]:
        out += go_golden_function(fn)
    out += [
        "}",
        "",
        "// goldenStreams builds each streaming wrapper for golden replay.",
        "var goldenStreams = map[string]func(map[string]float64) (goldenStepper, error){",
    ]
    for stream in spec["streams"]:
        out += go_golden_stream(stream)
    out += ["}", ""]
    return "\n".join(out)


def render_go(spec: dict) -> dict[Path, str]:
    groups: dict[str, list[dict]] = {}
    for fn in spec["functions"]:
        groups.setdefault(fn["group"], []).append(fn)
    files = {
        GO_DIR / f"{group}_gen.go": go_file([], [go_function(fn) for fn in fns])
        for group, fns in groups.items()
    }
    files[GO_DIR / "streaming_gen.go"] = go_file(
        ["runtime", "sync", "unsafe"], [go_stream(s) for s in spec["streams"]]
    )
    files[GO_DIR / "golden_dispatch_gen_test.go"] = render_go_golden_dispatch(spec)
    files[GO_DIR / "version_gen.go"] = "\n".join(
        [
            "// Code generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT.",
            "",
            "package ferrota",
            "",
            "// Version is the ferro_ta release this module wraps.",
            f'const Version = "{spec["version"]}"',
            "",
        ]
    )
    return files


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if outputs are stale"
    )
    args = parser.parse_args()

    spec_text = dump_spec()
    spec = json.loads(spec_text)
    header = render_header(spec)
    outputs: dict[Path, str] = {
        SPEC_PATH: spec_text,
        HEADER_PATH: header,
        GO_HEADER_PATH: header,
        **render_go(spec),
    }

    stale_generated = {
        p
        for p in [*GO_DIR.glob("*_gen.go"), *GO_DIR.glob("*_gen_test.go")]
        if p not in outputs
    }
    if args.check:
        stale = [
            p for p, text in outputs.items() if not p.exists() or p.read_text() != text
        ]
        stale += sorted(stale_generated)
        if stale:
            for path in stale:
                print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
            print("run: python3 scripts/build_ffi_bindings.py", file=sys.stderr)
            return 1
        print(
            f"ffi bindings up to date ({len(spec['functions'])} functions, {len(spec['streams'])} streams)"
        )
        return 0

    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    for path in stale_generated:
        path.unlink()
    print(
        f"wrote {len(outputs)} files ({len(spec['functions'])} functions, {len(spec['streams'])} streams)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
