// @generated by scripts/build_flutter_bridge.py — DO NOT EDIT.
// Regenerate with: python3 scripts/build_flutter_bridge.py
//
// Thin flutter_rust_bridge wrappers over `ferro_ta_core`, ported from the
// WASM bindings so all language surfaces stay in lockstep.
#![allow(clippy::too_many_arguments)]

pub fn ad(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, volume: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::volume::ad(&high, &low, &close, &volume)
}

pub fn adosc(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, volume: Vec<f64>, fastperiod: usize, slowperiod: usize) -> Vec<f64> {
    ferro_ta_core::volume::adosc(&high, &low, &close, &volume, fastperiod, slowperiod)
}

/// Average Directional Movement Index (Wilder smoothing).
///
/// # Arguments
/// - `high`       – `Float64Array` of high prices.
/// - `low`        – `Float64Array` of low prices.
/// - `close`      – `Float64Array` of close prices.
/// - `timeperiod` – look-back period (default 14, minimum 1).
///
/// # Returns
/// `Float64Array`; warm-up values are `NaN`.
pub fn adx(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::adx(&high, &low, &close, timeperiod)
}

/// All ADX components: returns [+DM, -DM, +DI, -DI, DX, ADX].
pub fn adx_all(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::momentum::adx_all(&high, &low, &close, timeperiod)
}

/// Average Directional Movement Index Rating (ADXR).
pub fn adxr(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::adxr(&high, &low, &close, timeperiod)
}

/// Aggregate tick/trade data into tick bars (every N ticks become one bar).
/// Returns `[open, high, low, close, volume]`.
pub fn aggregate_tick_bars(price: Vec<f64>, size: Vec<f64>, ticks_per_bar: usize) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::aggregation::aggregate_tick_bars(&price, &size, ticks_per_bar)
}

/// Aggregate tick data into volume bars (fixed volume threshold).
/// Returns `[open, high, low, close, volume]`.
pub fn aggregate_volume_bars_ticks(price: Vec<f64>, size: Vec<f64>, volume_threshold: f64) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::aggregation::aggregate_volume_bars_ticks(&price, &size, volume_threshold)
}

/// Annualized basis.
pub fn annualized_basis(spot: f64, future: f64, time_to_expiry: f64) -> f64 {
    ferro_ta_core::futures::basis::annualized_basis(spot, future, time_to_expiry)
}

/// Absolute Price Oscillator.
pub fn apo(close: Vec<f64>, fastperiod: usize, slowperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::apo(&close, fastperiod, slowperiod)
}

/// Aroon indicator. Returns [aroon_down, aroon_up].
pub fn aroon(high: Vec<f64>, low: Vec<f64>, timeperiod: usize) -> (Vec<f64>, Vec<f64>) {
    ferro_ta_core::momentum::aroon(&high, &low, timeperiod)
}

/// Aroon Oscillator.
pub fn aroonosc(high: Vec<f64>, low: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::aroonosc(&high, &low, timeperiod)
}

/// ATM implied volatility interpolated from strikes/vols.
pub fn atm_iv(strikes: Vec<f64>, vols: Vec<f64>, reference_price: f64) -> f64 {
    ferro_ta_core::options::surface::atm_iv(&strikes, &vols, reference_price)
}

/// Average True Range (Wilder smoothing, TA-Lib compatible).
///
/// # Arguments
/// - `high`  – `Float64Array` of high prices.
/// - `low`   – `Float64Array` of low prices.
/// - `close` – `Float64Array` of close prices.
/// - `timeperiod` – look-back period (default 14, minimum 1).
///
/// # Returns
/// `Float64Array`; first `timeperiod` values are `NaN`.
pub fn atr(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::volatility::atr(&high, &low, &close, timeperiod)
}

/// Average Price: (open + high + low + close) / 4.
pub fn avgprice(open: Vec<f64>, high: Vec<f64>, low: Vec<f64>, close: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::price_transform::avgprice(&open, &high, &low, &close)
}

/// Back-adjusted continuous contract.
pub fn back_adjusted_continuous(front: Vec<f64>, next: Vec<f64>, next_weights: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::futures::roll::back_adjusted_continuous(&front, &next, &next_weights)
}

/// Bollinger Bands (SMA ± k × rolling standard deviation).
///
/// # Arguments
/// - `close` – `Float64Array` of close prices.
/// - `timeperiod` – look-back window (default 5, minimum 1).
/// - `nbdevup` – multiplier for the upper band (default 2.0).
/// - `nbdevdn` – multiplier for the lower band (default 2.0).
///
/// # Returns
/// A `js_sys::Array` containing three `Float64Array` elements:
/// `[upperband, middleband, lowerband]`.
pub fn bbands(close: Vec<f64>, timeperiod: usize, nbdevup: f64, nbdevdn: f64) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::overlap::bbands(&close, timeperiod, nbdevup, nbdevdn)
}

/// Full-sample OLS beta of asset vs benchmark returns.
pub fn beta_full(asset_returns: Vec<f64>, benchmark_returns: Vec<f64>) -> f64 {
    ferro_ta_core::portfolio::beta_full(&asset_returns, &benchmark_returns)
}

/// Rolling beta (return-based regression).
pub fn beta_rolling(real0: Vec<f64>, real1: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::statistic::beta(&real0, &real1, timeperiod)
}

/// Balance of Power.
pub fn bop(open: Vec<f64>, high: Vec<f64>, low: Vec<f64>, close: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::momentum::bop(&open, &high, &low, &close)
}

/// Calendar spreads between consecutive futures prices.
pub fn calendar_spreads(futures_prices: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::futures::curve::calendar_spreads(&futures_prices)
}

/// Carry spread.
pub fn carry_spread(spot: f64, future: f64, rate: f64, time_to_expiry: f64) -> f64 {
    ferro_ta_core::futures::basis::carry_spread(spot, future, rate, time_to_expiry)
}

/// Commodity Channel Index.
pub fn cci(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::cci(&high, &low, &close, timeperiod)
}

/// Chandelier Exit — ATR-based trailing stop levels.
/// Returns `[long_exit, short_exit]`.
pub fn chandelier_exit(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize, multiplier: f64) -> (Vec<f64>, Vec<f64>) {
    ferro_ta_core::extended::chandelier_exit(&high, &low, &close, timeperiod, multiplier)
}

/// Detect cross-over/cross-under events between fast and slow series.
/// Returns Int8Array: 1 = bullish, -1 = bearish, 0 = none.
pub fn check_cross(fast: Vec<f64>, slow: Vec<f64>) -> Vec<i8> {
    ferro_ta_core::alerts::check_cross(&fast, &slow)
}

/// Fire an alert when series crosses a threshold level.
/// direction: 1 = cross above, -1 = cross below.
/// Returns Int8Array: 1 at crossing bars, 0 elsewhere.
pub fn check_threshold(series: Vec<f64>, level: f64, direction: i32) -> Vec<i8> {
    ferro_ta_core::alerts::check_threshold(&series, level, direction)
}

/// Choppiness Index — measures market choppiness vs trending.
pub fn choppiness_index(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::extended::choppiness_index(&high, &low, &close, timeperiod)
}

/// Close-to-close realised volatility (rolling).
///
/// First `window - 1` values are `NaN`.
pub fn close_to_close_vol(close: Vec<f64>, window: usize, trading_days: f64) -> Vec<f64> {
    ferro_ta_core::options::realized_vol::close_to_close_vol(&close, window, trading_days)
}

/// Chande Momentum Oscillator.
pub fn cmo(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::cmo(&close, timeperiod)
}

/// Rolling Pearson correlation.
pub fn correl(real0: Vec<f64>, real1: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::statistic::correl(&real0, &real1, timeperiod)
}

/// Curve slope (linear regression).
pub fn curve_slope(tenors: Vec<f64>, futures_prices: Vec<f64>) -> f64 {
    ferro_ta_core::futures::curve::curve_slope(&tenors, &futures_prices)
}

/// Double Exponential Moving Average.
pub fn dema(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::dema(&close, timeperiod)
}

/// Detect structural breaks using CUSUM approach.
pub fn detect_breaks_cusum(series: Vec<f64>, window: usize, threshold: f64, slack: f64) -> Vec<i8> {
    ferro_ta_core::regime::detect_breaks_cusum(&series, window, threshold, slack)
}

/// Donchian Channels — rolling highest high / lowest low.
/// Returns `[upper, middle, lower]`.
pub fn donchian(high: Vec<f64>, low: Vec<f64>, timeperiod: usize) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::extended::donchian(&high, &low, timeperiod)
}

/// Directional Movement Index (DX).
pub fn dx(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::dx(&high, &low, &close, timeperiod)
}

/// Exponential Moving Average (SMA-seeded).
///
/// # Arguments
/// - `close` – `Float64Array` of close prices.
/// - `timeperiod` – look-back period (default 30, minimum 1).
///
/// # Returns
/// `Float64Array` with the first `timeperiod - 1` values set to `NaN`.
pub fn ema(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::ema(&close, timeperiod)
}

/// Extract trade PnL and hold durations from positions and strategy returns.
/// Returns `[pnl, hold_durations]`.
pub fn extract_trades(positions: Vec<f64>, strategy_returns: Vec<f64>) -> (Vec<f64>, Vec<f64>) {
    ferro_ta_core::attribution::extract_trades(&positions, &strategy_returns)
}

/// Forward-fill NaN values in a 1-D array.
pub fn forward_fill_nan(values: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::chunked::forward_fill_nan(&values)
}

/// Cumulative PnL from funding rate payments.
pub fn funding_cumulative_pnl(position_size: Vec<f64>, funding_rate: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::crypto::funding_cumulative_pnl(&position_size, &funding_rate)
}

/// Futures basis: future - spot.
pub fn futures_basis(spot: f64, future: f64) -> f64 {
    ferro_ta_core::futures::basis::basis(spot, future)
}

/// Garman-Klass OHLC volatility estimator (rolling).
pub fn garman_klass_vol(open: Vec<f64>, high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, window: usize, trading_days: f64) -> Vec<f64> {
    ferro_ta_core::options::realized_vol::garman_klass_vol(&open, &high, &low, &close, window, trading_days)
}

pub fn ht_dcperiod(close: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::cycle::ht_dcperiod(&close)
}

pub fn ht_dcphase(close: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::cycle::ht_dcphase(&close)
}

pub fn ht_phasor(close: Vec<f64>) -> (Vec<f64>, Vec<f64>) {
    ferro_ta_core::cycle::ht_phasor(&close)
}

pub fn ht_sine(close: Vec<f64>) -> (Vec<f64>, Vec<f64>) {
    ferro_ta_core::cycle::ht_sine(&close)
}

pub fn ht_trendline(close: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::cycle::ht_trendline(&close)
}

/// Hull Moving Average (HMA).
pub fn hull_ma(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::extended::hull_ma(&close, timeperiod)
}

/// Ichimoku Cloud (Ichimoku Kinko Hyo).
/// Returns `[tenkan, kijun, senkou_a, senkou_b, chikou]`.
pub fn ichimoku(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, tenkan: usize, kijun: usize, senkou_b: usize, displacement: usize) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::extended::ichimoku(&high, &low, &close, tenkan, kijun, senkou_b, displacement)
}

/// Implied carry rate.
pub fn implied_carry_rate(spot: f64, future: f64, time_to_expiry: f64) -> f64 {
    ferro_ta_core::futures::basis::implied_carry_rate(spot, future, time_to_expiry)
}

/// IV Percentile over a rolling window.
pub fn iv_percentile(iv_series: Vec<f64>, window: usize) -> Vec<f64> {
    ferro_ta_core::options::iv::iv_percentile(&iv_series, window)
}

/// IV Rank over a rolling window.
pub fn iv_rank(iv_series: Vec<f64>, window: usize) -> Vec<f64> {
    ferro_ta_core::options::iv::iv_rank(&iv_series, window)
}

/// IV Z-Score over a rolling window.
pub fn iv_zscore(iv_series: Vec<f64>, window: usize) -> Vec<f64> {
    ferro_ta_core::options::iv::iv_zscore(&iv_series, window)
}

/// Kaufman Adaptive Moving Average.
pub fn kama(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::kama(&close, timeperiod)
}

/// Keltner Channels — EMA +/- (multiplier x ATR).
/// Returns `[upper, middle, lower]`.
pub fn keltner_channels(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize, atr_period: usize, multiplier: f64) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::extended::keltner_channels(&high, &low, &close, timeperiod, atr_period, multiplier)
}

/// Linear interpolation helper.
pub fn linear_interpolate(xs: Vec<f64>, ys: Vec<f64>, target: f64) -> f64 {
    ferro_ta_core::options::surface::linear_interpolate(&xs, &ys, target)
}

/// Linear regression fitted value.
pub fn linearreg(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::statistic::linearreg(&close, timeperiod)
}

/// Linear regression angle in degrees.
pub fn linearreg_angle(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::statistic::linearreg_angle(&close, timeperiod)
}

/// Linear regression intercept.
pub fn linearreg_intercept(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::statistic::linearreg_intercept(&close, timeperiod)
}

/// Linear regression slope.
pub fn linearreg_slope(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::statistic::linearreg_slope(&close, timeperiod)
}

/// Generic Moving Average (matype: 0=SMA, 1=EMA, 2=WMA, 3=DEMA, 4=TEMA, 5=TRIMA, 6=KAMA, 7=T3).
pub fn ma(close: Vec<f64>, timeperiod: usize, matype: u8) -> Vec<f64> {
    ferro_ta_core::overlap::ma(&close, timeperiod, matype)
}

/// Moving Average Convergence/Divergence.
///
/// # Arguments
/// - `close`        – `Float64Array` of close prices.
/// - `fastperiod`   – fast EMA period (default 12).
/// - `slowperiod`   – slow EMA period (default 26).
/// - `signalperiod` – signal EMA period (default 9).
///
/// # Returns
/// A `js_sys::Array` containing three `Float64Array` elements:
/// `[macd_line, signal_line, histogram]`.
pub fn macd(close: Vec<f64>, fastperiod: usize, slowperiod: usize, signalperiod: usize) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::overlap::macd(&close, fastperiod, slowperiod, signalperiod)
}

/// MACD with configurable MA types. Returns [macd, signal, histogram].
pub fn macdext(close: Vec<f64>, fastperiod: usize, fastmatype: u8, slowperiod: usize, slowmatype: u8, signalperiod: usize, signalmatype: u8) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::overlap::macdext(&close, fastperiod, fastmatype, slowperiod, slowmatype, signalperiod, signalmatype)
}

/// MACD with fixed 12/26 periods. Returns [macd, signal, histogram].
pub fn macdfix(close: Vec<f64>, signalperiod: usize) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::overlap::macdfix(&close, signalperiod)
}

/// MESA Adaptive Moving Average. Returns [mama, fama].
pub fn mama(close: Vec<f64>, fastlimit: f64, slowlimit: f64) -> (Vec<f64>, Vec<f64>) {
    ferro_ta_core::overlap::mama(&close, fastlimit, slowlimit)
}

/// Element-wise addition.
pub fn math_add(a: Vec<f64>, b: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::math::add(&a, &b)
}

/// Element-wise division.
pub fn math_div(a: Vec<f64>, b: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::math::div(&a, &b)
}

/// Element-wise multiplication.
pub fn math_mult(a: Vec<f64>, b: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::math::mult(&a, &b)
}

/// Element-wise subtraction.
pub fn math_sub(a: Vec<f64>, b: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::math::sub(&a, &b)
}

/// Moving Average with Variable Period.
pub fn mavp(close: Vec<f64>, periods: Vec<f64>, minperiod: usize, maxperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::mavp(&close, &periods, minperiod, maxperiod)
}

/// Median Price: (high + low) / 2.
pub fn medprice(high: Vec<f64>, low: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::price_transform::medprice(&high, &low)
}

/// Money Flow Index.
///
/// # Arguments
/// - `high`       – `Float64Array` of high prices.
/// - `low`        – `Float64Array` of low prices.
/// - `close`      – `Float64Array` of close prices.
/// - `volume`     – `Float64Array` of volume values.
/// - `timeperiod` – look-back period (default 14, minimum 1).
///
/// # Returns
/// `Float64Array`; warm-up values are `NaN`.
pub fn mfi(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, volume: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::volume::mfi(&high, &low, &close, &volume, timeperiod)
}

/// Midpoint over rolling window.
pub fn midpoint(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::midpoint(&close, timeperiod)
}

/// MidPrice over rolling window.
pub fn midprice(high: Vec<f64>, low: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::midprice(&high, &low, timeperiod)
}

/// Minus Directional Indicator (-DI).
pub fn minus_di(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::minus_di(&high, &low, &close, timeperiod)
}

/// Minus Directional Movement (-DM).
pub fn minus_dm(high: Vec<f64>, low: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::minus_dm(&high, &low, timeperiod)
}

/// Momentum — difference between current close and close *timeperiod* bars ago.
///
/// # Arguments
/// - `close`      – `Float64Array` of close prices.
/// - `timeperiod` – look-back window (default 10, minimum 1).
///
/// # Returns
/// `Float64Array`; first `timeperiod` values are `NaN`.
pub fn mom(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::mom(&close, timeperiod)
}

/// Normalized Average True Range: ATR / close * 100.
pub fn natr(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::volatility::natr(&high, &low, &close, timeperiod)
}

/// On-Balance Volume.
///
/// # Arguments
/// - `close`  – `Float64Array` of close prices.
/// - `volume` – `Float64Array` of volume values.
///
/// # Returns
/// `Float64Array` — cumulative OBV.
pub fn obv(close: Vec<f64>, volume: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::volume::obv(&close, &volume)
}

/// Put-call parity residual.
pub fn parity_gap(call_price: f64, put_price: f64, spot: f64, strike: f64, rate: f64, carry: f64, time_to_expiry: f64) -> f64 {
    ferro_ta_core::futures::synthetic::parity_gap(call_price, put_price, spot, strike, rate, carry, time_to_expiry)
}

/// Parkinson (high-low) volatility estimator (rolling).
pub fn parkinson_vol(high: Vec<f64>, low: Vec<f64>, window: usize, trading_days: f64) -> Vec<f64> {
    ferro_ta_core::options::realized_vol::parkinson_vol(&high, &low, window, trading_days)
}

/// Pivot Points — support / resistance levels.
/// Returns `[pivot, r1, s1, r2, s2]`.
pub fn pivot_points(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, method: String) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::extended::pivot_points(&high, &low, &close, &method)
}

/// Plus Directional Indicator (+DI).
pub fn plus_di(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::plus_di(&high, &low, &close, timeperiod)
}

/// Plus Directional Movement (+DM).
pub fn plus_dm(high: Vec<f64>, low: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::plus_dm(&high, &low, timeperiod)
}

/// Percentage Price Oscillator. Returns [ppo, signal, histogram].
pub fn ppo(close: Vec<f64>, fastperiod: usize, slowperiod: usize, signalperiod: usize) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::momentum::ppo(&close, fastperiod, slowperiod, signalperiod)
}

/// Put-call parity deviation: `C - P - (S·e^{-qT} - K·e^{-rT})`.
///
/// Returns 0 at no-arbitrage.
pub fn put_call_parity_deviation(call_price: f64, put_price: f64, spot: f64, strike: f64, rate: f64, carry: f64, time_to_expiry: f64) -> f64 {
    ferro_ta_core::options::pricing::put_call_parity_deviation(call_price, put_price, spot, strike, rate, carry, time_to_expiry)
}

/// Compute fractional rank of each element (1-based, ascending).
pub fn rank_series(x: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::signals::rank_values(&x)
}

/// Rank values (percentile ranking [0, 100]).
pub fn rank_values(x: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::signals::rank_values(&x)
}

/// Ratio between two series: a / b (NaN where b is zero).
pub fn ratio(a: Vec<f64>, b: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::portfolio::ratio(&a, &b)
}

/// Ratio-adjusted continuous contract.
pub fn ratio_adjusted_continuous(front: Vec<f64>, next: Vec<f64>, next_weights: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::futures::roll::ratio_adjusted_continuous(&front, &next, &next_weights)
}

/// Label bars as trend (1), range (0), or NaN (-1) based on ADX threshold.
pub fn regime_adx(adx: Vec<f64>, threshold: f64) -> Vec<i8> {
    ferro_ta_core::regime::regime_adx(&adx, threshold)
}

/// Label bars using ADX + ATR-ratio combined rule.
pub fn regime_combined(adx: Vec<f64>, atr: Vec<f64>, close: Vec<f64>, adx_threshold: f64, atr_pct_threshold: f64) -> Vec<i8> {
    ferro_ta_core::regime::regime_combined(&adx, &atr, &close, adx_threshold, atr_pct_threshold)
}

/// Relative strength of asset vs benchmark (cumulative return ratio).
pub fn relative_strength(asset_returns: Vec<f64>, benchmark_returns: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::portfolio::relative_strength(&asset_returns, &benchmark_returns)
}

/// Rate of Change: `(close[i] - close[i-p]) / close[i-p] * 100`.
pub fn roc(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::roc(&close, timeperiod)
}

/// Rate of Change Percentage.
pub fn rocp(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::rocp(&close, timeperiod)
}

/// Rate of Change Ratio.
pub fn rocr(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::rocr(&close, timeperiod)
}

/// Rate of Change Ratio x 100.
pub fn rocr100(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::rocr100(&close, timeperiod)
}

/// Rogers-Satchell OHLC volatility estimator (rolling).
pub fn rogers_satchell_vol(open: Vec<f64>, high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, window: usize, trading_days: f64) -> Vec<f64> {
    ferro_ta_core::options::realized_vol::rogers_satchell_vol(&open, &high, &low, &close, window, trading_days)
}

/// Roll yield.
pub fn roll_yield(front_price: f64, next_price: f64, time_to_expiry: f64) -> f64 {
    ferro_ta_core::futures::roll::roll_yield(front_price, next_price, time_to_expiry)
}

/// Rolling beta of asset vs benchmark over a sliding window.
pub fn rolling_beta(asset: Vec<f64>, benchmark: Vec<f64>, window: usize) -> Vec<f64> {
    ferro_ta_core::portfolio::rolling_beta(&asset, &benchmark, window)
}

/// Rolling maximum over timeperiod bars.
pub fn rolling_max(real: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::math_ops::rolling_max(&real, timeperiod)
}

/// Rolling minimum over timeperiod bars.
pub fn rolling_min(real: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::math_ops::rolling_min(&real, timeperiod)
}

/// Rolling sum over timeperiod bars.
pub fn rolling_sum(real: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::math_ops::rolling_sum(&real, timeperiod)
}

/// Detect volatility regime breaks using rolling variance ratio.
pub fn rolling_variance_break(series: Vec<f64>, short_window: usize, long_window: usize, threshold: f64) -> Vec<i8> {
    ferro_ta_core::regime::rolling_variance_break(&series, short_window, long_window, threshold)
}

/// Relative Strength Index (Wilder smoothing).
///
/// # Arguments
/// - `close` – `Float64Array` of close prices.
/// - `timeperiod` – look-back period (default 14, minimum 1).
///
/// # Returns
/// `Float64Array` — values in `[0, 100]`; first `timeperiod` values are `NaN`.
pub fn rsi(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::rsi(&close, timeperiod)
}

/// RSI threshold signals.
pub fn rsi_threshold_signals(close: Vec<f64>, timeperiod: usize, oversold: f64, overbought: f64) -> Vec<f64> {
    ferro_ta_core::backtest::rsi_threshold_signals(&close, timeperiod, oversold, overbought)
}

/// Parabolic SAR.
pub fn sar(high: Vec<f64>, low: Vec<f64>, acceleration: f64, maximum: f64) -> Vec<f64> {
    ferro_ta_core::overlap::sar(&high, &low, acceleration, maximum)
}

/// Parabolic SAR Extended.
pub fn sarext(high: Vec<f64>, low: Vec<f64>, startvalue: f64, offsetonreverse: f64, accelerationinitlong: f64, accelerationlong: f64, accelerationmaxlong: f64, accelerationinitshort: f64, accelerationshort: f64, accelerationmaxshort: f64) -> Vec<f64> {
    ferro_ta_core::overlap::sarext(&high, &low, startvalue, offsetonreverse, accelerationinitlong, accelerationlong, accelerationmaxlong, accelerationinitshort, accelerationshort, accelerationmaxshort)
}

/// Simple single-asset backtest. Returns [positions, strategy_returns, equity].
pub fn single_asset_backtest(close: Vec<f64>, signals: Vec<f64>, commission_per_trade: f64, slippage_bps: f64) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::backtest::single_asset_backtest(&close, &signals, commission_per_trade, slippage_bps)
}

/// Simple Moving Average.
///
/// # Arguments
/// - `close` – `Float64Array` of close prices.
/// - `timeperiod` – look-back window (default 30, minimum 1).
///
/// # Returns
/// `Float64Array` with the first `timeperiod - 1` values set to `NaN`.
pub fn sma(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::sma(&close, timeperiod)
}

/// Spread between two series: a - hedge * b.
pub fn spread(a: Vec<f64>, b: Vec<f64>, hedge: f64) -> Vec<f64> {
    ferro_ta_core::portfolio::spread(&a, &b, hedge)
}

/// Rolling population standard deviation scaled by `nbdev`.
pub fn stddev(close: Vec<f64>, timeperiod: usize, nbdev: f64) -> Vec<f64> {
    ferro_ta_core::statistic::stddev(&close, timeperiod, nbdev)
}

/// Full Stochastic Oscillator (slow %K and slow %D).
pub fn stoch(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, fastk_period: usize, slowk_period: usize, slowd_period: usize) -> (Vec<f64>, Vec<f64>) {
    ferro_ta_core::momentum::stoch(&high, &low, &close, fastk_period, slowk_period, slowd_period)
}

/// Stochastic RSI. Returns [fastk, fastd].
pub fn stochrsi(close: Vec<f64>, timeperiod: usize, fastk_period: usize, fastd_period: usize) -> (Vec<f64>, Vec<f64>) {
    ferro_ta_core::momentum::stochrsi(&close, timeperiod, fastk_period, fastd_period)
}

/// Synthetic forward price from put-call parity.
pub fn synthetic_forward(call_price: f64, put_price: f64, strike: f64, rate: f64, time_to_expiry: f64) -> f64 {
    ferro_ta_core::futures::synthetic::synthetic_forward(call_price, put_price, strike, rate, time_to_expiry)
}

/// Synthetic spot implied by put-call parity.
pub fn synthetic_spot(call_price: f64, put_price: f64, strike: f64, rate: f64, carry: f64, time_to_expiry: f64) -> f64 {
    ferro_ta_core::futures::synthetic::synthetic_spot(call_price, put_price, strike, rate, carry, time_to_expiry)
}

/// Tillson T3.
pub fn t3(close: Vec<f64>, timeperiod: usize, vfactor: f64) -> Vec<f64> {
    ferro_ta_core::overlap::t3(&close, timeperiod, vfactor)
}

/// Triple Exponential Moving Average.
pub fn tema(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::tema(&close, timeperiod)
}

/// Term structure slope.
pub fn term_structure_slope(tenors: Vec<f64>, atm_ivs: Vec<f64>) -> f64 {
    ferro_ta_core::options::surface::term_structure_slope(&tenors, &atm_ivs)
}

/// True Range.
pub fn trange(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::volatility::trange(&high, &low, &close)
}

/// Remove first overlap elements from an array.
pub fn trim_overlap(chunk_out: Vec<f64>, overlap: usize) -> Vec<f64> {
    ferro_ta_core::chunked::trim_overlap(&chunk_out, overlap)
}

/// Triangular Moving Average.
pub fn trima(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::trima(&close, timeperiod)
}

/// TRIX: 1-period rate of change of triple-smoothed EMA.
pub fn trix_indicator(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::trix(&close, timeperiod)
}

/// Time Series Forecast.
pub fn tsf(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::statistic::tsf(&close, timeperiod)
}

/// Typical Price: (high + low + close) / 3.
pub fn typprice(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::price_transform::typprice(&high, &low, &close)
}

/// Ultimate Oscillator.
pub fn ultosc(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod1: usize, timeperiod2: usize, timeperiod3: usize) -> Vec<f64> {
    ferro_ta_core::momentum::ultosc(&high, &low, &close, timeperiod1, timeperiod2, timeperiod3)
}

/// Rolling population variance scaled by `nbdev²`.
pub fn var(close: Vec<f64>, timeperiod: usize, nbdev: f64) -> Vec<f64> {
    ferro_ta_core::statistic::var(&close, timeperiod, nbdev)
}

/// Aggregate OHLCV data into volume bars of a fixed volume threshold.
/// Returns `[open, high, low, close, volume]`.
pub fn volume_bars(open: Vec<f64>, high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, volume: Vec<f64>, volume_threshold: f64) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    ferro_ta_core::resampling::volume_bars(&open, &high, &low, &close, &volume, volume_threshold)
}

/// Volume Weighted Average Price (cumulative or rolling).
pub fn vwap(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, volume: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::extended::vwap(&high, &low, &close, &volume, timeperiod)
}

/// Volume Weighted Moving Average.
pub fn vwma(close: Vec<f64>, volume: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::extended::vwma(&close, &volume, timeperiod)
}

/// Weighted Close Price: (high + low + close * 2) / 4.
pub fn wclprice(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::price_transform::wclprice(&high, &low, &close)
}

/// Weighted continuous contract.
pub fn weighted_continuous(front: Vec<f64>, next: Vec<f64>, next_weights: Vec<f64>) -> Vec<f64> {
    ferro_ta_core::futures::roll::weighted_continuous(&front, &next, &next_weights)
}

/// Williams %R.
pub fn willr(high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::momentum::willr(&high, &low, &close, timeperiod)
}

/// Weighted Moving Average.
///
/// # Arguments
/// - `close` – `Float64Array` of close prices.
/// - `timeperiod` – look-back window (default 30, minimum 1).
///
/// # Returns
/// `Float64Array` with the first `timeperiod - 1` values set to `NaN`.
pub fn wma(close: Vec<f64>, timeperiod: usize) -> Vec<f64> {
    ferro_ta_core::overlap::wma(&close, timeperiod)
}

/// Yang-Zhang OHLC volatility estimator (rolling).
///
/// Most efficient estimator — handles overnight gaps.
pub fn yang_zhang_vol(open: Vec<f64>, high: Vec<f64>, low: Vec<f64>, close: Vec<f64>, window: usize, trading_days: f64) -> Vec<f64> {
    ferro_ta_core::options::realized_vol::yang_zhang_vol(&open, &high, &low, &close, window, trading_days)
}

/// Rolling Z-score of a 1-D series.
pub fn zscore_series(x: Vec<f64>, window: usize) -> Vec<f64> {
    ferro_ta_core::portfolio::zscore_series(&x, window)
}
