//! Public bridge surface scanned by flutter_rust_bridge.
//!
//! Every indicator is a plain-Rust `pub fn` over `ferro_ta_core`, generated by
//! `scripts/build_flutter_bridge.py` from the WASM bindings so all language
//! surfaces stay in lockstep.

pub mod indicators;
