"""Shared constants for the FFI code generators."""

GENERATED_NOTE = (
    "Generated by scripts/build_ffi_bindings.py from ffi_spec.json. DO NOT EDIT."
)


def with_requires(fn: dict, error_name: str = "FT_ERR_INVALID_PARAM") -> str:
    """Doc text plus the cross-parameter rule, if any."""
    if not fn.get("requires"):
        return fn["doc"]
    return f"{fn['doc']}\nRequires: {fn['requires']} (else {error_name})."
